---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret renovate-operator-oidc-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *secret
    template:
      data:
        RENOVATE_OPERATOR_CLIENT_ID: "{{ .RENOVATE_OPERATOR_CLIENT_ID }}"
        RENOVATE_OPERATOR_CLIENT_SECRET: "{{ .RENOVATE_OPERATOR_CLIENT_SECRET }}"
        RENOVATE_OPERATOR_OIDC_ISSUER: "{{ .RENOVATE_OPERATOR_OIDC_ISSUER }}"
        RENOVATE_OPERATOR_SESSION_SECRET: "{{ .RENOVATE_OPERATOR_SESSION_SECRET }}"
  dataFrom:
    - extract:
        key: renovate-operator
