---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-data-pvc
  namespace: ai
  labels:
    app.kubernetes.io/name: &name ollama
    app.kubernetes.io/instance: *name
    snapshot.home.arpa/enabled: "true"
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: ceph-block
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-models-pvc
  namespace: ai
  labels:
    app.kubernetes.io/name: &name ollama
    app.kubernetes.io/instance: *name
    snapshot.home.arpa/enabled: "true"
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: ceph-block
  resources:
    requests:
      storage: 500Gi
