---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app unifi
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: unifi
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
#  dependsOn:
#    - name: local-path-provisioner
#      namespace: storage
#    - name: volsync
#      namespace: volsync
  values:
    defaultPodOptions:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 50
            preference:
              matchExpressions:
              - key: node-role.kubernetes.io/worker
                operator: In
                values:
                - worker

    controllers:
      app:
        type: deployment
        replicas: 1
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsUser: 999
            runAsGroup: 999
            fsGroup: 999
            fsGroupChangePolicy: "OnRootMismatch"
        containers:
          app:
            nameOverride: *app
            image:
              repository: jacobalberty/unifi
              tag: v10.0.162@sha256:896c0ab82d33300694dae82982fd7094497afcbea0be92cadc1e94bfead731d3
              pullPolicy: IfNotPresent
            env:
              TZ: ${TIMEZONE}
              RUNAS_UID0: "false"
              UNIFI_UID: "999"
              UNIFI_GID: "999"
              UNIFI_STDOUT: "true"
              # JVM_INIT_HEAP_SIZE: null
              JVM_MAX_HEAP_SIZE: 1024M
              SYSTEM_IP: "10.200.15.227"
            envFrom:
              - secretRef:
                  name: cluster-secrets
            resources:
              requests:
                memory: 512Mi
                cpu: 100m
              limits:
                memory: 2Gi
            probes:
              liveness:
                enabled: true
                port: 8080
              readiness:
                enabled: true
                port: 8080
              startup:
                enabled: true
                port: 8080
#        statefulset:
#          volumeClaimTemplates:
#            - name: config
#              accessMode: ReadWriteOnce
#              size: 10Gi
#              storageClass: local-hostpath
#              globalMounts:
#                - path: /unifi
    service:
      app:
#        controller: *app
        type: LoadBalancer
        externalTrafficPolicy: Cluster
        annotations:
          external-dns.alpha.kubernetes.io/hostname: "unifitalos.${SECRET_DOMAIN}"
          external-dns.kubernetes.io/hostname: "unifitalos.${SECRET_DOMAIN}"
          lbipam.cilium.io/ips: "10.200.15.227"
        ports:
          http:
            primary: true
            port: 8080
            protocol: HTTP
          stun:
            port: 3478
            protocol: UDP
          https:
            port: &port 8443
            protocol: HTTPS
          secure-redirect:
            port: 8843
            protocol: HTTPS
          http-redirect:
            port: 8880
            protocol: HTTP
          speedtest:
            port: 6789
            protocol: TCP
          unifi-disc:
            port: 10001
            protocol: UDP
          unifi-disc-12:
            port: 1900
            protocol: UDP
          syslog:
            protocol: UDP
            port: 5514

    route:
      app:
#        annotations:
#          gethomepage.dev/enabled: "true"
#          gethomepage.dev/group: Home
#          gethomepage.dev/name: "Unifi Controller Talos"
#          gethomepage.dev/icon: sh-ubiquiti-unifi
#          gethomepage.dev/description: "Unifi Controller Talos"
#          gethomepage.dev/widget.type: unifi
#          gethomepage.dev/widget.url: http://unifitalos:8080
        hostnames: ["unifitalos.${SECRET_DOMAIN}"]
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: *port
            timeouts:
              request: 0s  # websocket, never time out
              backendRequest: 0s  # websocket, never time out

    persistence:
      data:
        enabled: true
        existingClaim: unifi-config
        globalMounts:
          - path: "/unifi"
