---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app frigate
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: frigate
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      frigate:
        pod:
          resourceClaims:
            - name: gpu
              resourceClaimTemplateName: frigate-gpu
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/blakeblackshear/frigate
              tag: "0.18.0"
            env:
              TZ: Australia/Melbourne
              LIBVA_DRIVER_NAME: iHD
            envFrom:
              - secretRef:
                  name: frigate-secret
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/version
                    port: &port 5000
                  initialDelaySeconds: 120
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              privileged: true
            resources:
              claims:
                - name: gpu
              requests:
                cpu: 100m
              limits:
                memory: 4Gi
    defaultPodOptions:
#      affinity:
#        podAntiAffinity:
#          requiredDuringSchedulingIgnoredDuringExecution:
#            - labelSelector:
#                matchExpressions:
#                  - key: app.kubernetes.io/name
#                    operator: In
#                    values: ["plex"]
#              topologyKey: kubernetes.io/hostname
#      affinity:
#        nodeAffinity:
#          requiredDuringSchedulingIgnoredDuringExecution:
#            nodeSelectorTerms:
#            - matchExpressions:
#              - key: kubernetes.io/hostname
#                operator: In
#                values:
#                - k3sworker1
      nodeSelector:
        google.feature.node.kubernetes.io/coral: "true"
#        intel.feature.node.kubernetes.io/gpu: "true"
    service:
      app:
#        controller: frigate
        annotations:
          lbipam.cilium.io/ips: ${SVC_FRIGATE_ADDR}
        type: LoadBalancer
        ports:
          http:
            port: *port
          go2rtc:
            port: 1984
          rtsp:
            port: 8554
          webrtc:
            port: 8555
            protocol: TCP
          webrtc-udp:
            port: 8555
            protocol: UDP

    route:
      app:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Infrastructure
          gethomepage.dev/name: Frigate
          gethomepage.dev/icon: frigate.svg
          gethomepage.dev/pod-selector: app.kubernetes.io/name=frigate
          gethomepage.dev/widget.type: frigate
          gethomepage.dev/widget.url: "http://10.200.15.238:5000"
        hostnames: ["video.davidstewen.com"]
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: *port

    persistence:
      config:
        existingClaim: ${VOLSYNC_CLAIM}
      config-file:
        type: configMap
        name: frigate-configmap
        globalMounts:
          - path: /config/config.yml
            subPath: config.yml
            readOnly: false
      cache:
        type: emptyDir
        medium: Memory
        sizeLimit: 4Gi
        globalMounts:
          - path: /dev/shm
      coral:
        type: hostPath
        hostPath: /dev/apex_0
        hostPathType: CharDevice
      media:
        type: nfs
        server: 192.168.10.15
        path: /volume2/piNFS01/flux-cluster/media/frigate
        globalMounts:
          - path: /media/frigate
