---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: ftb-2
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 5.2.0
  url: oci://ghcr.io/itzg/minecraft-server-charts/minecraft
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ftb-2
spec:
  chartRef:
    kind: OCIRepository
    name: ftb-2
  #  dependsOn: []
  interval: 15m
  values:
    #    affinity:
    #      nodeAffinity:
    #        requiredDuringSchedulingIgnoredDuringExecution:
    #          nodeSelectorTerms:
    #          - matchExpressions:
    #            - key: kubernetes.io/arch
    #              operator: In
    #              values:
    #              - amd64
    #        preferredDuringSchedulingIgnoredDuringExecution:
    #        - weight: 50
    #          preference:
    #            matchExpressions:
    #            - key: node-role.kubernetes.io/worker
    #              operator: In
    #              values:
    #              - worker
    resources:
      requests:
        memory: 4G
      limits:
        memory: 16G
    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
    securityContext:
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
      allowPrivilegeEscalation: false
    serviceAnnotations:
      lbipam.cilium.io/ips: "10.200.15.249"
    #      mc-router.itzg.me/externalServerName: "mcsv.${SECRET_DOMAIN}"
    livenessProbe:
      command:
        - mc-health
      initialDelaySeconds: 120
      periodSeconds: 10
    readinessProbe:
      command:
        - mc-health
      initialDelaySeconds: 120
      periodSeconds: 10
    startupProbe:
      command:
        - mc-health
      enabled: true
      failureThreshold: 60
      periodSeconds: 10
    image:
      repository: itzg/minecraft-server
      tag: java21
    minecraftServer:
      eula: "TRUE"
      version: "1.21.1"
      type: "FTBA"
      forceReDownload: true
      ftbModpackId: "126"
      ftbModpackVersionId: "100464"
      difficulty: normal
      whitelist: "dneck77"
      ops: "dneck77"
      gameMode: survival
      pvp: false
      onlineMode: true
      jvmXXOpts: "-XX:MaxRAMPercentage=75"
      memory: 12288M
      serviceType: LoadBalancer
      loadBalancerIP: "10.200.15.249"
      #      servicePort: 25565
      motd: "TurtleTest FTB:R"
      externalTrafficPolicy: Cluster
      allowNether: true
      worldSaveName: TurtleTest
      viewDistance: 12
      overrideServerProperties: true
      modUrls:
        - https://github.com/cpburnz/minecraft-prometheus-exporter/releases/download/1.21.1-neoforge-1.2.1/Prometheus-Exporter-1.21.1-neoforge-1.2.1.jar
      extraPorts:
        #      extraPorts:
        #      - name: metrics
        #        containerPort: 9225
        #        protocol: TCP
        #        service:
        #          enabled: true
        #          embedded: false
        #          type: ClusterIP
        #          port: 9225
        #        ingress:
        #          enabled: false
        #      - name: map
        #        containerPort: 8123
        #        protocol: TCP
        #        service:
        #          enabled: true
        #          embedded: false
        #          type: ClusterIP
        #          port: 8123
        #        ingress:
        #          ingressClassName: internal
        #          enabled: true
        #          hosts:
        #          - name: &host "mc.${SECRET_DOMAIN}"
        #            path: /
        #          tls:
        #          - secretName: *host
        #            hosts:
        #            - *host

        # Open port 19565 for minecraft-prometheus-exporter
        - name: metrics
          containerPort: 19565
          protocol: TCP
          service:
            enabled: true
            embedded: false
            type: ClusterIP
            port: 19565
          ingress:
            enabled: false

    persistence:
      dataDir:
        enabled: true
        existingClaim: ftb-2-data
    extraEnv:
      # recommended rolling logs for saving disk
      ENABLE_ROLLING_LOGS: true
      ENABLE_WHITELIST: true
      ENFORCE_WHITELIST: true
      FORCE_WORLD_COPY: false
#      DEBUG: true
#      DEBUG_EXEC: true
#      DEBUG_MEMORY: true
