---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openclaw-cortana
  namespace: ai
spec:
  dataFrom:
    - extract:
        key: home-assistant
    - extract:
        key: openclaw-cortana
    - extract:
        key: talos-homelab-kubeconfig
    - extract:
        key: otel-collector
  refreshInterval: "12h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    creationPolicy: Owner
    name: openclaw-cortana-secret
    template:
      data:
        DISCORD_BOT_TOKEN: "{{ .DISCORD_CORTANA_BOT_TOKEN }}"
        DISCORD_SERVER_ID: "{{ .DISCORD_SERVER_ID }}"
        DISCORD_CHANNEL_ID: "{{ .DISCORD_CORTANA_BOT_CHANNEL }}"
        DISCORD_TEST_VOICE_CHANNEL_ID: "{{ .DISCORD_TEST_VOICE_CHANNEL_ID }}"
        MY_DISCORD_USERID: "{{ .MY_DISCORD_USERID }}"
        GEMINI_API_KEY: "{{ .OPENCLAW_GEMINI_API_KEY }}"
        GH_TOKEN: "{{ .OPENCLAW_BACKUP_GH_PAT }}"
        GITHUB_TOKEN: "{{ .OPENCLAW_BACKUP_GH_PAT }}"
        # Github Fine Grained PAT Tokens
        BACKUP_TOKEN: "{{ .OPENCLAW_BACKUP_GH_PAT }}"
        BACKUP_REPO: "{{ .OPENCLAW_BACKUP_GH_REPO }}"
        # Github PAT for access to Obsidian vault repo https://github.com/dstewen/Obsidian_Vault_Openclaw
        OPENCLAW_OBSIDIANVAULT_GH_PAT: "{{ .OPENCLAW_OBSIDIANVAULT_GH_PAT }}"
        TALOS_CONFIG: "{{ .KUBECONFIG }}"
        GOOGLE_AI_API_KEY: "{{ .OPENCLAW_GEMINI_API_KEY }}"
        GROQ_API_KEY: "{{ .GROQ_API_KEY }}"
        # Mistral API Key - free tier
        MISTRAL_API_KEY: "{{ .MISTRAL_API_KEY }}"
        # Elevenlabs API key
        ELEVENLABS_API_KEY: "{{ .ELEVENLABS_API_KEY }}"
        ELEVENLABS_VOICE_ID: "{{ .ELEVENLABS_VOICE_ID }}"
        # Home-Assistant
        HA_URL: "{{ .HA_URL }}"
        # Home-Assistant Talos token
        HA_TOKEN: "{{ .HA_OPENCLAW_TOKEN }}"
        # Wiki.js API Key
        WIKI_KEY: "{{ .WIKI_KEY }}"
        # Otel Collector Bearer Token
        OTEL_BEARER_TOKEN: "{{ .OTEL_BEARER_TOKEN }}"
      engineVersion: v2
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openclaw-cortana-s3-backup-credentials
  namespace: ai
spec:
  dataFrom:
    - extract:
        key: openclaw-cortana
  refreshInterval: "12h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    creationPolicy: Owner
    name: s3-backup-credentials
    template:
      data:
        # Garage S3 backup settings
        S3_ENDPOINT: "{{ .BACKBLAZE_S3_ENDPOINT }}"
        S3_BUCKET: "{{ .GARAGE_S3_BUCKET }}"
        S3_ACCESS_KEY_ID: "{{ .BACKBLAZE_CORTANA_BACKUP_KEY }}"
        S3_SECRET_ACCESS_KEY: "{{ .BACKBLAZE_CORTANA_BACKUP_SECRET }}"
        # S3_REGION: garage
      engineVersion: v2
