---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app minio
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: minio
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      minio:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: quay.io/minio/aistor/minio
              tag: RELEASE.2024-09-19T12-57-43Z@sha256:acc4662cc1390617fec94230a15f95d46c5cf9812aecf112907840fb4d7ea01c
            env:
              MINIO_API_CORS_ALLOW_ORIGIN: https://minio.davidstewen.com,https://s3.davidstewen.com
              MINIO_BROWSER_REDIRECT_URL: https://minio.davidstewen.com
              MINIO_PROMETHEUS_JOB_ID: minio
              MINIO_PROMETHEUS_URL: https://prometheus.davidstewen.com
              MINIO_PROMETHEUS_AUTH_TYPE: public
              MINIO_SERVER_URL: https://s3.davidstewen.com
              MINIO_UPDATE: "off"
            envFrom:
              - secretRef:
                  name: minio-secret
              - secretRef:
                  name: cluster-secrets
            args:
              - server
              - /data
              - --console-address
              - :9001
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /minio/health/live
                    port: 9000
                  initialDelaySeconds: 30
                  periodSeconds: 30
                  timeoutSeconds: 10
                  failureThreshold: 6
              readiness: *probes
              startup:
                enabled: false
            resources:
              requests:
                memory: 100Mi
                cpu: 100m
              limits:
                memory: 2Gi
    defaultPodOptions:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - arm64
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 50
              preference:
                matchExpressions:
                  - key: node-role.kubernetes.io/worker
                    operator: In
                    values:
                      - worker
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups: [100]
    #        seccompProfile: { type: RuntimeDefault }
    service:
      app:
        controller: minio
        ports:
          http:
            primary: true
            port: &consolePort 9001
          s3:
            port: &apiPort 9000
    serviceMonitor:
      app:
        serviceName: minio
        endpoints:
          - port: s3
            scheme: http
            path: /minio/v2/metrics/cluster
            interval: 1m
            scrapeTimeout: 10s

    route:
      app:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Storage
          gethomepage.dev/name: Minio
          gethomepage.dev/icon: sh-minio
          gethomepage.dev/description: "Minio on Talos"
          gethomepage.dev/pod-selector: app.kubernetes.io/name=minio
        hostnames: ["minio.${SECRET_DOMAIN}"]
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *consolePort
      s3:
        hostnames: ["s3.${SECRET_DOMAIN}"]
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *apiPort

    persistence:
      data:
        enabled: true
        type: nfs
        server: 192.168.10.15
        path: /volume2/piNFS01/flux-cluster/minio/
        globalMounts:
          - path: /data
