---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/litellm.home-operations.com/litellmvirtualkey_v1alpha1.json
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMVirtualKey
metadata:
  name: openclaw-test
spec:
  proxyRef: litellm
  keyAlias: Openclaw-Test
  secretName: litellm-key-openclaw-test
  secretKey: api-key
#---
#apiVersion: external-secrets.io/v1alpha1
#kind: PushSecret
#metadata:
#  name: openclaw-test
#spec:
#  secretStoreRefs:
#  - name: onepassword-connect
#    kind: ClusterSecretStore
#  selector:
#    secret:
#      name: litellm-key-openclaw-test
#  data:
#  - match:
#      secretKey: api-key
#      remoteRef:
#        remoteKey: litellm
#        property: LITELLM_OPENCLAW_TEST_API_KEY
