---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/nfd.k8s-sigs.io/nodefeaturerule_v1alpha1.json
apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: google-coral-device
spec:
  rules:
    - # Google Coral M2 Accelerator
      name: google.coral
      labels:
        google.feature.node.kubernetes.io/coral: "true"
      matchFeatures:
        - feature: pci.device
          matchExpressions:
            class: { op: In, value: ["0880"] }
            vendor: { op: In, value: ["1ac1"] }
