apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:cigi1I42Ioi2YqnOadqisj2WhVUe8cMrTL+RAThqYcJUY+GKzjg+hw==,iv:Bv2jXche48ZdrFjovadnUQe0kCN0Z5sh8VLz7/mKqis=,tag:znCyjvHwNy+yhWLFBJaWaQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFFDNHR3TGpz
        dWYzdnNYNndzRVJrRnBJNEp2ODZOc0ZabGxadm5JNEdVM3V6WDN1L2hjWWZtc25i
        ZGFJYnk5cHZ2d0RHeGtmZFlFdjNOV3FOdllhYmFnT3VUTGhIZU5Hbmc4WHJKU1lY
        ajBJZjBxdkhFVVdNUUMxSW51R0RwUnVidGxPV243NGIydjJiT3ZJNTN2aEdtUFZt
        d0RPYmFlUUJ3czhxcENqYWdkS21SN1gxNHZQcm9TNW8xUWFjM0VYa2o0TEN2TDJR
        c3Ivai9DSGhCc1Uvb1lrQUptMCtIdCs5QlpneFdROVNuYXpxRE0wODVwbzZpTGJj
        K1RJejUrbXBpRzloZXpjOHlNNDdtM0VLZWxOS0p1MTI1NHJYcnF6Z1dmZGhVZCtC
        V0VONDFiQ1JWNFpRaWZSQlh3NGdQQjMraW1OUTdvdVhEYzJ4Qmlud3AwWU1Ic3gv
        RzU1b2ZWY1EzTVJ1aWxIOXF3Q29Md04rejZXM1FIaitTejBQdm9uQ0NzSkVTWUJU
        Ym41Mk1hN3UzYlRJWlluYWoraldWTEthTUxReG5Xdk4zM3ZQRUIzZFdzZzJ5TWpR
        NUtheWluYlJZWE1TTkVKZ09KOXFkano0cHZ0eDBrUkhETEkvSXRPdlJGdEFYeDVW
        Lzh3aUhXMHMyV0lBMnY1M2Iyc241R0hsOWhSR1JESzdxLzlhV1U2dzZhRWFPM0lN
        Y0NNTWorSFJ5MzIvc1JnaTQxSG1CUTFtZ2U5M2ZoREJOeFBLajJ2SzBaRXlRdEZU
        QWMyeHVDNnMyWUhJMG9wL0ZydXlhRkpJc2xlMmJ3ejl4NEFwUmgxeC9nSU1oS055
        UzU2U05HSHFEb0VmaklYWjFXM3RRVm1ScVQyVk93RGdpUVJzYmZoYTN2TVZ0QTFm
        bUphQ0I2T2VjNm5nWHJBUW1La0d6SHQyTURoQ1QwRUNTcHI3VkU4c3NBMVRLaWtB
        WldBK1dxTjYxL2x6V25NNHl0UHB1M29EVDZ3TEFGSzVnaHVrVjE2eHE1UVFXd2xH
        ZnF3MWsvUHhNL1B4dmVMc0FyZlpnS2JVZngvYUQwVE5ETHZLUnAwQlMyaG5NWTJC
        ZlpwMERXTFJPSkwyM0M4U0gzWjBxZmF4U2hnclpBOWtWaVBxS29YcEJ2Q0FZNjQr
        b2hsZDhtNGZUa09uSkpMNG40eXNKQkJFdzdVTTVzY3Nzd0lmYmY4V0MyVGV2dmVt
        Z0VqNG12UThmaHVZUDV5VGFITmdubHNQd1dQeEIvK2htSHBrSXBDYjZzVHE2dGVZ
        VFBBeDRmV3BoRWZCUmU5TDJodURSNVMyeUNzZ3AxZ2ovK2NmNEJjMU1iVzU5MGMy
        dG9qd0Q3ZVRQUTM2YnJjTjJNbHY1anNIRno0V0pUaWU4TmZnWXFpSHh0OSt5YTRM
        NStWOUpoS0RjamxOa1JEeHVQNnFXZ2V5aGhrTjBTbnYvU3hNNjVwa0pYNXE5dUhj
        Q2tpc2tMZG9NQkkxOVlsTy9Qc1BuLzZBVklFWHc3K01ZbHZkeHB6d3l6cWpUZWYv
        YjVBdkNWRHhDQklzeHFlODBFYmQ3c09WdGNkakZrQjljK2xrcVlxNU9MVmIxVjhm
        RHE4bDVrTGJEbGNzT3oyZFRxY3NIVGRUMzVYcFF6YjdxNFpBQlFvM2t2c0FBc3Ni
        cXJMcExmNDA2aDR1a09lUUdQU2psTFJ1NjFadjJueHVhY2tPSnExQ3FCY3lIK2Fp
        bkEyalM4di8wMmpKeXJTR1hLMnNCODNwdDNydGtLL2N2Q25hU3NrelBsY2hSaTU2
        QnZyM0xxMmJxbHMyaVN0WE5aWVRJUHlPdjNlZTY3ekJRTGhtTmtrQWlmTDFORlQx
        cFM1NXpDNm9XaHVFa0JkZVZWcDczQm1DZHgweFZJZ2JIM1lLdXlSczJFbXJrbUhz
        RXgvdWxBWWpBdHRZQjhVOTlxVG9paE8vMDQzZlVkbEo3RmJFeUhrUExodmFSdwpo
        dHlGM3lGWGR5dEFkWU5zYkRWKysyQWp6MjdveC9XK01jRUE0Zi9pQVVJCi0tLSBv
        Qkphbjh6MUFtTDFRRWFKcW9JU0w3MFhhb0V4eHhZQTNaOE5qaURyallRCs4Y69lw
        wp/Kt/M8tzC2Ihrytz+CO6MY5FxjjCUG4dYFhfwbnquMT629WYgT12QBEVHdqGrk
        eXVTE6IDGkGgLyc=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq13kgy63cgnvwlckua679c7jrant6jc932vc78zaejqatgh9ee2ys6yal5hsm0jdk9cl9vvyak9up8hf92sjwuscaagp6tvj5f20tn09k20nspt2ray3m7pnxrwvfc5j2md7esds275dpv2zeryjjh6w5mfzdppf9vjzu5p9v8ty7r338r8cndw4h4rpehyysjk828fqk9ga2543rc69jwenxywmnp76tmwcasz0s45wck7y5nyc52smhe3r84rv7a4zl5zg40gv4k5er5vw26c8cd73prkcnskpgpgqltqe75jf3ecfdpwp9sul38g8dsf6geskzrs3awtf36agxxz6aed4r3znqc0sdnfyuhezaflkeqjc69f3nfqcnrqfj04t4x7esq3w6t54rwp297m4zrpadqn3e3ch4rdwacc6j6dxdewzy8dk9qhrxdxgz07spcx44nwq45y72vsrje3q2wsmxnwxmnu8upq3nh34st2a3vqdkzafuz6sq49urmpewxnfuznyjpekp0yduzar3ssucegcapdjjqnrz7ckdv73c5ktksxt60txznpvap8jf2qg76zjyvn9lyd2sh67zvfvmzljv9e9pf98mh8s4xkg28m6r59hv2k59gktmynf47y99eg34rgx8xpeul4jwpkz7mvqe92cz25llpzy7s2enatnyv0323q6xz9fs3c47d2a0gc44w6m90fjgtl4uu8ywcv0s4m9gmx23e2s3kl8mfz5zfx9na39l9l3zvxuvme5pyvl7svnq7z89mx2fa8qzjv8wenhdyzg98hpv6x3my74s5u8p4ng3wsf8f56kzkvd8nvayz4zsqucrc8x2mzs5fhpjyjd29vd5ftwejz44rt9vqe5ez2ext9tqwuu2399ck52mch9q9lq8fyp9ppu0y04y09fq8gmu283etvskhcc9kz0zfv95zupt2s7x7dgn53hr4vgq3f2ekadkw8mp8e3pnhtfcrpjd93euer7uxqh3mjur78pzdwrrvxy0xr2andmnj8nwsa0qjkxeq99dqpdaxqe2jc99h6s5n0h7dcnmfm9uuaxpm84fq0tzjqmk9newrpsvuwry0jjvplv02zva20vh2s9jjrxxq3mpu8ywj8ufzalmuv4q0uphym4fp8eg9ukgk56mep52tdt4u7yz0sqy3delgk0pvd4gvfea3h5e4msv7uvyx6v07qelm2kpj38dj9rca0lpqa0wfzp05fvruh9fmgphxewj8xgx3rgmsrf2a4yn4mcs6ddkp2yc7svu7w80cexezg82qx5tdcr9wmxdpcxnsn82y8fkk95fphp5zvcyffnhm6pr2d04ww4vq9zm9j32gy898ce0ga5psj0y63u2gs62ekt5tp8s4h2yz04nvaqluc2ppaf5yaygx9lxketh3v7rwp397g30nmywg5sd0gd6cprpydf3x9pte3mx4h5ptuvtzyl82df8qvcfsdrvx8n8nafasf3h5rjjnjjp69eyw8qp30ydycj3d2lsgfky2vr873yvjmmuws95v9a43f4qd28w2p6pgaua3kf86alkmsyllljj7hnxezrz6fqapggrzg4vhazr82xvcp0k4erz6dzqrn95n6ueryap0vwxtq2e2qmmfev2w6x8630r3gqlj22ypgllm7fw5e9ql0l09l0g39v8un2gw5yvzvmqjtjcsxdp2le3ztkswgg0hvyeuqvf930xlxe9dwdtzcf0hygs9mcsdpwgu493vtljkzssqnkrh5evm2ycv8f0dz9z84cm0mnzjzgw9z74jznsdr7y77285d3svrgwg3d7essz4f5zhh2q928qmzfzj0m0w65kyda5hm6t5hrgywd3ajhfcm22qleneuxxt7u52u5asg8e9lx2lme8lm93f5cdw4gvcey4fql7hztg5cmq3l0
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-07T03:14:23Z"
  mac: ENC[AES256_GCM,data:su/gBL811YXDOMfxmWM97XLgsTOvKEgNahZZ/utZ1VirGZX5xhXf2t7BoRxXvEFusIISkwgQP8fqbYoHRJNF80DGwxHhzM5o+c0h5/Ops0Qcx2I++gXb9jdFP7eoBru3AcRsyn4fxkMn1H9YAGlWVRPy32nlxxpvxpftPYJ+A9s=,iv:gslD47rI9osskIDE+rSRZYCCzLdmWpNUNO9ZHT3xno0=,tag:0lyQodAhBKKokF2bjco6hw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
