apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:eCjBI9V+J56RXcvgOpVNcujhoMQ4UuaI+yg4Vpxo19WLNHQkviJaLA==,iv:rl93yxYZoensA1NyNrFnvAs2nGAh3KQ0ZgE0WMguSKo=,tag:HiAC9jL2URkqXfHFn5VZ6w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFIyejk2aUtj
        VElyWENsekd3eFhNRGdRbFdTVzJ0cUZPMVQ0L09zNWlBWCt6S3pGaUFaTUM2c1M3
        ditEaitpMnJ3VFd6dHZkM0VaamIyNTRjTG1UVzFWbWN0YVRBKys3ZHNMOTlEVnZy
        KzgzQlEvZmdCMnNnYVYySTlOS2t1QnNieGY4UWthRUU2RWsyTzg5bHpGaDBOTkxw
        Q2h3U3Vub1RWV1VwYi9wdmlPOUFOM2tQMkFxYlNHZFcvSEplZ1dpYy82OVhGRU9M
        ZFBSTU9FYk1zN2FaQVpLMnVOL0xNQTdCcFRGV0tLMjRsb0U2QkMzR2ZCVVZMbTBq
        VVVsZjZrME5qMGxGb1d6Q2tya0dmaW1EVVlHd21Bb2RERXZMb09FemU0TFpSeFBh
        WlBjTnJTOEt5NjZYemNabm01UjJ5cVNlUkpPbkI4WktRQktTYm04NE1YVlVtU2E1
        ekRYWUN5bzFvR2RhcEMrZFQ1RU1vanFadWY5ejdBK3EzMWlnd0tscUVTelpYb1hq
        ckVveFJUd05MZHMvcnY2RHJNUFpHODFzWitXTGxyTmhpQlF3QURlL2hqSmZzcSts
        Z00wQjJCZFFqbSsva2dWVzNPSlhrZFJ2eTlLT3lYK0tDbTI0ZVA5Y2J2QjRCelF0
        MVlSYkhmR2tSRVpCa3c4TVdmR2JoM1Q2amxSM0NyT1I1K2JSUFdwM0Qrbi9FbEVv
        YUQwcU9EYWpmbmF6K29VUzAvN3ZGVjc1Um1GejR0TS9SbGV5d29nNE1ENkNPZlJI
        b0JkaGJ2ck5mbmtESFZHekllKzBNNXlOV0NmT0t4di9pNTdLNmhPM3JJdHNKNzBS
        bkhvYlA4Z1FETFBRNDFSWjI3ZlF4M3kyRlNCeWwrcDJnM1Z0Qmd1YldQZUpNZFRD
        WTE1Q3NBTmZYaDVWR2M4cjZYc0prQ3dCS1NNYVM4L2o2aVk2T3FIdlJYMWJzZ3BV
        cHR5dGJTK1c5Nm9UQ2dhOTRpYXNVS0FmV0c3Yys0TWNVcC9va2s4VzBnL09MZmRn
        MDg4dE56WkszdUlQZXluQkxoYk1PLzhyNXBpVWlQTEI5NU9qSDlvMDMwNHp6OEds
        ZHd3WGJSYkRkb3I0U3YyTEw3UkpEUzhxbkNPTmRHM1pZNm9YMEhFZU5jcUR6QWpx
        RGtQcXliWmZ2MU04Y2lualBPYjZIQVpuTU5CbGUzdFhpS2UzZG12bTd4Z1hKTWpq
        czg2UXk5enhpV0ZRUXFrazBJZGh1VDZnQVVxZVM0MnRSS0JEVlRNWE1nTElrdDVw
        VDlGYWMrdlBLR3RYNmdua3VHaW5nd0hHK29TVU4yVmpyYUJDZUJISHVuL1ZOK0tM
        bld2cHdsaFJScWUySnJjeXpmSUZCdHY4T0hqWW93SlFSU0NlVmFQczlTZXBJU0lE
        RWw4RStEczVlZkkvcGhheWdEVENGNkgySjRWekhGMUU0WVJoWkZUeTNHcHNzZVhh
        VlZYbmxkNmp6UCtmYVEyM09sa0xWOTdUS1lRZ2NmMFYxM0tLQVRkdmtsNzhvLy8y
        a3VOUUJ2Z3dIeDBHNjFKR0d3Z1I3ZDZNaGdkYjZoaFJva05mZmtzWjBCREh1am1x
        TVBOZTk0NE4wMkplU0VneE0reUMyR0lSbjYvMnVsWndXR0o2Mm1YeWpaNHRaVmJW
        RkltYXcyZW1kSkNNS28rcy9EUE90azZSV2NIeUdZU3d5UDhkZ0gySWhmM0ZlUlVJ
        OEJCd09kMDR2bTRxRnJpelZ6NUp6bjlnV0w5aXRycW11WFI1Z3VDMjRTZ1dUekdG
        aHlpci9WTzMzZEFsZDRKcmpRSmFjYTJ0Q3JNZXhtbklScWppVmZScFYrTndJeHJZ
        djBmQ0YvS1dSb0VoSERVNXRlbXRKekRLNlZyaHlkWWZKaXIySVo2VlcwWlpkSVBl
        UjJ2ZXFTbGc1RWsvUXZoSGFOUG5sRlFFN0VhbTZ2RXV1aFovUW9VUHFCa3ZGUQpG
        RGxXSlpJdkI2dGw5T1NkYlcvMUw3UHZoamJOTHNlQy9SMW5OZG1lQkp3Ci0tLSBz
        ZWk1dEZoaEZnSjVHYnZNbm9ScXZ5ZW52STBmNE5pSEllZHFqMzVGY0NzCm8I5zpe
        UXPK7EY+ZRJ7AF0sMqfAAG7b4aTzeJZ8Vlo7Uqf0BtFgapFKaEnGgDiBb7HAd3jB
        e8r81LWD7unLuXM=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq13kgy63cgnvwlckua679c7jrant6jc932vc78zaejqatgh9ee2ys6yal5hsm0jdk9cl9vvyak9up8hf92sjwuscaagp6tvj5f20tn09k20nspt2ray3m7pnxrwvfc5j2md7esds275dpv2zeryjjh6w5mfzdppf9vjzu5p9v8ty7r338r8cndw4h4rpehyysjk828fqk9ga2543rc69jwenxywmnp76tmwcasz0s45wck7y5nyc52smhe3r84rv7a4zl5zg40gv4k5er5vw26c8cd73prkcnskpgpgqltqe75jf3ecfdpwp9sul38g8dsf6geskzrs3awtf36agxxz6aed4r3znqc0sdnfyuhezaflkeqjc69f3nfqcnrqfj04t4x7esq3w6t54rwp297m4zrpadqn3e3ch4rdwacc6j6dxdewzy8dk9qhrxdxgz07spcx44nwq45y72vsrje3q2wsmxnwxmnu8upq3nh34st2a3vqdkzafuz6sq49urmpewxnfuznyjpekp0yduzar3ssucegcapdjjqnrz7ckdv73c5ktksxt60txznpvap8jf2qg76zjyvn9lyd2sh67zvfvmzljv9e9pf98mh8s4xkg28m6r59hv2k59gktmynf47y99eg34rgx8xpeul4jwpkz7mvqe92cz25llpzy7s2enatnyv0323q6xz9fs3c47d2a0gc44w6m90fjgtl4uu8ywcv0s4m9gmx23e2s3kl8mfz5zfx9na39l9l3zvxuvme5pyvl7svnq7z89mx2fa8qzjv8wenhdyzg98hpv6x3my74s5u8p4ng3wsf8f56kzkvd8nvayz4zsqucrc8x2mzs5fhpjyjd29vd5ftwejz44rt9vqe5ez2ext9tqwuu2399ck52mch9q9lq8fyp9ppu0y04y09fq8gmu283etvskhcc9kz0zfv95zupt2s7x7dgn53hr4vgq3f2ekadkw8mp8e3pnhtfcrpjd93euer7uxqh3mjur78pzdwrrvxy0xr2andmnj8nwsa0qjkxeq99dqpdaxqe2jc99h6s5n0h7dcnmfm9uuaxpm84fq0tzjqmk9newrpsvuwry0jjvplv02zva20vh2s9jjrxxq3mpu8ywj8ufzalmuv4q0uphym4fp8eg9ukgk56mep52tdt4u7yz0sqy3delgk0pvd4gvfea3h5e4msv7uvyx6v07qelm2kpj38dj9rca0lpqa0wfzp05fvruh9fmgphxewj8xgx3rgmsrf2a4yn4mcs6ddkp2yc7svu7w80cexezg82qx5tdcr9wmxdpcxnsn82y8fkk95fphp5zvcyffnhm6pr2d04ww4vq9zm9j32gy898ce0ga5psj0y63u2gs62ekt5tp8s4h2yz04nvaqluc2ppaf5yaygx9lxketh3v7rwp397g30nmywg5sd0gd6cprpydf3x9pte3mx4h5ptuvtzyl82df8qvcfsdrvx8n8nafasf3h5rjjnjjp69eyw8qp30ydycj3d2lsgfky2vr873yvjmmuws95v9a43f4qd28w2p6pgaua3kf86alkmsyllljj7hnxezrz6fqapggrzg4vhazr82xvcp0k4erz6dzqrn95n6ueryap0vwxtq2e2qmmfev2w6x8630r3gqlj22ypgllm7fw5e9ql0l09l0g39v8un2gw5yvzvmqjtjcsxdp2le3ztkswgg0hvyeuqvf930xlxe9dwdtzcf0hygs9mcsdpwgu493vtljkzssqnkrh5evm2ycv8f0dz9z84cm0mnzjzgw9z74jznsdr7y77285d3svrgwg3d7essz4f5zhh2q928qmzfzj0m0w65kyda5hm6t5hrgywd3ajhfcm22qleneuxxt7u52u5asg8e9lx2lme8lm93f5cdw4gvcey4fql7hztg5cmq3l0
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-06T11:13:00Z"
  mac: ENC[AES256_GCM,data:4ryhwSB3EldvCozg2JbjinmtEpVbKyxrG6rqWg0q/TP8ZGqhs/f4z7T/KMY2MiXFs4NNNTONQ+ncYYEB2VAIHNtXoCWnNoY3xxdcF3coi3wXtZw+b2qc9rpKxMvrPZuZKoCaHkrtMm8RFyhTBhZPvxX/GJNHqFThSyqiirNzU64=,iv:MJDUWzi7HuLEHwehXcbnjXslW2hwJHjaAMwfgZmOEMw=,tag:GkfT/IPq9ypOt3KVP2yspQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
