apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:5yLYmDPX3MMXmZyey7pMKWhFFxYlX0saUNajsEmdqygbJ0ceO1DZPg==,iv:Ngz/PL8no9npiwas/54b2Njg6FjSbEoc+cCZynDotTg=,tag:4scWDpEXNltfcsmiZ5TSjw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHpRQkg3QlNl
        S2JPaUdOR2dZbXRCYnV0MnRGN2VDbERzcGtaTDhFalUxSTBPeHozOFlpOVNjRE5Z
        T3B0TlFIMk9ZeHRVTjJYcWNhVFpvN0hhSW1xanJFd1hCa2NiL2F2NzArSm1JZWhx
        RndqL0tiQlRZS2RyempTOCt2MU1raXI0TmcvZ1dZemk5akREcmMyMG84ZVZ5YmJG
        MFFPQ2NnWk1CSDdsSnk4K3AyY2hieFgvOTNPNDBYNnJOa3V1TkR2dmdlWDlSYU4x
        RjB5TW9VVEIrblZGSVlVeDBESUpnTGFWdnRPQVRNZXdyRE9YbVg1QXJnR040UDJU
        ODIwWllsTHdaeXE4dU9MUG5aelNrOW1mNmJ6WDhGYkY2dkNpWDZ0NXFlQVIxaEU3
        UjBvNjFXYUdodG5qWjAvbWszaUtWVE1JTUFOUVR1enBNbEIwSHVwZExWWnluR2l0
        bHA2bEpRcGhaT2pIbVhxLzk4VlNqM0xRL0tpeVRUR0lmSWZEdXRlVHJnbzBzN2dt
        SFR3NDJHRWZiQVUydmo3N1VQKzE0Y0FvclhpaEUwa0tqU1M0Q3NqcmFyY3R5UDhn
        ZEVvTm1adnZzdmpRU1lZaUpGWnhCNnNKMmt0LzdrVEkyejNvYktOR0xDcE5XRFd4
        T2RhaitHUm5CeTdJQ0xzSllMSUtxVFkrWWYxRUp4NXhrNllhQjJGeTZzL2xjbkVh
        bTkrTGpISFlyU1RkbGRmaVE1dmMxUGdzK2pKeWM0REJiNXk4SXdxbUJiNGNTdlZy
        SFZNTG05Qk5jdnhZUHRabE10ZHEyL05tTGdMNzBVUXZxdno3ZzdZa3FJSEI1Q29y
        QjArZmdUWGErcS9LWDVVSHNyS3NSdnpTakhHWUphNGhaQ2lFcDJYanozaldyaE5Z
        RHBhTmxBa2FHMUNLYzVvZklYTFhCaUNaMEZkS1REMnNHbG5UdnlGdG9NdWpLTWVX
        T0haL0tmSExzR0tKUjlockljQUZOMjI3bjJtWWtxdzRqaG5lWmlJY3BENjVWTHRV
        WFd4c0Jjd3Zob0kyYjNoaExxZFJUemlldnRVOUhEUkRyM01kaEVia0JUNVVXTS82
        ZWFQM21tVlRWL3c3cWVKOWFEb0xYakVOSWlGdXYrYWdBVmZFdTJRd0g5bTExNFUv
        MkV5YVVRSlZFdy9FemJMUU8rL1hjbzFsNXBHam5SU0ovQ2c1LzdxRy85R0FMY09m
        Nmh3YkZVb016NUxaYUtWYmg3NnhNWnlCN2pCUHhvN1VHZnJoRy96aC9QR1VmMTVz
        NzJ4bktpM2RFTVVQVzZKcGlVSEI2RlpDcnFwRENqMlpRM1BteEc1ZnBtK0RWRlBB
        R0FpSWJtaExwc0oxYU9wOWd1MkphclRudkIvNXJSL1g0TWFXa1ZXQkl5QlRSTmFT
        SXl3NkRvQ2JIUXo1NmYvaEJQdDhScTdzcUJaak5BQnFISkRmVDA4NysxeEdzQzRI
        YkR4d2tyeW8xNHJUN3ZrQXptaTB4OSt2bjZIOFprenpkVVluMjdwLzlqdHhiMXQ2
        R25ncnpNa3BvMk5ja3IwOGRRblhGYXpzOURTbHVkb0FaY2hUYzI0Wlh6OFFkUGhY
        MC9NQUFETmVlNEVSajkzZDdsOVE0SFVJUlhFSkFCQ1AvS3JZcWZDM085OVVqUjZ3
        bGd0dm5LeFl0SEtwUTB5SWJmVEI2VmZaWVJZR0dvZHBqT3Q2V0I4YUNNd0tsWi83
        bUJSMHhlcHlRMlFVZ2k5RDExTDlsS3pXV0xqaTZ1ZUw5ZUtIaHRRVXpzQzEvQ3Aw
        RTZBWGExZlF5VjJTM0t1OFJUcndTOW9aU2xsUy9JNGFnR0IwcWlHN09PRlkrd0JY
        WVA1UGdEQi9ZNmxyR1hWUXJkazV3YVFCSWp4UjFoenpCWkxmWFB1VWVJbEdIL25j
        dXJuNTVUb1BDOEhUSTJVTTJ2QUpVZjF6amlabkZrYmNzSHFFOTFPNTZoQUhPQQpT
        a1BWbGRlK1o2TStqQWJ6VWV5MStFQ2daRlNkMUUrVGNtam51UmlkelhBCi0tLSB1
        UGRoZXowS3UveGFKZS93UGRiMUtvaTlDeGVzRnFyMUV3aDRvR0xQMXNNChxplTRo
        15q/4R/3nEewr6J3asYpqyeRGFfhaynPxjHU/7nGD2agrBdUgrw5jpvJIPyvGCwL
        Z1m0o1+tQcmIe5U=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq13kgy63cgnvwlckua679c7jrant6jc932vc78zaejqatgh9ee2ys6yal5hsm0jdk9cl9vvyak9up8hf92sjwuscaagp6tvj5f20tn09k20nspt2ray3m7pnxrwvfc5j2md7esds275dpv2zeryjjh6w5mfzdppf9vjzu5p9v8ty7r338r8cndw4h4rpehyysjk828fqk9ga2543rc69jwenxywmnp76tmwcasz0s45wck7y5nyc52smhe3r84rv7a4zl5zg40gv4k5er5vw26c8cd73prkcnskpgpgqltqe75jf3ecfdpwp9sul38g8dsf6geskzrs3awtf36agxxz6aed4r3znqc0sdnfyuhezaflkeqjc69f3nfqcnrqfj04t4x7esq3w6t54rwp297m4zrpadqn3e3ch4rdwacc6j6dxdewzy8dk9qhrxdxgz07spcx44nwq45y72vsrje3q2wsmxnwxmnu8upq3nh34st2a3vqdkzafuz6sq49urmpewxnfuznyjpekp0yduzar3ssucegcapdjjqnrz7ckdv73c5ktksxt60txznpvap8jf2qg76zjyvn9lyd2sh67zvfvmzljv9e9pf98mh8s4xkg28m6r59hv2k59gktmynf47y99eg34rgx8xpeul4jwpkz7mvqe92cz25llpzy7s2enatnyv0323q6xz9fs3c47d2a0gc44w6m90fjgtl4uu8ywcv0s4m9gmx23e2s3kl8mfz5zfx9na39l9l3zvxuvme5pyvl7svnq7z89mx2fa8qzjv8wenhdyzg98hpv6x3my74s5u8p4ng3wsf8f56kzkvd8nvayz4zsqucrc8x2mzs5fhpjyjd29vd5ftwejz44rt9vqe5ez2ext9tqwuu2399ck52mch9q9lq8fyp9ppu0y04y09fq8gmu283etvskhcc9kz0zfv95zupt2s7x7dgn53hr4vgq3f2ekadkw8mp8e3pnhtfcrpjd93euer7uxqh3mjur78pzdwrrvxy0xr2andmnj8nwsa0qjkxeq99dqpdaxqe2jc99h6s5n0h7dcnmfm9uuaxpm84fq0tzjqmk9newrpsvuwry0jjvplv02zva20vh2s9jjrxxq3mpu8ywj8ufzalmuv4q0uphym4fp8eg9ukgk56mep52tdt4u7yz0sqy3delgk0pvd4gvfea3h5e4msv7uvyx6v07qelm2kpj38dj9rca0lpqa0wfzp05fvruh9fmgphxewj8xgx3rgmsrf2a4yn4mcs6ddkp2yc7svu7w80cexezg82qx5tdcr9wmxdpcxnsn82y8fkk95fphp5zvcyffnhm6pr2d04ww4vq9zm9j32gy898ce0ga5psj0y63u2gs62ekt5tp8s4h2yz04nvaqluc2ppaf5yaygx9lxketh3v7rwp397g30nmywg5sd0gd6cprpydf3x9pte3mx4h5ptuvtzyl82df8qvcfsdrvx8n8nafasf3h5rjjnjjp69eyw8qp30ydycj3d2lsgfky2vr873yvjmmuws95v9a43f4qd28w2p6pgaua3kf86alkmsyllljj7hnxezrz6fqapggrzg4vhazr82xvcp0k4erz6dzqrn95n6ueryap0vwxtq2e2qmmfev2w6x8630r3gqlj22ypgllm7fw5e9ql0l09l0g39v8un2gw5yvzvmqjtjcsxdp2le3ztkswgg0hvyeuqvf930xlxe9dwdtzcf0hygs9mcsdpwgu493vtljkzssqnkrh5evm2ycv8f0dz9z84cm0mnzjzgw9z74jznsdr7y77285d3svrgwg3d7essz4f5zhh2q928qmzfzj0m0w65kyda5hm6t5hrgywd3ajhfcm22qleneuxxt7u52u5asg8e9lx2lme8lm93f5cdw4gvcey4fql7hztg5cmq3l0
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-06T12:26:40Z"
  mac: ENC[AES256_GCM,data:Tc70lUiaDflPlVvwZk5TnnpNhqBxONC47799Zs1aNA7Dci/33O8pcPre87nHYWOG0lU8S1r2PmTP1+B9k/n1DMLy+cv9DolfbnXF0UDsFoVozK55XszCZD2EnejilLPO9G3GBXd26DJ4zEdPcZTWVXSv8NRBXkye64/p4FbL5v0=,iv:lYu4TaLgbQO7UlXCA+RCpGB3+/Bm+0cE1nVPvUxx7i8=,tag:XQ4iSOz19kjeno4gtU1c6A==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
