apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-secret
  namespace: monitoring
stringData:
  admin-password: ENC[AES256_GCM,data:PzdV6BHYuSGc,iv:hK6ekZPu2vOHe9+CgI4ZatQeDd3x7bT9PXxKtxFMY7Y=,tag:NmQGsM9QxnOSXuPZF9lLxQ==,type:str]
  admin-user: ENC[AES256_GCM,data:FC2TIMw=,iv:iKxnRwkRfS7sjNG8yI8TxaMOAHMdiSYdkRWHeL/jjYU=,tag:SY2DpcW7AcuGj81vGSGtdQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGlSNk5TWFR3
        VmIvZHJaVG1uV0tYN1BzSVk5L2tIb1pSVEROMW4xY1RqNldQWGFOUmtPSmdJb3VC
        OGt0UVZTbjdkQkxjd2FUTnJVS1E5dEN4NFBOYzRxbDBSQ3RqVUowdWlwUXF6L1Br
        Wloxck40S1VMVDFQY0pkVGNqT0RBVjRMdGs1emRZWlFjQXRxNG1ISjNoVjF5NGNI
        NFovbnpHcGtHMnBKUUREUm9EdWFSVERrSmt2d0JId3N0di96WWpBd1BhRENybnpM
        Z09LU3NWUlo2OEZId044cUIxQnN1VkoyQjhsTGxMaFlZYktuZ3BXRXV2L1lDZDVo
        WUhFZjRCSFRyTGx5ajlyQjlGV1d0VU5WbmRjbVhpN0dieENKMzBzMTJvQ1JVSXpl
        aWV1K3RhVk1uVUFydlBvQzZSeGdMTU9mVE0wWm9yUkdNdyszaFZ1dWN2eU1ud1ha
        eXpCN09WZ1hRQmptUmpLNEIrenVRbnNkUENaSmpIdXFNcmJKNU9pVXBaOGhYY2Nl
        N2ZqWjlTK2JldS93RThLZFk4eGpDcHZ0L0xKOEc0T0tTWGY2RUFWazdiMkN5bUww
        YnZHZG1rQ0oxQzZjTFUyYm1kekE1N29obEVzRjFZVk5KZHFwc0FtbCs1RGdDS3cv
        cytxUlJFbVEwUC9LK1ppL1I2MFZ5MUJTaWRZUUpGSmF4M09WeHBpM3ptUnhBZ2wr
        YXk1VitkdjhwYlFFVTZQSzNacjJhUHZjN0V5ZlR1aGFqTjVlQkZNbnROTlpOMHJ1
        aGkxZzhaZ3JVREt6VjB0TDU5TjdJdkJuMEllRnlGQ3J1NjNTbFJDenFudWo3Rmlp
        aGZOQnQyelA0M3p3TFRxVzdxenJhMXQ3K1BDQVhHdjVZS2N3L1dObkEwbW9mQlpU
        RXZJbkk1UENpcUtCMHNEMlhqZHFCcWszbUhOU0FEeFJTK2xUcmp6VmR5Tzl6QmVF
        bzY4WW1PWG5aczZybEltMnVSbHE3R2hLdkI2Wm8zZ2ZqckMwVnN0L0FNUWEvVGUx
        VlUySjhFcmUwM254L2RST1JBb0hOSTkxZWpycVJOKytialZ6TnZQMnhKSWs3MW9F
        TW9XYnRhMVkwZ3QwWVBocmdrSUQvVnVGTGpNUURnMTlQVTlyeVk1V1pXY0RxSkFs
        TUdrYXh6OWFDaTJFUWFFUkZuWnlJQ00yZjVQZVNhekNTSHp4Q3U3eXE2YzVJbFJq
        SXVvQkpWMkwrbXlwK1VJR3k2RnVzcXZKTFdQeXdaT2w3VlVtK210WU9pVGlDYmxN
        d0RnNXRDZzNQTS9oc2x1ZXpVNG00L2p6SXdoeDVYdDFvbWJpdFlRZk1FeHptbCts
        L0VsZ2dtaGZQQ0JzSWhjNVdxdHpJTkYwUEMzWG5HRmd5NWd6emd5Y1RkNE10NVpW
        azVaQjhPdVZETnFrQWNPdnpUeWhuN2FHbk5FOGJIbG84QmlJSi9DTmd5YVpGNHg0
        aWpEV3lURzRQeWJkNWNodUxuYyttRHVJK3FrQjNTZGJGakVMd2J2Qi8xN3ZHYWZj
        a1d0cjM4b0RXWGVxZjVKQ1FwcHV2ZUFKZ09vSmpZMmg3OVFrNVhUcmtWNk5vbXJL
        VlNPYjdkS2FwcVQ4K2FTWndCeDl3dnFMNjBnQnZhZzlxYU9OaHRVY204aWNJcmhM
        b0dsQzFXYkJwWmJTTEZseXR6SmNSZHJlVElNWHBZY0JUclZmMlEwUFdTTjVNcnc2
        aHFEVDgwaTRIQUlScGxhOXg5U1N2YmJ2eGtFUjQxcHM0c3h0alhoOHRBbUEzRHBU
        RVhZNUhPdE0wdTBrTnpieFpPWVd5cktFVityQm82MnRrN0JNRnFqOVNVd2F1aDFq
        WEsvSlh6QnJhZEtEdDcwUE93MmJ0UzNkdWpnSVNSZnZCV1JqbTJaMHl4MUpZK0NO
        ZHpQUjBOUGxMS0NHUnYyTEQvRERsMFdpcjd4UWVqQzl0QW81L0hnbGdWdnlJZwp4
        c25XMlNEVzNNUWVwTG56akRPQVpDaStBSEtNSkNxL0l6VGx5aHpBS3pNCi0tLSB3
        cVR2aTFPNElDWkFXWU1oUGRaVDBYb2lBVllEb29GR3U1K3lRRVcrVW4wCo61FFhj
        wybB6hASlJMdk+G+D/CKpu+Jz4ZSHxTHLFGFxamCKeQW0H4SgUg5d4EPyrYtOPch
        +xlnW+3A+7I/xYM=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq13kgy63cgnvwlckua679c7jrant6jc932vc78zaejqatgh9ee2ys6yal5hsm0jdk9cl9vvyak9up8hf92sjwuscaagp6tvj5f20tn09k20nspt2ray3m7pnxrwvfc5j2md7esds275dpv2zeryjjh6w5mfzdppf9vjzu5p9v8ty7r338r8cndw4h4rpehyysjk828fqk9ga2543rc69jwenxywmnp76tmwcasz0s45wck7y5nyc52smhe3r84rv7a4zl5zg40gv4k5er5vw26c8cd73prkcnskpgpgqltqe75jf3ecfdpwp9sul38g8dsf6geskzrs3awtf36agxxz6aed4r3znqc0sdnfyuhezaflkeqjc69f3nfqcnrqfj04t4x7esq3w6t54rwp297m4zrpadqn3e3ch4rdwacc6j6dxdewzy8dk9qhrxdxgz07spcx44nwq45y72vsrje3q2wsmxnwxmnu8upq3nh34st2a3vqdkzafuz6sq49urmpewxnfuznyjpekp0yduzar3ssucegcapdjjqnrz7ckdv73c5ktksxt60txznpvap8jf2qg76zjyvn9lyd2sh67zvfvmzljv9e9pf98mh8s4xkg28m6r59hv2k59gktmynf47y99eg34rgx8xpeul4jwpkz7mvqe92cz25llpzy7s2enatnyv0323q6xz9fs3c47d2a0gc44w6m90fjgtl4uu8ywcv0s4m9gmx23e2s3kl8mfz5zfx9na39l9l3zvxuvme5pyvl7svnq7z89mx2fa8qzjv8wenhdyzg98hpv6x3my74s5u8p4ng3wsf8f56kzkvd8nvayz4zsqucrc8x2mzs5fhpjyjd29vd5ftwejz44rt9vqe5ez2ext9tqwuu2399ck52mch9q9lq8fyp9ppu0y04y09fq8gmu283etvskhcc9kz0zfv95zupt2s7x7dgn53hr4vgq3f2ekadkw8mp8e3pnhtfcrpjd93euer7uxqh3mjur78pzdwrrvxy0xr2andmnj8nwsa0qjkxeq99dqpdaxqe2jc99h6s5n0h7dcnmfm9uuaxpm84fq0tzjqmk9newrpsvuwry0jjvplv02zva20vh2s9jjrxxq3mpu8ywj8ufzalmuv4q0uphym4fp8eg9ukgk56mep52tdt4u7yz0sqy3delgk0pvd4gvfea3h5e4msv7uvyx6v07qelm2kpj38dj9rca0lpqa0wfzp05fvruh9fmgphxewj8xgx3rgmsrf2a4yn4mcs6ddkp2yc7svu7w80cexezg82qx5tdcr9wmxdpcxnsn82y8fkk95fphp5zvcyffnhm6pr2d04ww4vq9zm9j32gy898ce0ga5psj0y63u2gs62ekt5tp8s4h2yz04nvaqluc2ppaf5yaygx9lxketh3v7rwp397g30nmywg5sd0gd6cprpydf3x9pte3mx4h5ptuvtzyl82df8qvcfsdrvx8n8nafasf3h5rjjnjjp69eyw8qp30ydycj3d2lsgfky2vr873yvjmmuws95v9a43f4qd28w2p6pgaua3kf86alkmsyllljj7hnxezrz6fqapggrzg4vhazr82xvcp0k4erz6dzqrn95n6ueryap0vwxtq2e2qmmfev2w6x8630r3gqlj22ypgllm7fw5e9ql0l09l0g39v8un2gw5yvzvmqjtjcsxdp2le3ztkswgg0hvyeuqvf930xlxe9dwdtzcf0hygs9mcsdpwgu493vtljkzssqnkrh5evm2ycv8f0dz9z84cm0mnzjzgw9z74jznsdr7y77285d3svrgwg3d7essz4f5zhh2q928qmzfzj0m0w65kyda5hm6t5hrgywd3ajhfcm22qleneuxxt7u52u5asg8e9lx2lme8lm93f5cdw4gvcey4fql7hztg5cmq3l0
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-07T01:07:27Z"
  mac: ENC[AES256_GCM,data:UglWHUpP87anNGNMfwe3HBu4Q84ROOEgmNJRFf1bZ+ix9qR31ZusfwhQNAAvM9BlK9hYcTLNt6+09UzO1EI0EwI+Im7peSC5VOhME8dVk73GGBq9LbY7z1zHv8nCVKnbdQSL2X17G2c990NEqMXhU/VaOpm+LTnR/c+3sH6Qpxs=,iv:zwVape1nynAlf7VMpRiqlqUbcPMuv966O82BJ3d8G58=,tag:f4lXV+C1N4TRigVT6U8FvA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
