---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app paperless-scan
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: paperless-scan
  values:
    controllers:
      paperless-scan:
        replicas: 1
        #        labels:
        #          nfsMount: "true"
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/philippmundhenk/brotherscannerdocker
              tag: latest@sha256:f9ea728461313fb32a3f3d186a9c44bd2989e5b5da44e78d31ff99d1cbbd3777
            env:
              UID: 1000
              GID: 1000
              TZ: Australia/Victoria
              NAME: Scanner
              MODEL: MFC-L2880DW
              RESOLUTION: 300
              IPADDRESS: 192.168.10.81 # IP Address of your scanner
              HOST_IPADDRESS: &ip 10.200.15.243
              WEBSERVER: true
              DISABLE_GUI_SCANTOEMAIL: true
              DISABLE_GUI_SCANTOIMAGE: true
              DISABLE_GUI_SCANTOOCR: true
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
            resources:
              requests:
                cpu: 10m
                memory: 256Mi
              limits:
                memory: 512Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        forceRename: *app
        primary: true
        ports:
          http:
            port: &httpPort 80
      brother:
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: *ip
        ports:
          scan-udp:
            port: 54925
            protocol: UDP
          scan-tcp:
            port: 54921
            protocol: TCP
          snmp:
            port: 161
            protocol: UDP

    route:
      app:
        hostnames: ["scan.davidstewen.com"]
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: *httpPort

    persistence:
      nas:
        type: nfs
        server: 192.168.10.15
        path: /volume2/piNFS01/flux-cluster/media/paperless/consume
        globalMounts:
          - path: /scans
