apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:ezMUQahfYjNK5gVaqj+5,iv:Fg85zYCb1TWVzz1PTqkI6GFZyWFkE76m/k4tM6ycj1g=,tag:QYE5l5yOHyDXiejQrd2Q8g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IEhvdlpLUFVj
        RlBsM05TbXdqWFVrU1JTMFdoK2dhOUE5YXBqSzhhMm5GVXRQUkljd0kycDBVQ1F1
        ZzUwZTlxTFdSUU1XR3J5T2xVN2NNQXNFMWowOFAraVNBeGZWZmJYK2hQNms4UTM3
        aGZDUFg0WTVnUk4zcEtPcTNOZWdIVDB6cnVlMmtwN0xsZk1SNVB2TG5CWU0yOUdD
        ZW8rbXBSbHRoTzVnQ0d1Yk82dzQzTThPT1VxRjB1SmNTV1RZcFZNU2ltRXk0bk44
        aDNKQ0xjWXA0Y3dZS0Z4TENaTkZLR2pPU2lyNGh0TEp3aXkxQS9IY04raTE5SFVY
        UktXcXZrZWQ0VDNxQmpwYkVLNGFzS2g3Y2JSZ3FYMHRmMXhBNTZkL2tvMitnYk1j
        RVNuemM1QXAzaTJXT1J2WG44RGxWeXZGTGJ1bytSaVROa2lpSVBOUitUcStZMTRW
        cER6bzRSN1Ezd1grS3RZTnU4Nm0rTTVNdGQ1V1F5Qkx3VmpLR05Lc3NJOTJLN1Y1
        K2NsTEFOck8xeEYxK0Ira2pCU2xDTDFwZjE2Q3hmVHloQnZEaHdwUUswWW5zQ25h
        YTBEUFJsZnpCRTRDREVENXMwRk5nZStSV2libmJGd2dra3ZkTmVVcHhlcHVSQmo4
        Mk02ZVV3YkM3N2M3emYxTHhPVHBoN3F1dTgvT0hLTzdDTnF2KzhGWk5ydGJEdkJP
        dHVGOUUwRmt1b1VjSE05NHlpSjVXRDFwRmdpUG5OczRFWDFDK3h3R0s3VnFzaDlu
        emxRS2hHSWdrcDJZUkQ4MUZWR2QwYzJjOGVDOXZBSmVsQWFnWDFkak9aeDBWM292
        TDdJN2tuSWxZdTVDNHRRWUV0R3VkL0VpQ0k3MTRwQ0gybmlUaTZTK0gzN215YlQy
        M3NqeUJYQVZ3Qmt4NE5rNDZiMWliVjVrN0dtR1NPa2xTekdLemZtTGowYnlZMy85
        V3FBRXpvZmFLemQ3L0N0L2JtVE55bDltSU5rODdFcGVLejduZEtWb3ZEVGlqeXo5
        eUVxTWtXRHdSTjJVRHQ1NlVCM2tvRnpONHNlZUc0bHFGWURJcURoWDVBdFZhSFlt
        Y2dodEhoMGw4ekcrRUJKMnhnUnZxRDZLVnAyVEhjM29NMEtZQ1hwZ2hSeGRjb1E4
        WEtaWXBKc01DWG1OaytaYkZuaVdhb3dCYWJhQzRReWkvMDZ0YXVZaHFXZUNZeURQ
        MmlEdm0wRnFqTzNiVktodmsvVXBDY3BLdVBDdzdIc2FwbXFpSUF0bXNWalF1Zjhz
        WHV1eC8rSXJnTE5aQUlBWFphT2gweFZXTG1Lei9Rb0xvc0I5ckJCbmswY2xGbzhJ
        UTVFVXpYbmNqZ3NYeVRNQkdQUG9RdERrY2pZdCtHYVgybC83dVQwcG5rT0dJTzl6
        Qng1NnprMW85YWFXTDFaRThLM1ZaeTBPUERBYXJRbW1rejFpTzZsK283c25ISkQ2
        bXd6TDJveEExc0dHYUZuK1lYZ1BmWm1sR2pPRzNISnQ4bmhyQmZPelJJdTJnQ3pl
        cFkvdDZiS1duN3RnQ2lMQkxqTm9tdTVZZS9pUE9kQlRBdDhWWDF1MW11MzU2MUZa
        WGdyQVduUHlsdFJZYjFwM3lDRnZMeFY4VHpkQnRLVGJHaXFnNEtvREhobzdoTGg1
        WjFWWnRTTWVLUHh0cTRxVFl4K1RCOUF2WlpsWVNySTNyL0Vxak4wcVNpVTVXQWkr
        QXR2RDNCM1ZsNm1xV09CQ2FGYzNIRlBPMVh4YUlXNXNEcFBvcWladzYxeng1bFY1
        SnBYTDFVZFE5RkhmQXZpTnM3RHpJRXdOUmExUXpEbDhFKzZjM21kQkd0YU9iOWFz
        YmE4dllCQnNKUlhuLzlOd3UyNitseDBaYUxkbTBRZEgwUm8wSlczN3BMKzcwRG9E
        RjJ5VnJ5em1XSmllR3pHa3BiSmJ4d1FMME1xbkhVR2w1RWN1NmtienZLcDViUQo5
        TS9sQkk1ekgvUjBwa3oyY2ptQnpldzhTcW16OVhScjMvZEV1Tk0yMm9RCi0tLSBY
        dmE4Wk9iUHFPZ2VEUUVMOXJMd0tMSUFLdXZ4MGxpb1d0OVVsQWxFMmFBCqAZDnIo
        UnnO1tKeAly1jiCpTgy5p5OeAqcn59ZOl/2fqYDr9FVw0OlNTJe90VbSwneKZbXV
        9G167kdIHUE8YvM=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq13kgy63cgnvwlckua679c7jrant6jc932vc78zaejqatgh9ee2ys6yal5hsm0jdk9cl9vvyak9up8hf92sjwuscaagp6tvj5f20tn09k20nspt2ray3m7pnxrwvfc5j2md7esds275dpv2zeryjjh6w5mfzdppf9vjzu5p9v8ty7r338r8cndw4h4rpehyysjk828fqk9ga2543rc69jwenxywmnp76tmwcasz0s45wck7y5nyc52smhe3r84rv7a4zl5zg40gv4k5er5vw26c8cd73prkcnskpgpgqltqe75jf3ecfdpwp9sul38g8dsf6geskzrs3awtf36agxxz6aed4r3znqc0sdnfyuhezaflkeqjc69f3nfqcnrqfj04t4x7esq3w6t54rwp297m4zrpadqn3e3ch4rdwacc6j6dxdewzy8dk9qhrxdxgz07spcx44nwq45y72vsrje3q2wsmxnwxmnu8upq3nh34st2a3vqdkzafuz6sq49urmpewxnfuznyjpekp0yduzar3ssucegcapdjjqnrz7ckdv73c5ktksxt60txznpvap8jf2qg76zjyvn9lyd2sh67zvfvmzljv9e9pf98mh8s4xkg28m6r59hv2k59gktmynf47y99eg34rgx8xpeul4jwpkz7mvqe92cz25llpzy7s2enatnyv0323q6xz9fs3c47d2a0gc44w6m90fjgtl4uu8ywcv0s4m9gmx23e2s3kl8mfz5zfx9na39l9l3zvxuvme5pyvl7svnq7z89mx2fa8qzjv8wenhdyzg98hpv6x3my74s5u8p4ng3wsf8f56kzkvd8nvayz4zsqucrc8x2mzs5fhpjyjd29vd5ftwejz44rt9vqe5ez2ext9tqwuu2399ck52mch9q9lq8fyp9ppu0y04y09fq8gmu283etvskhcc9kz0zfv95zupt2s7x7dgn53hr4vgq3f2ekadkw8mp8e3pnhtfcrpjd93euer7uxqh3mjur78pzdwrrvxy0xr2andmnj8nwsa0qjkxeq99dqpdaxqe2jc99h6s5n0h7dcnmfm9uuaxpm84fq0tzjqmk9newrpsvuwry0jjvplv02zva20vh2s9jjrxxq3mpu8ywj8ufzalmuv4q0uphym4fp8eg9ukgk56mep52tdt4u7yz0sqy3delgk0pvd4gvfea3h5e4msv7uvyx6v07qelm2kpj38dj9rca0lpqa0wfzp05fvruh9fmgphxewj8xgx3rgmsrf2a4yn4mcs6ddkp2yc7svu7w80cexezg82qx5tdcr9wmxdpcxnsn82y8fkk95fphp5zvcyffnhm6pr2d04ww4vq9zm9j32gy898ce0ga5psj0y63u2gs62ekt5tp8s4h2yz04nvaqluc2ppaf5yaygx9lxketh3v7rwp397g30nmywg5sd0gd6cprpydf3x9pte3mx4h5ptuvtzyl82df8qvcfsdrvx8n8nafasf3h5rjjnjjp69eyw8qp30ydycj3d2lsgfky2vr873yvjmmuws95v9a43f4qd28w2p6pgaua3kf86alkmsyllljj7hnxezrz6fqapggrzg4vhazr82xvcp0k4erz6dzqrn95n6ueryap0vwxtq2e2qmmfev2w6x8630r3gqlj22ypgllm7fw5e9ql0l09l0g39v8un2gw5yvzvmqjtjcsxdp2le3ztkswgg0hvyeuqvf930xlxe9dwdtzcf0hygs9mcsdpwgu493vtljkzssqnkrh5evm2ycv8f0dz9z84cm0mnzjzgw9z74jznsdr7y77285d3svrgwg3d7essz4f5zhh2q928qmzfzj0m0w65kyda5hm6t5hrgywd3ajhfcm22qleneuxxt7u52u5asg8e9lx2lme8lm93f5cdw4gvcey4fql7hztg5cmq3l0
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-06T06:53:07Z"
  mac: ENC[AES256_GCM,data:Avyt2rPikspLyIeQafZoKaw2qnKn8zACgD+LLe7z+Nf92rWtbsSXACeyC3hF1vfCt3FT6UUdSy86ObFqG62LA9on1c1lOdHLbIBLzAO6yjg7URPy/cnZwa70Mj05E0Ym0Qo/X/kr30R8RGVIORIHybNw9zF+gIL2iiz7d1WB/g4=,iv:9YzWPkm3v4evKVGIW/pOkocRrzpoFSqat0pbW8HSbko=,tag:aBjhh3xT/0fWVPuy+5MtvQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
