apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:ZqxgbnDsxAuR2EkUyUpO,iv:HNM16JbfzdQ/BXME7KhMYNW4LxkzYQOX/4ULOAcvv8w=,tag:DJC6nij8txbdErwUr+aXHA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IEYrdzNtM3p4
        bjZ2eWR2aE54bUtXcmZ5R3N6eWJvTWxsMHhDcm01emZzNHF2YXdkVnBuUHRmQy8x
        aldvemg1Z0lUTUYxbVJTUUVBN3RmMnpHd2kxOUx1KzJDdU5neWlwVGx2Qkd3RVB6
        S2p3SWdWc2dabHU3SXYxYVF1b1BrSHJXeVkyS20yVHR3T2JhUnNibkNJaFJkaTEw
        d3BTdnYwZjdYbTR0Yzd2NVNNeHM2K0cyMk9DZzdIQ0xyK1JYSVR4M2NzYlBXWUJC
        dlg0c2FrYkhGNlVNNU1ma1FVVm1HVGpWaDV2WEpOdE9ZOXZlc2RUSmJ0YUNqWjcz
        S0xUWEp4WFhOZURSM3hsU1g4R0YvQjBjK29PRStoNEVKaU1EZExGVEJESFNUeEVz
        Zy9URVVoRStkSzM0SkV4YURMQUQ4NDBsNnJtYXpncUhaZDd4T0IvdDJnVkIyb0Rm
        djFFL2lpZFc4R2plZ2lCaCtsNVRWKzI4YzZoWkVwa0k2b3kvcVpOcE55U0pGOS9E
        SmpyK2lHSTNBeG5CWWp6RHdiMmgzZ2YvbHZuTXcvRlJHNmpicW5DUk9CUExmMkcx
        NkdaaENaZmFESnJVWERnWEp0Y1lOcWVOU0pOOUNMT0tHZW1VVGd2aFZaYXRzbE41
        NEp3a2huQlJmQkxYTWRVcHF3UEs2WnVZMkFWc21yOTFPVW90QVNvL1ZSbGRDNmU1
        UkY0VkNENnVwOGxPK09kQUxNQ3haZ1ZaTitPSWIvL3UwMzZBSjRjeTl0ZlpWd1VT
        ZW8veXpvWC9vQ3RKQVpvNndFdFhnZzErY0x1SVdHN1ZEK3RmbC9LQkU1Nk4yNnpi
        NFMxb2ErejE1YkpVVHdSU0RmUlNXNHhaS2xGdEdhUE5ZT2RBcFZoT1U1cDNsbWlP
        SzkrT3VTVjl1SjBiL0VjaHMyWjNJb1AxdklyaHo4OVdPZHB0Ny9hdi9NUS9Va3dD
        V0pKNnhqMld0QTdUdnBzem9pNWhZdFVValE0MWY5ZGFYRDVRaXAvQTVCcEFTK3dF
        RzB4MkFYMFdPZWNkcTI3K3hHa3BEbEU1b0RwOFFoYnZTbjVhNWF0TWNGcVNCbHRH
        VnpxODNkRnZRSHlFM2pTSi9BODlWVGE4UHpPdFd2OExabnRuT2VSa0J2TWM1bGdK
        VmExR0ZyTFRlU1hPZlBIemtUWjhRN1N3WW1kb2FkTlNLWWpIa1ZuNHFrNkhzZ3lX
        S3YrNWFvN3RVWGdrV1hUTkFVc3I2bUx1MnJJdDFJU0F6RnRpekVCZFpITkpsM1oz
        WVU1WXpNUW43NnRTOGs5RmJDb0haVkRjVTlJRG1KaXgrMUtueUs0UUhnbklGejVh
        VE9tZDZTMEdiSVF4eWZyeHBCTFBWV1czMTJmeGJobWhsOHI2QThrZ0JqVmNFQ2lQ
        Qlp5ZDlLUVE3SEZGdHlXcEw5cFJBTDl0YVZmb05zWXNMQVVHaEkvTUpxR2NHYlcv
        QWtKUFgyMDFTUEl0TUNUNno3ZUlOeHVENndnNkE2ZXpJVm0vWXpJTEJoTjF4VDV4
        c0RiYjhqZm0rSjIwSFZKZzYvUmwwai9qQllvNXZVSTJockNOa3VZSnBMbUpjSzRC
        d1k2QlNtOVE3a1BLUlZHMnVKdmoxRmVDdzczUSs4WGJhSVdKdjQzN3FtL0ZJR3N0
        bHVGYmR0U0lCTkFNUmxIK3FZYnhQTWFpYWh5bjFYRGhhQ01oZkxZYTh5Q1V6NmhZ
        R3lEWWJLQTJRV1d4Q01KTTdFcUp0NW1qOVo2R0ZKRjFpYWZHcW9maXdUMGE4VkZq
        YTNRL24vNUlnMzFuYi9yOXpiaU0xVWMyVll4QUI2TEg0bG9GMXNraXViczQwV2Rn
        dWttaEV4RFZFMFRQQUk3L2ZTV0JnVkFnZHJldkVxSmZGaENPTTF2bEszWEFQb1pl
        ZFN6d3pXSzduUk4vd0RFemlRRUhmZnpjNURudTF4ZFVRWnZySXRUWFJqQWFmQQpS
        aVdhbEZ5UW5qeDN0L2RXcFlVV3J2cGN2NWdiTUZxcjhqelowUU0zWGxjCi0tLSA2
        R05DSktzbkV3S1pYYXRUaEdGOUxYM3FIRUlVZlRtS2dmUXh5cXdOSnI4CnlAObrQ
        F665IhaXGv23El7y6VlqOlpletvLUUN8dHmkVuWCX7WUWgdYaP6axIl5MJ5KNJem
        MwX5DuzHFN1zuJ0=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq13kgy63cgnvwlckua679c7jrant6jc932vc78zaejqatgh9ee2ys6yal5hsm0jdk9cl9vvyak9up8hf92sjwuscaagp6tvj5f20tn09k20nspt2ray3m7pnxrwvfc5j2md7esds275dpv2zeryjjh6w5mfzdppf9vjzu5p9v8ty7r338r8cndw4h4rpehyysjk828fqk9ga2543rc69jwenxywmnp76tmwcasz0s45wck7y5nyc52smhe3r84rv7a4zl5zg40gv4k5er5vw26c8cd73prkcnskpgpgqltqe75jf3ecfdpwp9sul38g8dsf6geskzrs3awtf36agxxz6aed4r3znqc0sdnfyuhezaflkeqjc69f3nfqcnrqfj04t4x7esq3w6t54rwp297m4zrpadqn3e3ch4rdwacc6j6dxdewzy8dk9qhrxdxgz07spcx44nwq45y72vsrje3q2wsmxnwxmnu8upq3nh34st2a3vqdkzafuz6sq49urmpewxnfuznyjpekp0yduzar3ssucegcapdjjqnrz7ckdv73c5ktksxt60txznpvap8jf2qg76zjyvn9lyd2sh67zvfvmzljv9e9pf98mh8s4xkg28m6r59hv2k59gktmynf47y99eg34rgx8xpeul4jwpkz7mvqe92cz25llpzy7s2enatnyv0323q6xz9fs3c47d2a0gc44w6m90fjgtl4uu8ywcv0s4m9gmx23e2s3kl8mfz5zfx9na39l9l3zvxuvme5pyvl7svnq7z89mx2fa8qzjv8wenhdyzg98hpv6x3my74s5u8p4ng3wsf8f56kzkvd8nvayz4zsqucrc8x2mzs5fhpjyjd29vd5ftwejz44rt9vqe5ez2ext9tqwuu2399ck52mch9q9lq8fyp9ppu0y04y09fq8gmu283etvskhcc9kz0zfv95zupt2s7x7dgn53hr4vgq3f2ekadkw8mp8e3pnhtfcrpjd93euer7uxqh3mjur78pzdwrrvxy0xr2andmnj8nwsa0qjkxeq99dqpdaxqe2jc99h6s5n0h7dcnmfm9uuaxpm84fq0tzjqmk9newrpsvuwry0jjvplv02zva20vh2s9jjrxxq3mpu8ywj8ufzalmuv4q0uphym4fp8eg9ukgk56mep52tdt4u7yz0sqy3delgk0pvd4gvfea3h5e4msv7uvyx6v07qelm2kpj38dj9rca0lpqa0wfzp05fvruh9fmgphxewj8xgx3rgmsrf2a4yn4mcs6ddkp2yc7svu7w80cexezg82qx5tdcr9wmxdpcxnsn82y8fkk95fphp5zvcyffnhm6pr2d04ww4vq9zm9j32gy898ce0ga5psj0y63u2gs62ekt5tp8s4h2yz04nvaqluc2ppaf5yaygx9lxketh3v7rwp397g30nmywg5sd0gd6cprpydf3x9pte3mx4h5ptuvtzyl82df8qvcfsdrvx8n8nafasf3h5rjjnjjp69eyw8qp30ydycj3d2lsgfky2vr873yvjmmuws95v9a43f4qd28w2p6pgaua3kf86alkmsyllljj7hnxezrz6fqapggrzg4vhazr82xvcp0k4erz6dzqrn95n6ueryap0vwxtq2e2qmmfev2w6x8630r3gqlj22ypgllm7fw5e9ql0l09l0g39v8un2gw5yvzvmqjtjcsxdp2le3ztkswgg0hvyeuqvf930xlxe9dwdtzcf0hygs9mcsdpwgu493vtljkzssqnkrh5evm2ycv8f0dz9z84cm0mnzjzgw9z74jznsdr7y77285d3svrgwg3d7essz4f5zhh2q928qmzfzj0m0w65kyda5hm6t5hrgywd3ajhfcm22qleneuxxt7u52u5asg8e9lx2lme8lm93f5cdw4gvcey4fql7hztg5cmq3l0
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-06T11:13:00Z"
  mac: ENC[AES256_GCM,data:uTWt/GlqdkLl6Mmsw51Gu9lXxkKS3Mj91mNmD8LrJ+lKmYWoBfO8TlwWErsdDy3sKUwvHoVrRfDtcsOJm5PueCihkxM2wdvt3l/ioFY2q1Nh3sqMuEcH6HfZF3DroDxlY1PVQD6JiuPztHsbvCHtAlTdaUN0OJ3qx3t51K6i5dI=,iv:xTwbaz2SRlb+Ci+RQuPHwn/ZjXw2lRmnYwS5qeYWYz8=,tag:/5ipEWIk0gDdD1jR4orTxA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
