apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:JN5o0WOhXJdKA6uxxqlU,iv:7P5Vvc7Suz0f7qnXDCWD7BkLcX2aiU/SmbmrxHZr2uQ=,tag:6ONYZhHSj2KmnVIiZ/XO6A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHJNTlV1UlNV
        Ni9iQzBreWttNkpwVm4ra2pOajEyemZZTmlzYmNQN1h5bjNYaWFmVmlQc25HbGpv
        eDBEejIxSVJXR3dqdUV0ZzRUWUlMcGFQQ0d0WmFjSXVIVnJxUmdRZDBNQzgwQUt1
        M0U3NFI4b2NMWHFhZ0hGdStWOFI0Q0I4SU42VlU1aTE0TGp3dnZFMldEZGpBOGJN
        QXMxWnVqQi80V3FWdlF6V2dVbFVJZHdsWkMrQlYyOGxOa3p1ZU1CLzdGRncwR1VB
        MU1wNGdIa0xyU1VvREg0bklHWHNubzJIb2QrUzRWNmY0UzhmcGpQbW91eUYyR2hG
        MEdyMnYvblJsOUdvWjdQY2pTRWJqWmtmZUxkY3A1eGJ3T2IxdGJzTHpCUmYwTFBq
        eWJBdkNBRW51enhaOUNuZnhjZE1mZ0dDZitvV3lWcmlBL2Q1bzI3b3VxOG1rcnBY
        Z21YL2tuUzRaT0dyZGoxRmhPU0s4VEJSZjBHYkdRdCtoMGxwc0NsQklrZ2NNZFNR
        ays3YTdpczJQNC83NnZSRjZxNkUyUjN0YnNJUnAwb0FLV3BqdmRHOFpYSzNnWCs4
        MGRwaHN0V2FjWnZ4ak5tbnhtamJxSHZ4RjBCRFNXL0VBdFdVeXhJV0U4ZUV4S1N2
        dGtEVVpzSk5IMXhmVjcxaTZoaWt2NUFSeHB6QWNwSEZnekJXQ1VYTDdpdTFwbnhu
        V2xLeFlFOFVVekU5dUN0Q1BXeW5EMFUwVnpFYUN5MlU3TElOeC9wN0lDcitHME54
        dlI1YUdpUjg1b2RsT2Y4OVdzQlVwY2dmRmFYd1ppdDV0eXFRc3pKMG9PMHFuVk9U
        UTVqc2dLV3JtUEhJK2ozMm9JVUJHdnpHWGhSMS9kNXdIT0ZoS3FxYitaMndkdzJs
        N2YrNC9Zd0x2VERRU2dnZDdWMkRXQWxxaFZuejFhSGtpcmJEVlhuL1lsTWdlM2lO
        bUpoZ2RtdzYreHFKd3lCUzBNbGg3V3k3KzJ2RG5FM25ITGNFSzZTLzA1bGZVeE5M
        dkRaTDlJaVJKYm1MNHZ2VFN5K2dGZHJVRGRKZy9UMTRlVDRIT1hscnlkM2UvbTJy
        QzdqdzZiZVRTRnBsRHF1N0s1N2NtTHFIMHVFWlBhdmZTZWU1dFpLVXF4M3liQ0Rk
        L0Q1VGZ5Q1VwSjR2N1JKend3ZG9SaUYweEE1L3B2Y0FoTE5udERJUU45ZW5MZjlB
        ZlZaclQrRmcrZlpvcVdQMy9HN0phWk1rVWxUMHljSVhoVFZHNVFCd0lRWUR4a2dj
        a3Vjb2tPWUxiamtMN2taSHEvaGRQV1hIakdlajlnc3dJRnY4ekJyQ1hoaERDam85
        aFowUTYxZ3VCWi9MMUxYQVBNbm1WVU1VUWpSajRLKzFUamNscVBJamhxNXgxcnVQ
        NklLamxuakxPZVd4SVMwOFFWTlh4K1UwNnBFR2haY3lYVHNFdWVrdzVlcnZLUVk4
        Z2VEMGtQcHFVU3NPWktjaGpWMk1icXhudytzQlVsTHBkdko3TTNSVWtaYURUOE1a
        OU1YNHhEckJOeTV3UHgxdEpySkx2SjhBa0F4WkZWcHlKMnhUUGZjeEpQamtndDFH
        YUpsMWZWZUlTbzM1S3NsZTJZb2Z2OS9HTHhCOW03cFRxSEdHeUFONVdBRktCVDJp
        eTlNdWZZaGRxZXp3RGd5cFNrN2xvS2hxQmg2MU1tYzhyTGdOQk1IQ1RVdGF3Njkr
        dmU0d21SSWdpQ0Nrb1NUamFvMGJRalNOTTdianJxUHlPcVRsYmpJQ3d0VEg4a1R0
        U1pCUjk1cXN4b3JxZDFPL1pOSWQ0Sklaa3dqeEMwZ09WMjFXZmpQT00zUlVKdlor
        WEMrbk13amNUVjJjOWs1L0ZFMnltWDBiRjNZZmozNFNwaHJTaTF0L1g1RGNTY0tN
        TXpyQTZTN2pqeUtCVFhOalRZd3duOXIxOXBvZWN0akdQQmNyOWlxalQ0MmhBUQpV
        a2hBVXZXR24rb1NtdDM0Y3BmeW9QdGZGUENqdmxEbGRMOEdrTEl3WE44Ci0tLSA1
        eTB5RWNPZnB4T3p6cEprWlRNc3dLdXcrN2MybEZycEF1MWVsNks3OTVvCoCQfKSR
        0Exskaizesn/ZtDFfcXIkWI9JtOKXKIMm4Ce0ztE78rSrDd2+t5iSrNgwuTg4wBJ
        wEpuK20MXePTwNQ=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq13kgy63cgnvwlckua679c7jrant6jc932vc78zaejqatgh9ee2ys6yal5hsm0jdk9cl9vvyak9up8hf92sjwuscaagp6tvj5f20tn09k20nspt2ray3m7pnxrwvfc5j2md7esds275dpv2zeryjjh6w5mfzdppf9vjzu5p9v8ty7r338r8cndw4h4rpehyysjk828fqk9ga2543rc69jwenxywmnp76tmwcasz0s45wck7y5nyc52smhe3r84rv7a4zl5zg40gv4k5er5vw26c8cd73prkcnskpgpgqltqe75jf3ecfdpwp9sul38g8dsf6geskzrs3awtf36agxxz6aed4r3znqc0sdnfyuhezaflkeqjc69f3nfqcnrqfj04t4x7esq3w6t54rwp297m4zrpadqn3e3ch4rdwacc6j6dxdewzy8dk9qhrxdxgz07spcx44nwq45y72vsrje3q2wsmxnwxmnu8upq3nh34st2a3vqdkzafuz6sq49urmpewxnfuznyjpekp0yduzar3ssucegcapdjjqnrz7ckdv73c5ktksxt60txznpvap8jf2qg76zjyvn9lyd2sh67zvfvmzljv9e9pf98mh8s4xkg28m6r59hv2k59gktmynf47y99eg34rgx8xpeul4jwpkz7mvqe92cz25llpzy7s2enatnyv0323q6xz9fs3c47d2a0gc44w6m90fjgtl4uu8ywcv0s4m9gmx23e2s3kl8mfz5zfx9na39l9l3zvxuvme5pyvl7svnq7z89mx2fa8qzjv8wenhdyzg98hpv6x3my74s5u8p4ng3wsf8f56kzkvd8nvayz4zsqucrc8x2mzs5fhpjyjd29vd5ftwejz44rt9vqe5ez2ext9tqwuu2399ck52mch9q9lq8fyp9ppu0y04y09fq8gmu283etvskhcc9kz0zfv95zupt2s7x7dgn53hr4vgq3f2ekadkw8mp8e3pnhtfcrpjd93euer7uxqh3mjur78pzdwrrvxy0xr2andmnj8nwsa0qjkxeq99dqpdaxqe2jc99h6s5n0h7dcnmfm9uuaxpm84fq0tzjqmk9newrpsvuwry0jjvplv02zva20vh2s9jjrxxq3mpu8ywj8ufzalmuv4q0uphym4fp8eg9ukgk56mep52tdt4u7yz0sqy3delgk0pvd4gvfea3h5e4msv7uvyx6v07qelm2kpj38dj9rca0lpqa0wfzp05fvruh9fmgphxewj8xgx3rgmsrf2a4yn4mcs6ddkp2yc7svu7w80cexezg82qx5tdcr9wmxdpcxnsn82y8fkk95fphp5zvcyffnhm6pr2d04ww4vq9zm9j32gy898ce0ga5psj0y63u2gs62ekt5tp8s4h2yz04nvaqluc2ppaf5yaygx9lxketh3v7rwp397g30nmywg5sd0gd6cprpydf3x9pte3mx4h5ptuvtzyl82df8qvcfsdrvx8n8nafasf3h5rjjnjjp69eyw8qp30ydycj3d2lsgfky2vr873yvjmmuws95v9a43f4qd28w2p6pgaua3kf86alkmsyllljj7hnxezrz6fqapggrzg4vhazr82xvcp0k4erz6dzqrn95n6ueryap0vwxtq2e2qmmfev2w6x8630r3gqlj22ypgllm7fw5e9ql0l09l0g39v8un2gw5yvzvmqjtjcsxdp2le3ztkswgg0hvyeuqvf930xlxe9dwdtzcf0hygs9mcsdpwgu493vtljkzssqnkrh5evm2ycv8f0dz9z84cm0mnzjzgw9z74jznsdr7y77285d3svrgwg3d7essz4f5zhh2q928qmzfzj0m0w65kyda5hm6t5hrgywd3ajhfcm22qleneuxxt7u52u5asg8e9lx2lme8lm93f5cdw4gvcey4fql7hztg5cmq3l0
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-06T12:26:41Z"
  mac: ENC[AES256_GCM,data:uggKbZqUDkt0/iW9Itd7vtXX150lHzb/vVv5NezEXjbmmqjmCZytP4aC62+s0CDvOSAVRcGmuPmCmtFgZPVaIneUmlZvKh46uO05Cx4nL0FkFixYwrdiAAHIXXVDoh5snfVJd682JMHYWQeP0VnCcCTGE7qVNvyKo3dzChDzk3s=,iv:U5fMU11maXF8e5OTTLsfbJRR52sGmq6nYFJDX1BBSa8=,tag:d/Q91xFvhICT1J+NauuTdg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
