---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: frigate-exporter
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: frigate-exporter-secret
    template:
      engineVersion: v2
      data:
        # App
  #        FRIGATE_USER: '{{ .FRIGATE_USER }}'
  #        FRIGATE_PASS: '{{ .FRIGATE_PASSWORD }}'
  #        FRIGATE_STATS_URL: '{{ .FRIGATE_STATS_URL }}'
  dataFrom:
    - extract:
        key: frigate
