apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: litellm
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: litellm-secret
    template:
      engineVersion: v2
      data:
        LITELLM_MASTER_KEY: "{{ .LITELLM_MASTER_KEY }}"
        DATABASE_URL: "postgresql://{{ .LITELLM_POSTGRES_USER }}:{{ .LITELLM_POSTGRES_PASS }}@postgres18-rw.database.svc.cluster.local:5432/litellm"
        INIT_POSTGRES_DBNAME: litellm
        INIT_POSTGRES_HOST: "postgres18-rw.database.svc.cluster.local"
        INIT_POSTGRES_USER: "{{ .LITELLM_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .LITELLM_POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        GEMINI_API_KEY: "{{ .OPENCLAW_GEMINI_API_KEY }}"
        GROQ_API_KEY: "{{ .GROQ_API_KEY }}"
        GENERIC_CLIENT_ID: "{{ .GENERIC_CLIENT_ID }}"
        GENERIC_CLIENT_SECRET: "{{ .GENERIC_CLIENT_SECRET }}"
        GENERIC_AUTHORIZATION_ENDPOINT: "{{ .GENERIC_AUTHORIZATION_ENDPOINT }}"
        GENERIC_TOKEN_ENDPOINT: "{{ .GENERIC_TOKEN_ENDPOINT }}"
        GENERIC_USERINFO_ENDPOINT: "{{ .GENERIC_USERINFO_ENDPOINT }}"
  #        DEEPSEEK_API_KEY: "{{ .DEEPSEEK_API_KEY }}"
  #        GLM_API_KEY: "{{ .GLM_API_KEY }}"
  #        OPENROUTER_API_KEY: "{{ .OPENROUTER_API_KEY }}"
  #        EASYROUTER_API_KEY: "{{ .EASYROUTER_API_KEY }}"
  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: litellm
    - extract:
        key: openclaw-test
