---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llmkube-models-cache
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 200Gi
  storageClassName: ceph-filesystem
