#---
#apiVersion: resource.k8s.io/v1
#kind: ResourceClaimTemplate
#metadata:
#  name: llama-strix-gpu
#spec:
#  spec:
#    devices:
#      requests:
#        - name: gpu
#          exactly:
#            deviceClassName: gpu.amd.com
#            adminAccess: true
#            allocationMode: All
---
apiVersion: resource.k8s.io/v1
kind: ResourceClaimTemplate
metadata:
  name: llmkube-models-gpu
spec:
  spec:
    devices:
      requests:
        - name: gpu
          firstAvailable:
            - name: gpu
              deviceClassName: gpu.intel.com
              adminAccess: false
              allocationMode: All
