apiVersion: v1
kind: Secret
metadata:
  name: flux-webhook-token
stringData:
  token: ENC[AES256_GCM,data:nUXvM0sw4ccdi7nMsp2Nb/nGLjj+YZJv6szr1V+dXws=,iv:T79SdaM740LFCalzmJUH/A+naJFYmkkxjvwALUwlcb8=,tag:LIFbuylLFezynrBC32OIpw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IDNBMTdqd1ND
        cS9NSFk2OG95OXFTanMvTHVkYVJQbE5WUXhCRnpEQzgxYXZPSVNlb0lxR0wxQTB2
        WkFlTjhSVUlRRU5WZ0hRcm4wWXlWUEp6UFpDY2prTTdVZFRWWUF0US9CRnk0bk1Q
        eFVjbGVIWklSWEdGM0paODVxVHAxQTEyRGVTZjNlNXh3eXUvWnlPZDFvM0JDYktB
        YXFkS1BLY0xmUW5SRHZSbjIyMUN1d1FIUEdPelZWNWRhSFYvSjZWTzhibVRUSjVs
        dzhQZmltb0dPMU1LVWkzdnNYZFE0TFc3cVJEeGhBZy8rWURqRDZUcUFvOUhJbnlS
        SExMMlIwbGVXZjV1QjFqbG5MWGV1eXgxRitJcTBZeUNkVTJ0MFZMK1R4TFg0YWhr
        OXRRTE1zM3V5OEEyZlZZMzJiUDZYQ2tTWWlnWFA1ZVhvU1FwWnMvNlZwaUNmMTdW
        MitueUJNdWZueVBsV1VFRWNJTlFxSnRSenVxeUY2cUhzdXdpV1hFVUtCemJQdzVJ
        cFpQdHBxNndlaE1FU2I4NHNYeWRzMy9iVWdselU4Mzg5RFB0NDZIdXZKVXRLTDJR
        eFBrdkdXQmN1KzVHR0hyMzdzZjQxa1o3U2VRcktramd1OEN1MDRJUnZkWWFVejVN
        RkN5Ui9lT3Zpc28wSGU1UDZlZC8ydWNuNkpsUXUvOG9vN2dOcFc3bzllaW9hSmlJ
        djNFcHorRDltZE1UKzcvMU16WlJzTG5acUFhSG94Slp6YlRSZy9NRG5KQllmU0Zl
        akZVL29XaUhQK1Y3TXNlUjk2ZHFvb3dmUzNHQzFycVZNaVRZRFJkSmg0bG9uZUxD
        ZXk1RS96bkVtN2VzQ29sQWtscDM3aklMTkMrMDdwTjNvZW4xUGlSSVovcUtndnJJ
        ZmlQb0dtVDZIcTdmUkRZSER6MXlOTFBtTEY1Q0hMdGlZOVB0NkF3Q3J5SjVGTGNY
        V2hucUQ4YS94TkJBem1xWWxiK1EwOU11SDI4M29aamtFcmRiM2s2L0o4cnJHQ0sx
        bExvYXhqcjdhVWhBdmZrWFZ1Y3JjYlhkdmpYZFoyMTE1djJIZjBEQ1kzalg5b0F6
        RThVRW1VUmY0eCtYVDRZVkpTTDNCWEM1ckUrdUpybysxUitHOXVsU29JQjNKZzF0
        ZThqVHBpKzdlUEtEMHY0UnV1TitRaFdGRHpOUEk3QVNvVndOSTBkS2VQTzcvYXFP
        ZmZOV1BkeTRBUDhNb3BxWSt0OTVPTFY5cnRjTGJRdlQ0RWtaQXVkMDU5dmtmMzEv
        N1ZBNHVOaEtYR2NoS21CVmJuNGZDcFRza2hUQTNsVXd0MGFRVWlkNmNNOVVuOGds
        NGpqUlAzR05HODRDbEdJa1BkNXFHRy9jTkNiR0hRRUFtQUR4RkRIb2h0ald3QnlI
        OWVUVC9kbW0xZ1ZCSXlVc0ZKamJJeUZEeWdNSzQxL052di9tSjEzWG94RjBva1c5
        ZmxVVTlxV29jcVJBUVl6by9GbWY0MkI1U3FBYkpONXRuSUg4Tkp1bkNLM2RGaDk3
        MDZ2bHBKZHdoZ1U4MW1nWGtKZ0llS1ZQMk9SL0ZCSkVVakFBa1BQM0ZGbkJsczBy
        aHlwbTdRZGg2UCtFd0JuSC95c0ZzZDB1dHVrK2FJSHlvYnc5MWJBYk93djIxODQv
        dVVhSXFwWFkxc1h0N0tSajBSYkdxOC9DMm4rS3RCM0wyZEtsdEMwZTlCUWxuQTk1
        UFdDZmJVSFBDdHFUY0wvWWtuUVp4eDZrYTBXM0tIeXJBblJhVm0xc1pSOGF0bFVm
        enRxVndXRjV4YXZVcDJKSTRBc01GU25GZDIxd3J2OXArbW03WmxkcW1aaDdLNC9C
        bWp6cjRnT0xoclh6eWhjeksvYktXSTMrM3dkQ0syUUxHejhBZUdHUStWVitkQkxN
        SEMrZENNWmdzL2RwcU5QdVdmeXYrVFl5S0FWSWpNLy9DSmtLaGVuNlBSNWFHQQpu
        dWFqQUdrT1ZBb0hZTjdkT3plUmNDTWN4eXBDNU5rNWFPdGhhbGxYS1N3Ci0tLSA4
        M3ZqWFBzTU96dDdaL3ZoVnBBMTZJUzBUbXY3eU9yKzFlMURqR0c2RDkwCoc1XZkg
        HlJhuzzMYcJmAYCKXiRv0WhtUZ1D/n42nK2gLUB2CozH9jfOPQ02PHwHsWn8Rhgy
        5VI70cozubnBsKQ=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq13kgy63cgnvwlckua679c7jrant6jc932vc78zaejqatgh9ee2ys6yal5hsm0jdk9cl9vvyak9up8hf92sjwuscaagp6tvj5f20tn09k20nspt2ray3m7pnxrwvfc5j2md7esds275dpv2zeryjjh6w5mfzdppf9vjzu5p9v8ty7r338r8cndw4h4rpehyysjk828fqk9ga2543rc69jwenxywmnp76tmwcasz0s45wck7y5nyc52smhe3r84rv7a4zl5zg40gv4k5er5vw26c8cd73prkcnskpgpgqltqe75jf3ecfdpwp9sul38g8dsf6geskzrs3awtf36agxxz6aed4r3znqc0sdnfyuhezaflkeqjc69f3nfqcnrqfj04t4x7esq3w6t54rwp297m4zrpadqn3e3ch4rdwacc6j6dxdewzy8dk9qhrxdxgz07spcx44nwq45y72vsrje3q2wsmxnwxmnu8upq3nh34st2a3vqdkzafuz6sq49urmpewxnfuznyjpekp0yduzar3ssucegcapdjjqnrz7ckdv73c5ktksxt60txznpvap8jf2qg76zjyvn9lyd2sh67zvfvmzljv9e9pf98mh8s4xkg28m6r59hv2k59gktmynf47y99eg34rgx8xpeul4jwpkz7mvqe92cz25llpzy7s2enatnyv0323q6xz9fs3c47d2a0gc44w6m90fjgtl4uu8ywcv0s4m9gmx23e2s3kl8mfz5zfx9na39l9l3zvxuvme5pyvl7svnq7z89mx2fa8qzjv8wenhdyzg98hpv6x3my74s5u8p4ng3wsf8f56kzkvd8nvayz4zsqucrc8x2mzs5fhpjyjd29vd5ftwejz44rt9vqe5ez2ext9tqwuu2399ck52mch9q9lq8fyp9ppu0y04y09fq8gmu283etvskhcc9kz0zfv95zupt2s7x7dgn53hr4vgq3f2ekadkw8mp8e3pnhtfcrpjd93euer7uxqh3mjur78pzdwrrvxy0xr2andmnj8nwsa0qjkxeq99dqpdaxqe2jc99h6s5n0h7dcnmfm9uuaxpm84fq0tzjqmk9newrpsvuwry0jjvplv02zva20vh2s9jjrxxq3mpu8ywj8ufzalmuv4q0uphym4fp8eg9ukgk56mep52tdt4u7yz0sqy3delgk0pvd4gvfea3h5e4msv7uvyx6v07qelm2kpj38dj9rca0lpqa0wfzp05fvruh9fmgphxewj8xgx3rgmsrf2a4yn4mcs6ddkp2yc7svu7w80cexezg82qx5tdcr9wmxdpcxnsn82y8fkk95fphp5zvcyffnhm6pr2d04ww4vq9zm9j32gy898ce0ga5psj0y63u2gs62ekt5tp8s4h2yz04nvaqluc2ppaf5yaygx9lxketh3v7rwp397g30nmywg5sd0gd6cprpydf3x9pte3mx4h5ptuvtzyl82df8qvcfsdrvx8n8nafasf3h5rjjnjjp69eyw8qp30ydycj3d2lsgfky2vr873yvjmmuws95v9a43f4qd28w2p6pgaua3kf86alkmsyllljj7hnxezrz6fqapggrzg4vhazr82xvcp0k4erz6dzqrn95n6ueryap0vwxtq2e2qmmfev2w6x8630r3gqlj22ypgllm7fw5e9ql0l09l0g39v8un2gw5yvzvmqjtjcsxdp2le3ztkswgg0hvyeuqvf930xlxe9dwdtzcf0hygs9mcsdpwgu493vtljkzssqnkrh5evm2ycv8f0dz9z84cm0mnzjzgw9z74jznsdr7y77285d3svrgwg3d7essz4f5zhh2q928qmzfzj0m0w65kyda5hm6t5hrgywd3ajhfcm22qleneuxxt7u52u5asg8e9lx2lme8lm93f5cdw4gvcey4fql7hztg5cmq3l0
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-07T03:14:24Z"
  mac: ENC[AES256_GCM,data:pRNt9k3HT2URp+N7xr/zaK79ZWmwRQAPr9JMys7COTlXa/Qed0ikIcluix8UPob945wH9UmypWqlUSIzD7j7SYGswPUfp3WXwJsBtF7CRyYmLeHDJNmFm/DA22cgX7hxD4ZBNfMphhkOwhFjJ+fkyVTJtGWwhde4StaleBCn75o=,iv:zIdKuniI4ZnkLsp/Z+t6+nUEKuODmXY3/WkLmIv3pnE=,tag:BiZtSbjckqa75MBs/1TxtA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
