apiVersion: v1
kind: Secret
metadata:
  name: flux-webhook-token
stringData:
  token: ENC[AES256_GCM,data:+PS9Jsg5jV/7R/ovVZW1Kh4p+2xJTF2VsHq0XNh3Y04=,iv:E8Yk9SlSnKIH0ZkgaWfAFFThzS4rCWtQpLVTKNsQghE=,tag:tyboIJfegjrEe95ZvnarjQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHpGV2p5STht
        dExWNWY0QlpnaXZsTWZiN3F3QmN2bjB3OEw1WkE5dkNzTkFLZlppc3FHTnhEamZP
        OWc3M1NiNm13V3lXRjFHOVh0TWw2MEpNL3lZOTgxeU83Qno3aVA3Ulh3UXdGdThL
        TVY0Qzc4eEhhSlpFd0NXZnFKUzJRVU1Cdit0Y3VxdDkxOW5aWTVKbWlya2FHR2VL
        MDYxKzJpcWpzS1VzcXZCenh5dWh4WTZhSW8vSWg3NE8wM0FiWEEwRFlsMHFIRmRV
        T1R4M0FFVVg5NlEyY0NYaGQ5TGJTYVN5YytYQmQxQnQzVHd6blZhRFVsQnZPdDU2
        VnZla3BhZTFYcCtKUXlQbWxzWjBHUERKd1U0VnUwQ08xUmtoZWU3VUttQ0VzMDEw
        ZkpVNi9jYUpnVXVFSDdHclBFcG1zWFBZc0g0d29zKy9STzIvamlhbXNPM3BiL3ZB
        TDhqYk9sU0p2bTFhbTM0THoybHJNNFk4QmFNWUdoZEpVeFVrSGFYU3dMNUhUMUww
        NzBxYTBQSER4UGN0WjR0MEEyWmNVSjFSbUZ6dWZzZ1BwdHJyUGZFaktOd1hwRHA4
        MFg0OXNzS2tYS29Ba2ZZdTh2Vll3eldxYUtGczZ4aUhpTFhKU1JGKzByRXBKeURv
        LzZ4cnUyMWlKZGs5QmlJWjZwaVdPeCt4dzZqb0p0WWJoSjNkTTlaQ0VPNk1xZzJY
        MzQ0aUlyMDh3V296YWhqOFdKaGpwL3k4Nm5HRk5TVXZGeUx6Si9QS0ZBN1BYcGxk
        dENHMHZmd1lpcGFES2doM2FITXVCczRtOUhNanF1NWs3d0Vkbys5L3B0SkMxZVZN
        bFFSVDA2NjA3NW0raG5DQmEyc0FUNDBRU0p1SG56V0tiTFYzZDVtRkhZV0Q4ekNh
        czVtWTh6NGkvWTM0TVZDU0hiVWthZU1NUXNtT2lsakdWNEFJczhNVkU0aHd5ZGFz
        YU5BVmxQRjZXanlOWVFMTnBTelBQVmJmTkZOdUNPUE5MY3Nmd3dpYVlESEpuRDdY
        N2hMbm9lUXJlL3orTkVuM2Jqc3QyRkE2VFhrNlg2c1hORExvQkZ0Z1dSUFpPWngx
        Njh6cUF4bWhwcG82elFzSnFtcHhBbkxZSktqMjFwTTcxSldEa3M3MnBUMDg0Zk5r
        NDltdkNhNDZWbWtHTDQrWlVEdXFBZFRrV2oxVCs0M2w5Ti9oUDczUzBPY2trUmFG
        ck4rZmROMlpsc3U4NkFOdk9TdFM5MlhhRVQyT1J6YmNRb1BWUUk5WHY5TC9YUHdM
        cWxNT0pMR2RiWmJ2OHZIRmFMdnZabzBWU0FJVVpPdXBYQzVDU3lZQXFSa1BDY0NP
        Nis4TkNWQjlDbkZ3eHJUTVhOeEtiSUw1U1VKTHlieiswV0I4RllqemptdUZZU2xr
        U0ZnMm9oL09HT2lyUEtHQ29MN09XbHpwN3N5VldTbHVnZDRKK2dySnlmNUJOeTNC
        MjRRaThPcDV5bHB2Uk42M1M3UjdkZzF6VlY4bDNRZTdra3RwQUdoUFdueVBGR21W
        YzlnY21wcS80ZThhSVlHT1N4TWxaUVdjdThadThVejVqS1MvVzgzcUVaZFU0c2sy
        andubTJNL1N2RUk1aXlHS0JLM0EvY3ExME1QbGxhdS9Lb1RHQ0pIeEorWGhlNnJ0
        Y3NWamRqcVV3YUFFcElSbk5qa1cwcjVyWkNwTWlJckxCcHZ3ZVQ3TUl5MjlieW1T
        ckF3NDcwb2RBT3ZpVFNjcU5EVmNSTE1pOEVlY0hFY1M2RlFXdlZvbTdIOVB6c21i
        ckQvY3pRaWFKbUl1eCtWdmtXK05xNTZHSUFmczZkczNQbjRvNEkxRFh3V2JUMzdW
        bGViUmc4Q2JDRjRVeFVPSXpOVVV0VzcraWpwTSt4UGNSZVFzMGZCZ0dNK3JhU2Uw
        NHB6dzk3dHNEYTdVeHZvT3pJZnNORTVLaHVPUFZGUmhkVmpycFNpcWNlZ25BQQpt
        eWdnMHJnU3YrdEhYVlMvY2Z4NnYzZDI0TVRsUXNDWEdyQ2k4aVdPOVA0Ci0tLSBp
        azNEK1FuN3JYS1FtbkJwc3NaTExwV2w0dUFpcnJLbkdtS2hjdGxDWUkwClEduOGO
        voFaH0JdUbskTtqU3wd7FbE0PGZetPMZogy3MNonfqJcwD2e6K2SFogK9Yri+X3K
        1lCq1siiY5FrTck=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq13kgy63cgnvwlckua679c7jrant6jc932vc78zaejqatgh9ee2ys6yal5hsm0jdk9cl9vvyak9up8hf92sjwuscaagp6tvj5f20tn09k20nspt2ray3m7pnxrwvfc5j2md7esds275dpv2zeryjjh6w5mfzdppf9vjzu5p9v8ty7r338r8cndw4h4rpehyysjk828fqk9ga2543rc69jwenxywmnp76tmwcasz0s45wck7y5nyc52smhe3r84rv7a4zl5zg40gv4k5er5vw26c8cd73prkcnskpgpgqltqe75jf3ecfdpwp9sul38g8dsf6geskzrs3awtf36agxxz6aed4r3znqc0sdnfyuhezaflkeqjc69f3nfqcnrqfj04t4x7esq3w6t54rwp297m4zrpadqn3e3ch4rdwacc6j6dxdewzy8dk9qhrxdxgz07spcx44nwq45y72vsrje3q2wsmxnwxmnu8upq3nh34st2a3vqdkzafuz6sq49urmpewxnfuznyjpekp0yduzar3ssucegcapdjjqnrz7ckdv73c5ktksxt60txznpvap8jf2qg76zjyvn9lyd2sh67zvfvmzljv9e9pf98mh8s4xkg28m6r59hv2k59gktmynf47y99eg34rgx8xpeul4jwpkz7mvqe92cz25llpzy7s2enatnyv0323q6xz9fs3c47d2a0gc44w6m90fjgtl4uu8ywcv0s4m9gmx23e2s3kl8mfz5zfx9na39l9l3zvxuvme5pyvl7svnq7z89mx2fa8qzjv8wenhdyzg98hpv6x3my74s5u8p4ng3wsf8f56kzkvd8nvayz4zsqucrc8x2mzs5fhpjyjd29vd5ftwejz44rt9vqe5ez2ext9tqwuu2399ck52mch9q9lq8fyp9ppu0y04y09fq8gmu283etvskhcc9kz0zfv95zupt2s7x7dgn53hr4vgq3f2ekadkw8mp8e3pnhtfcrpjd93euer7uxqh3mjur78pzdwrrvxy0xr2andmnj8nwsa0qjkxeq99dqpdaxqe2jc99h6s5n0h7dcnmfm9uuaxpm84fq0tzjqmk9newrpsvuwry0jjvplv02zva20vh2s9jjrxxq3mpu8ywj8ufzalmuv4q0uphym4fp8eg9ukgk56mep52tdt4u7yz0sqy3delgk0pvd4gvfea3h5e4msv7uvyx6v07qelm2kpj38dj9rca0lpqa0wfzp05fvruh9fmgphxewj8xgx3rgmsrf2a4yn4mcs6ddkp2yc7svu7w80cexezg82qx5tdcr9wmxdpcxnsn82y8fkk95fphp5zvcyffnhm6pr2d04ww4vq9zm9j32gy898ce0ga5psj0y63u2gs62ekt5tp8s4h2yz04nvaqluc2ppaf5yaygx9lxketh3v7rwp397g30nmywg5sd0gd6cprpydf3x9pte3mx4h5ptuvtzyl82df8qvcfsdrvx8n8nafasf3h5rjjnjjp69eyw8qp30ydycj3d2lsgfky2vr873yvjmmuws95v9a43f4qd28w2p6pgaua3kf86alkmsyllljj7hnxezrz6fqapggrzg4vhazr82xvcp0k4erz6dzqrn95n6ueryap0vwxtq2e2qmmfev2w6x8630r3gqlj22ypgllm7fw5e9ql0l09l0g39v8un2gw5yvzvmqjtjcsxdp2le3ztkswgg0hvyeuqvf930xlxe9dwdtzcf0hygs9mcsdpwgu493vtljkzssqnkrh5evm2ycv8f0dz9z84cm0mnzjzgw9z74jznsdr7y77285d3svrgwg3d7essz4f5zhh2q928qmzfzj0m0w65kyda5hm6t5hrgywd3ajhfcm22qleneuxxt7u52u5asg8e9lx2lme8lm93f5cdw4gvcey4fql7hztg5cmq3l0
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-06T12:26:40Z"
  mac: ENC[AES256_GCM,data:LNbcn7qL99J5j4Hn4b98b8+0y7sT9VEEwqSCXt0tDjqV40wLSx9aNuqG7q5lJtyl9GLGZIb4yzZ0qBQgc243X2L8t/grLj6Fs+Z2TcuzpxJR4DUpfw0sCmuksKeM9mEjdiibHB20HtybSaiIwOt2SjnXFJMPAnffiOg9b9z0T/0=,iv:6cDxFUOukQvCIxKUrQFjwBUgE44fh9yjAki8wNsJLI8=,tag:J0ir9+PPhk/73GG4HkkLkQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
