apiVersion: v1
kind: Secret
metadata:
  name: flux-webhook-token
stringData:
  token: ENC[AES256_GCM,data:aY/5vrTPk06fDZBN/n5vHPftz0d4MBjNQtGZkKSX1sA=,iv:3q0oCih8Uv7CI/fDuaBuBh9HPEd4H2PpiU8VK7AN/XM=,tag:KjkVEWsA3Yg+PLtPPviCrw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IG5JVUMxZkF4
        U1hyVXhFTVl1YUFFUkJocE1yYW95bHhWZUxYQVY0Y0o1UCsxS0lWRDBLUHFScXAr
        QjNlb1lBY1RaWjgvR1dhY3Q1bHVIMis2ZzArNDU2cHNFZSthODRoMHZzbXlRME9B
        MlFwMUJYRjdkOTIwclZ3REJPRkdzQnMrNWl6dTE1RlFZRVBuYjVhZXRPVEFFbkV4
        OS9RVEpRNTc4YUQrVnFmZTNEN01yZU9vT0lqMWI4c2NrNHAzUjZKa1RORVdQR1Nu
        RURLVm91aDRJYVNUMlRQNDJoY1pEWTFvNk1Kb0tucnozTWsyNldZY1RyY2NDQkFZ
        c1BYN1k5S01iMjl2OFBWQkdmSmtkUGdacm9kSHNTZWxqNVJLL0VpRmNsMkZhRStE
        SVBldHRTYS82OFhleUVvYnBZUm54V1VtclJmV1Q5ZmxrQ3JxekVBak9zVFFNdjhI
        SnltWndETnRYaDdkVWVWbW5RTGwrbFRTcHJ1eERvV3p3QTU0RExTckRHeElubXlX
        eHRVNE01aTdZRW9oN2xyTjVJTFVjMUtBaWlyVDV2T1gwL1VuNUt5RmpKK011bEJ5
        VC81TVFWSXAxRjdnL2NFalRFcFlQNGI5OHc4U1gwWUY5RFFXQWVoeDZrNmNBRjlZ
        Wm4yVHV6YWV1eVMweTgxWU1pY0NxSXpmK0p4MlJLZXBWQmNGY2lBaTducDNKQkxR
        WXFwL3g2V3FMb1JtTElFeW4wc1hHdXBBK1h1STBROFNPTVhhcnN0YVpMMjltUWlw
        dklvZEw4dGNJMHBCL0FqZzN4eXhpZm1XVGlqTVg2OHFOdjl2N2xpM3JCTXAzTjd4
        T0ppMG5CeHhBNENhOWVmYmFTR1BuSjBNSFFrRDdjVS9kM2NabVJsSU1JU0Vob0lW
        UHlmVzlUQlJoWlFqQWRUTkxGZzFDcWlDblZJeDVITXdhZlJ5UzJ3WW54ZytWT3pC
        UHlYRHUyMTdQS2xvSW1qUXp2RHJLQXppMGswdUNOYi9IOGc2VXc1d3RaRlNkd3N1
        dTJFUngvdHB0UUtJMXk0WFhyN2o3UkRiRS9PeXRsUTBoQStyRkM4MFo3cjczQTBL
        RzU2SmdhWDJEME1uMVBGa3hRek54eUNhbUJOMzdDVlNmUjh6RVNydkExbStIbHVu
        MlErdVZld2ZGVFd1aFpuZHoxKzVEVzhEaDVWd0ZCdjR1VmtydU9GQ0tRdXAzOHps
        c3NiMExPUG1qd1VlUUczOVhPblNneU5HbmVTYnI5WSs4eXlNRy9IZ3p6c2R2SEIx
        K2ErRjlUbVNrTHdWeFVEL2J0ek1GQWNkb1V5eE5tamZnWjRlbVN5VGFzcmVlMVND
        ZDJpNFZ2RUp3UkpzODFTaUpGb0YxUUk3MlpkQnN4K3VjaW5CY3JXOTFtMS9ncHhL
        YnlzQmlLQldlRFZOTjVoQ1ZnT3RrSUNrYkFwcmp2Qm1RMUh2VVI5YmloU0NMVCsr
        N2hTWE9jMURtN2d5eXBXem1SS2RmU1pwa1N2bEczSkgvb0FrY1dicVREUTVaVUFO
        V204MFQzUkZ6N2R2WldFYmZpb2hhMmlrenk2bkhJUVJZc2FqSm5XVzNJeXZrcjVF
        Y2w3bVBDZ2NBWFpIN1U3TWM1cVRXMytKR1VSb09aM1JCVnJxdk1reTE2dUMwSEpj
        WDJIRTBLZjRkNHU0OXNvZThvM2trK2ljN096YXIxeVplSlA0SUJncXhRTloyVlEw
        dzVvNWF6OHVuUUIxUGZCcmIwcGJ4eTN4UkVIbHlVNnBOcFIySGIrVWFINFpiUHdJ
        UlVTaUNpeEpXVmJia3gya0hkbHZjZ2dMRERBT2s2YW9sZkFURU1POTU2dGdTbkIx
        OGJkbGgwRmdySFdmbjNUb3lOZnBOdmYzTlFwSk9FMjltM1RObXVEOUg1ZDJVMmFB
        K0NtVUM1aFQxbHVIRityTmpjeFVxZFN3Ukc3RXJteE9UVlVTWTNVQkFZemNCZwpw
        VkJsb2pPOGF2TC81TEM5Nlh5N3dTMnBRVUZySnN3T05hOUdhM0dlM2c0Ci0tLSAr
        Y0FXbGNzY1JzOW1QdC9YMW5wNEd6QVcyMFJRb2hqRnUvWFo1Zm9tZnZvCtRK3UkO
        kdfBuQqoZaBnaLaLo9ys0a8vxxnkFWfbcftlr0w/Dxc3LyHdQVDqrA6P9RrmNANG
        EVOIvKqEMcC5NPM=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq13kgy63cgnvwlckua679c7jrant6jc932vc78zaejqatgh9ee2ys6yal5hsm0jdk9cl9vvyak9up8hf92sjwuscaagp6tvj5f20tn09k20nspt2ray3m7pnxrwvfc5j2md7esds275dpv2zeryjjh6w5mfzdppf9vjzu5p9v8ty7r338r8cndw4h4rpehyysjk828fqk9ga2543rc69jwenxywmnp76tmwcasz0s45wck7y5nyc52smhe3r84rv7a4zl5zg40gv4k5er5vw26c8cd73prkcnskpgpgqltqe75jf3ecfdpwp9sul38g8dsf6geskzrs3awtf36agxxz6aed4r3znqc0sdnfyuhezaflkeqjc69f3nfqcnrqfj04t4x7esq3w6t54rwp297m4zrpadqn3e3ch4rdwacc6j6dxdewzy8dk9qhrxdxgz07spcx44nwq45y72vsrje3q2wsmxnwxmnu8upq3nh34st2a3vqdkzafuz6sq49urmpewxnfuznyjpekp0yduzar3ssucegcapdjjqnrz7ckdv73c5ktksxt60txznpvap8jf2qg76zjyvn9lyd2sh67zvfvmzljv9e9pf98mh8s4xkg28m6r59hv2k59gktmynf47y99eg34rgx8xpeul4jwpkz7mvqe92cz25llpzy7s2enatnyv0323q6xz9fs3c47d2a0gc44w6m90fjgtl4uu8ywcv0s4m9gmx23e2s3kl8mfz5zfx9na39l9l3zvxuvme5pyvl7svnq7z89mx2fa8qzjv8wenhdyzg98hpv6x3my74s5u8p4ng3wsf8f56kzkvd8nvayz4zsqucrc8x2mzs5fhpjyjd29vd5ftwejz44rt9vqe5ez2ext9tqwuu2399ck52mch9q9lq8fyp9ppu0y04y09fq8gmu283etvskhcc9kz0zfv95zupt2s7x7dgn53hr4vgq3f2ekadkw8mp8e3pnhtfcrpjd93euer7uxqh3mjur78pzdwrrvxy0xr2andmnj8nwsa0qjkxeq99dqpdaxqe2jc99h6s5n0h7dcnmfm9uuaxpm84fq0tzjqmk9newrpsvuwry0jjvplv02zva20vh2s9jjrxxq3mpu8ywj8ufzalmuv4q0uphym4fp8eg9ukgk56mep52tdt4u7yz0sqy3delgk0pvd4gvfea3h5e4msv7uvyx6v07qelm2kpj38dj9rca0lpqa0wfzp05fvruh9fmgphxewj8xgx3rgmsrf2a4yn4mcs6ddkp2yc7svu7w80cexezg82qx5tdcr9wmxdpcxnsn82y8fkk95fphp5zvcyffnhm6pr2d04ww4vq9zm9j32gy898ce0ga5psj0y63u2gs62ekt5tp8s4h2yz04nvaqluc2ppaf5yaygx9lxketh3v7rwp397g30nmywg5sd0gd6cprpydf3x9pte3mx4h5ptuvtzyl82df8qvcfsdrvx8n8nafasf3h5rjjnjjp69eyw8qp30ydycj3d2lsgfky2vr873yvjmmuws95v9a43f4qd28w2p6pgaua3kf86alkmsyllljj7hnxezrz6fqapggrzg4vhazr82xvcp0k4erz6dzqrn95n6ueryap0vwxtq2e2qmmfev2w6x8630r3gqlj22ypgllm7fw5e9ql0l09l0g39v8un2gw5yvzvmqjtjcsxdp2le3ztkswgg0hvyeuqvf930xlxe9dwdtzcf0hygs9mcsdpwgu493vtljkzssqnkrh5evm2ycv8f0dz9z84cm0mnzjzgw9z74jznsdr7y77285d3svrgwg3d7essz4f5zhh2q928qmzfzj0m0w65kyda5hm6t5hrgywd3ajhfcm22qleneuxxt7u52u5asg8e9lx2lme8lm93f5cdw4gvcey4fql7hztg5cmq3l0
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-06T11:13:00Z"
  mac: ENC[AES256_GCM,data:6dU2JlxWye+u3NQ9YSo2eu2A6w3pZkisys3XxmBWnUl28fGO85uJdsfadL2NMrnyqowfDLVLXiyvCTDZn9B3gPC8odKCJuNRMT+CYKUCPj7M15fSwbdY5ZcdYKDKrYdQfzKayErnzTf8aWpC7iO2hX/WHFPYeGHyaU8tea3wBjs=,iv:VXqnMaFnc5JxY1E3qD5i2dmXGZDgHtQHD4Itdw5qK44=,tag:cIjtXnBxs1zDHH3fBTh9kw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
