---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: database
components:
  - ../../components/sops
resources:
  # Flux-Kustomizations
  #  - ./cloudnative-pg/ks.yaml
  - ./dragonfly-operator/ks.yaml
  #  - ./influxdb3/ks.yaml
  #  - ./pgadmin/ks.yaml
  #  - ./plugin-barman-cloud/ks.yaml
  - ./valkey/ks.yaml
