---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app tdarr-node-arm64
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: tdarr-node-arm64
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    defaultPodOptions:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/worker
                    operator: In
                    values:
                      - worker
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - arm64
      securityContext:
        #        runAsUser: 0
        #        runAsGroup: 0
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
        supplementalGroups:
          #          - 44 # video
          #          - 125 # render
          #          - 105 # render
          - 568
    controllers:
      tdarr-node-arm64:
        annotations:
          reloader.stakater.com/auto: "true"
        replicas: 2 # Set to 2 arm64 nodes. Tdarr free license limits nodes to 5 maximum
        strategy: RollingUpdate
        containers:
          node:
            image:
              repository: haveagitgat/tdarr_node
              tag: 2.96.01@sha256:a24f19274a9862df73033997c15f69e7c473252bc8aeed789b2c09aa24a81414
            env:
              TZ: Australia/Melbourne
              nodeID: kube-node-arm64
              serverIP: 10.200.15.242
              serverPort: 8266
            envFrom:
              - secretRef:
                  name: tdarr-node-arm64-secret
            resources:
              requests:
                cpu: 100m
                memory: 64Mi
              limits:
                #                cpu: 1000m
                memory: 512Mi
    service:
      app:
        controller: *app
        enabled: false
    persistence:
      cache:
        type: nfs
        server: ${NAS_IP:=temp}
        path: "/volume2/piNFS01/flux-cluster/tdarr/cache"
        globalMounts:
          - path: /cache

      movies:
        type: nfs
        server: ${NAS_IP:=temp}
        path: /volume2/piNFS01/flux-cluster/media_new/media/Movies
        globalMounts:
          - path: /mnt/movies

      output:
        type: nfs
        server: ${NAS_IP:=temp}
        path: /volume2/piNFS01/flux-cluster/tdarr/output
        globalMounts:
          - path: /output

      tv:
        type: nfs
        server: ${NAS_IP:=temp}
        path: "/volume2/piNFS01/flux-cluster/media_new/media/Recorded TV Shows"
        globalMounts:
          - path: /mnt/recorded-tv

      other-videos:
        type: nfs
        server: ${NAS_IP:=temp}
        path: "/volume2/piNFS01/flux-cluster/media_new/media/Other Videos"
        globalMounts:
          - path: /mnt/other-videos
