---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name selfhosted-test-pem
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *name
  data:
    - secretKey: private_key_pem
      remoteRef:
        key: Github_Selfhosted_Runners
        property: github_app_private_key
#---
## yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
#apiVersion: external-secrets.io/v1
#kind: ExternalSecret
#metadata:
#  name: &name cortananexus-bot-pem
#spec:
#  secretStoreRef:
#    kind: ClusterSecretStore
#    name: onepassword-connect
#  target:
#    name: *name
#  data:
#    - secretKey: private_key_pem
#      remoteRef:
#        key: github_cortananexus_bot
#        property: github_app_private_key
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name docker-hub-token
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *name
    template:
      data:
        DOCKERHUB_USERNAME: "{{ .username }}"
        DOCKERHUB_TOKEN: "{{ .DOCKERHUB_TOKEN }}"
  dataFrom:
    - extract:
        key: dockerhub
