---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name webhook
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *name
    template:
      data:
        GITHUB_WEBHOOK_SECRET: "{{ .RENOVATE_OPERATOR_PUSH_TOKEN }}"
  dataFrom:
    - extract:
        key: github
