apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:IqL8tryjtFGKvtJqDRpA7AiwBkAvwutAQW24W55XRET5IN7v6DUJxPLXjaElDkapPSbp9umUUk8S2u7bardyHoI3LbSdQlPBokxyME4U3Qwe2gLK0648A4TeQjzJga/9wV+gGEb6JLsDrgcxMUB3X/gnzRgL1TyV2VOZsQ2go2PDM6xuYQQQG1OLsXoSuPWtoXXzC97D/m9pL8A3hSkqd7oO8ONiCxc5OtVt0EGT8MH2kFkx,iv:n8Hix60fTzAMyKy0U2ZuruLobNS4aveCxynseg8uRbk=,tag:nyiARi5Tmqwu8uwVIE2R0Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGdFVUc2eCs2
        cXZZd0ROZS90ZlBUcmRYeUp1bHd2KzVCbFFISHFucjFFUFZkcmtGTTFrVUF5em5D
        SVpLK2dDL01RNmlJWUhGV1NsS0Z5UzRxazZIaHB4bjlkMjNId3VhY0NEaERpdGtt
        Qms3THZvcG9yS0cvRHJuRm9xcTB1U05UbVNXZ2xscG1uWFloazNvTW9DQzlUYXUy
        K0dVdjRoYlQ3T2wvVm0zUENYOUgzcVVSQzZBNHdLU0htdWpXMys0d0U2cWNMU29Z
        OHErYXJ0Z1I4ZXgyRldWMC9MZ2ZGUDFBTXVReWRHL0RwbEI4NzRyWDhBNkRtbHZl
        TmJLb2RQMDhUa3pjaXQvOUM1bDJBUk8waFVZa3hoSXNLcXBwRk93RFd2WENMbzJ5
        SWZuRVByZHVPZWhsU3RJZW0vRW5qSVptY0pGMnhET1RyT21xb25PTVpzdE9SeVR6
        ak5wamZRV2FWU1RkM0V3V3JVOU5wTHFnTit5Vk9lenlCeUxicFVNbzFsaFRaUFpy
        YjE2RXN2YWVPdURlekNQaldOTUJhVEllbzV0Q1dmVjVPUW1nYWlSVjBKSTQyZUIr
        cnVDVk1XMmhQd0t0WnpXYmZqd0kvNzc0YlVCUmpLdE5PcUFwc0ZiMmkyYXVxcStq
        MDZFTnJDb1lFNXNjMGhraWxvU1JyTlNRakUxMUUzUDk3Q3FLa3lqcFRHR0Nodjhr
        OEc1YUxPOGQvbEVoNVYxSlVMVzZQUDQrMDFmUWNrdG1DaGVScVdwSlJURHM0YUhh
        SDFSTHB6T003VWRXRm5qRHJmOWY5cXFMRm5GZjRCbXg0czVkV2cxczNucGlacFlJ
        Q2lYdTBZWE9qN2JUS04weWxlQ0REOHJxV0JnS2ptRk5YV0diRnZXS3VwY3pWcGJh
        b1RpQWx5TU16NjF2WjFmZTA5aWtvNE41SFpJSkFMYkVRS3V1eVRmbFNNb1duZklm
        aWpTZ3hkUUNxSDlhaDhpd0FNd2VLMDhDakE3SmxnL2dLQkxzTWxnNWJnd2phdC92
        Q3JzdkpUMHBwVlF3MEtZZlFFWkJtNHYvZFNsNDdtRDhBcjlrWVRCQ0FwTW1IUzRF
        YW9VSnNscGxMRDRIbGh1cTB6cmFEeE8zK1U3UmQveXRnQ2MwQnB5U0E0QU9VRjFW
        TllWNVR6Qm10MzZrNDNiSS9XUzhwMmFZWUxvMW1jTU04OVNpTjhOTXhUbnhPaWI0
        YWhqNEdLNE9VTGdFNnIrY2U0WEx5YVhqckRWa1VhNkJNOERjamFjU3ZTamNYUXZR
        d2lNR0dDTTBmS2Z6Mk1nRmxNWUdsaTIvRWM2Sk43QnJSREx2QS9yUHJLVTczVEps
        QlhnMFhUVnU1N1dpYUtSdWNTa1pqOHZwbncyZjNxWE4xTnZVRERhcDA2L3VLdzU3
        b3A1TXNlcFpERkRZMEQzMlNDZjdhZldTdGVjTkJaamNFcENoU3I2UEdXZC9MeU9h
        Nlg3SDRoZmdjSHhZaitrVCtPZmkyeEs1UGZiR1ZPOXV2NEQrMUJqVCtSM1E2ZTJp
        N0QzY29wbWRCUjdTTUt1d3V5U1FtM09jWENjQXFqR0VuT3FkV3NsSW4yazRRRVJI
        ak00RFFYMjUxMnlMZHhaSmxwMVJGeUdBTUtKTGFNSlAyUytDQTN5L2c5V0grTzhq
        bmtZUURZQndzaWdFakZDS2QzeU1XZ0R6WVNtY2xKNlRYcS9vMCt3M0NyLzlkUHk4
        cVRTandHRGZnQTZacHlLNEZBQmdpaENoc09ob2V4eURMcUFQcnhJYXlvUHRTTm51
        RTVsMHhpKzhXZ2lNUmZhaEdJS2wybFY3cTdoQmppUE5XOTJjZVZqbkpXVzBrQkdw
        bWFOcGluYWUrSnpGWElGak9mK1FZMVE3bFRXWGpZSmdLWmdhSG9MQVNjdFNOckNT
        c0k5MG00OHFuVVR2RHdFU1YvTkxaRFdZYmFLSFdpd3RyUUVsQ2lXZ3BOSXNldwpa
        OFVjK292K0h2V2ZVZ1BMME02UDBPQmxuMjVRcmJ0SHhwbGc5bkpyWEY0Ci0tLSBB
        ZDVTY1N6TksvU0l1ZHd2anAzd3B6Q1Zva2tIMkxOdGtnenpaR1R0Y3lJCu1a0Z/f
        aCfjkWZdHKQEZdaBGwkXnrBXX8ot3pWv0BP57XX8xX6ycAUwBOTvv1AoQk0G3FSW
        4jVtAIH7C8ublq8=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq13kgy63cgnvwlckua679c7jrant6jc932vc78zaejqatgh9ee2ys6yal5hsm0jdk9cl9vvyak9up8hf92sjwuscaagp6tvj5f20tn09k20nspt2ray3m7pnxrwvfc5j2md7esds275dpv2zeryjjh6w5mfzdppf9vjzu5p9v8ty7r338r8cndw4h4rpehyysjk828fqk9ga2543rc69jwenxywmnp76tmwcasz0s45wck7y5nyc52smhe3r84rv7a4zl5zg40gv4k5er5vw26c8cd73prkcnskpgpgqltqe75jf3ecfdpwp9sul38g8dsf6geskzrs3awtf36agxxz6aed4r3znqc0sdnfyuhezaflkeqjc69f3nfqcnrqfj04t4x7esq3w6t54rwp297m4zrpadqn3e3ch4rdwacc6j6dxdewzy8dk9qhrxdxgz07spcx44nwq45y72vsrje3q2wsmxnwxmnu8upq3nh34st2a3vqdkzafuz6sq49urmpewxnfuznyjpekp0yduzar3ssucegcapdjjqnrz7ckdv73c5ktksxt60txznpvap8jf2qg76zjyvn9lyd2sh67zvfvmzljv9e9pf98mh8s4xkg28m6r59hv2k59gktmynf47y99eg34rgx8xpeul4jwpkz7mvqe92cz25llpzy7s2enatnyv0323q6xz9fs3c47d2a0gc44w6m90fjgtl4uu8ywcv0s4m9gmx23e2s3kl8mfz5zfx9na39l9l3zvxuvme5pyvl7svnq7z89mx2fa8qzjv8wenhdyzg98hpv6x3my74s5u8p4ng3wsf8f56kzkvd8nvayz4zsqucrc8x2mzs5fhpjyjd29vd5ftwejz44rt9vqe5ez2ext9tqwuu2399ck52mch9q9lq8fyp9ppu0y04y09fq8gmu283etvskhcc9kz0zfv95zupt2s7x7dgn53hr4vgq3f2ekadkw8mp8e3pnhtfcrpjd93euer7uxqh3mjur78pzdwrrvxy0xr2andmnj8nwsa0qjkxeq99dqpdaxqe2jc99h6s5n0h7dcnmfm9uuaxpm84fq0tzjqmk9newrpsvuwry0jjvplv02zva20vh2s9jjrxxq3mpu8ywj8ufzalmuv4q0uphym4fp8eg9ukgk56mep52tdt4u7yz0sqy3delgk0pvd4gvfea3h5e4msv7uvyx6v07qelm2kpj38dj9rca0lpqa0wfzp05fvruh9fmgphxewj8xgx3rgmsrf2a4yn4mcs6ddkp2yc7svu7w80cexezg82qx5tdcr9wmxdpcxnsn82y8fkk95fphp5zvcyffnhm6pr2d04ww4vq9zm9j32gy898ce0ga5psj0y63u2gs62ekt5tp8s4h2yz04nvaqluc2ppaf5yaygx9lxketh3v7rwp397g30nmywg5sd0gd6cprpydf3x9pte3mx4h5ptuvtzyl82df8qvcfsdrvx8n8nafasf3h5rjjnjjp69eyw8qp30ydycj3d2lsgfky2vr873yvjmmuws95v9a43f4qd28w2p6pgaua3kf86alkmsyllljj7hnxezrz6fqapggrzg4vhazr82xvcp0k4erz6dzqrn95n6ueryap0vwxtq2e2qmmfev2w6x8630r3gqlj22ypgllm7fw5e9ql0l09l0g39v8un2gw5yvzvmqjtjcsxdp2le3ztkswgg0hvyeuqvf930xlxe9dwdtzcf0hygs9mcsdpwgu493vtljkzssqnkrh5evm2ycv8f0dz9z84cm0mnzjzgw9z74jznsdr7y77285d3svrgwg3d7essz4f5zhh2q928qmzfzj0m0w65kyda5hm6t5hrgywd3ajhfcm22qleneuxxt7u52u5asg8e9lx2lme8lm93f5cdw4gvcey4fql7hztg5cmq3l0
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-06T12:26:40Z"
  mac: ENC[AES256_GCM,data:YcwbJY29JVsfqCOqz8bmKCrHSuQCRjxoe3st8xnXjliEN1Md9824LUuTL0XedQZR1kty7FPNXL6x3Jspup6vlQZEKRTHFLo7D1aXbKX6Vx/jel2aCuvklIwKyl/vENnOzLjT2og5Mt/+iywpbo2Q5q8G3Xky8NaNtBCrxcnVkxE=,iv:N26X9/8N3TTnqbrTuCMfzM2Z0YPPu1t2TG252NT8DLQ=,tag:FVMtCA+KzYZXVqA+ers1Bg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
