apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:d16wriLGhP5lJFGE4hbUUcl90cUvNdWHrLTKLwJD2t7/zpFn3tmN1BVRtZ86M5QYhxwAl3Y7DOE1Rc9xx114JRpoIiGwejLysiNdjQlkkaL65dczsvsDyUeBgfGDzwjS7GeO8e24Lx5q6/cYkRcuT2Gz3TOSd/Xiyc1BnOwqM/jICNKnZ/s9Bkvvau9PVylbMDWt6NMnqo86P0zK/R0p5uAhBMtPRryBCIhMN8DmRIfU1Mg3,iv:G8MguFkKE4/iy9JCSzJm7KyUg2AEpnXA+dH0IRDAi6M=,tag:vMThoLKawB0swo9J49Tahw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFliWnB4YzNt
        WGVJcXNOK28xUGdMZUk5MGozWkpiUWFTeTFRdUcwdzZWNzVhaWtVRVNxV1Avdm1n
        RTlhTW13cG8xVHQyZEhiNmRMU1R6a1ozTXl1NDZER3AxVWpZa2RxNzN5TFJnMnRV
        SmQvSkpEb3RhM3FJOTB6dW9oaHdQQTE4eXBqUXVSNmRMTUhjK2dMMHh6Zmp1SXpy
        REhUbzRac00reEwzK0NyZnQ1bHYxZWVHTHNjSzh5bDBDZUxXbXc0TzdDNVNxbjFh
        Q01hOHJpRCtDemNwT01iY2hrSmU5Ykp6Rk1aNnRMQlQxQUtUNENicWhHaktjbDEv
        SE5lTlRBTVFxajlaeVVEOTF2N2s5NkY0SndsRi9ORldvQ0s2bzdyZ2VvdDZpSXhw
        aFJnMC8wSllKbXFaRSswUG1LZ3VwM2p3MXdVemlxUE1ITlRXWDZnUFJTam9RVUN2
        RG1xTG1wM0RkaWE5eHhqMUdQVTFkMEVlR0xNMi9reHoybHRuR0xtTjlxSjg0bG5S
        RTJwUW9OUVlmOGNkN3NSTElIck9qc0UvRWR5VlB3NHowcHMrY1BMdlkvRFc2THZP
        NGNFSjdzYU1YYWozVlV4NlFzM3hmK1BnNktXNjNNNmhseEZnR1IvMk5jQkJ0SHBV
        bUhVNUhHS1lPQTJ6SlZjZmx2ZC9oeGlCNDB6dVZibjVPSVE0OW5nQ1drMzJ2REla
        Zkg0cU1rWFVKS3lNNXdORTJMS3IvSEEwNTNwa09KUDhldUlWMTBPS0JDZEtQQmt6
        K2lEVW1OelFqbEV3OVZnMTAvYnQrTjU5T3kwU1RnYW1FTmJoUE5WRDFVZk5MSUhh
        cklPNHo1Y1ppQUVsS01GTXQ3MmdMS3VhcWI2OWN3RTY0K2ltTjNoZEFVK1FTamxy
        aFZqay9ueEl4N0d0ZWg2UENwU2F4NDVwWGlQdzY2ZG5raG5MTDdTeW00S2o5d1Bh
        VmxtYWF5WTN5V2hzNDFEaEIxZFN0T0ZmK1VFK28wYUV1M0w0VWd2bWlrQmpWbVdF
        akRmRVZuUDRJNG52a1cxWkhlZWRrNVBQbSsyTG0zN2F3amJJY29Ua0o0KzZOT2Ev
        VTF5M0ZjU0dDdCtzMGdmNEVaR0F3OE8wdE1RSDhWTGNVeUVPSVk2U25hOG9YZzNm
        MnIwVzlhdzJJM0pIbklXUzFDOGFDcGQ3cjRYcXBVOWc3VmlOWUpoTjF0QWlPeXZh
        dE1PTUlUd3d2djBtQXI1bnBJaFl2Z2NiTTZNUVdkRm8zOUhHcnI0VlhOVkRYMDEr
        Vk0weGhmS0pVdlNzdmdFdFI4SDBwMnNoTERaNnFkWEFaNXk4WXoranQ2cW9XZ2Zk
        L0JQWDlIRkE3L2tXeFFtTjlaSHhMaDFycGp5N0hiKzkxSUo1LzBGdUZIVzhVdzc3
        UnRlWkRpaHA2OHlaOEZ3d0ltUVZRTlg5VkxUMUNxa0ZjcnNaZWtFNEFETXJDNVVI
        MDhsZXhacGZlcFNjWGtyQ242bnFrUDVUQWZuamt6M0VIKytzVjQzMWxhZEt2dWo3
        TFBpOHFGZGwzeDN5bkxhQXpuTjFvZnVvWXhMNWlQZXRMR3FDZ2lnWmFFR0tiNk1Q
        ZFJBTm84NVBrMUxTcHdPb3h2SHVSWURxTjVYalFoblZidExrY0d0MVpuOHZ4bWtk
        dk5rbS9BL1JJbEtmTGoxcVJLYVA0cnZjNVFpT215TVFLTm56dkZjUFNyM0U1aGF1
        UlRMN3lyOHFyMVNEVFdocXE4a0phbWtZOGxTK2pQNkliNW5WS1h0dFlQcTllMWxD
        TTBXbEFuMmlmcVRnakJMMkVhWUtmclZZVkorU1ZiQ3JyUjVmRTVJUUk4ZHREMXBh
        UGRjNUJNY1R5K3NmaUZUb2RnTXZiKzRBTHFFeVMzenF6djFJdzVmQkpnRTYzMnpa
        Vlp4emdYTmYwNjRHQUtqRlNyODZkMkRta0R3YVQzblc4UUhqbVlmQ1FkMEJQdwpJ
        bkxIV1d1OVJFUzZVNE9KUytMMUxXcmVOdEljQ0VrMXE5cFdKV25CNjVZCi0tLSBH
        MkpOckFEZnhFRC8yUHJnYjdZM1V3L1FNdUtLSDBOMDZnZzdCUUdaQTZRCsNLRUQs
        3YhJ61FeFCmPhnx5EWMAbHn+46A4dguFr9QsOYEHc1UUMNmolrr3Wd9a3hOVBp0w
        R1wTL60aLXZRTyk=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq13kgy63cgnvwlckua679c7jrant6jc932vc78zaejqatgh9ee2ys6yal5hsm0jdk9cl9vvyak9up8hf92sjwuscaagp6tvj5f20tn09k20nspt2ray3m7pnxrwvfc5j2md7esds275dpv2zeryjjh6w5mfzdppf9vjzu5p9v8ty7r338r8cndw4h4rpehyysjk828fqk9ga2543rc69jwenxywmnp76tmwcasz0s45wck7y5nyc52smhe3r84rv7a4zl5zg40gv4k5er5vw26c8cd73prkcnskpgpgqltqe75jf3ecfdpwp9sul38g8dsf6geskzrs3awtf36agxxz6aed4r3znqc0sdnfyuhezaflkeqjc69f3nfqcnrqfj04t4x7esq3w6t54rwp297m4zrpadqn3e3ch4rdwacc6j6dxdewzy8dk9qhrxdxgz07spcx44nwq45y72vsrje3q2wsmxnwxmnu8upq3nh34st2a3vqdkzafuz6sq49urmpewxnfuznyjpekp0yduzar3ssucegcapdjjqnrz7ckdv73c5ktksxt60txznpvap8jf2qg76zjyvn9lyd2sh67zvfvmzljv9e9pf98mh8s4xkg28m6r59hv2k59gktmynf47y99eg34rgx8xpeul4jwpkz7mvqe92cz25llpzy7s2enatnyv0323q6xz9fs3c47d2a0gc44w6m90fjgtl4uu8ywcv0s4m9gmx23e2s3kl8mfz5zfx9na39l9l3zvxuvme5pyvl7svnq7z89mx2fa8qzjv8wenhdyzg98hpv6x3my74s5u8p4ng3wsf8f56kzkvd8nvayz4zsqucrc8x2mzs5fhpjyjd29vd5ftwejz44rt9vqe5ez2ext9tqwuu2399ck52mch9q9lq8fyp9ppu0y04y09fq8gmu283etvskhcc9kz0zfv95zupt2s7x7dgn53hr4vgq3f2ekadkw8mp8e3pnhtfcrpjd93euer7uxqh3mjur78pzdwrrvxy0xr2andmnj8nwsa0qjkxeq99dqpdaxqe2jc99h6s5n0h7dcnmfm9uuaxpm84fq0tzjqmk9newrpsvuwry0jjvplv02zva20vh2s9jjrxxq3mpu8ywj8ufzalmuv4q0uphym4fp8eg9ukgk56mep52tdt4u7yz0sqy3delgk0pvd4gvfea3h5e4msv7uvyx6v07qelm2kpj38dj9rca0lpqa0wfzp05fvruh9fmgphxewj8xgx3rgmsrf2a4yn4mcs6ddkp2yc7svu7w80cexezg82qx5tdcr9wmxdpcxnsn82y8fkk95fphp5zvcyffnhm6pr2d04ww4vq9zm9j32gy898ce0ga5psj0y63u2gs62ekt5tp8s4h2yz04nvaqluc2ppaf5yaygx9lxketh3v7rwp397g30nmywg5sd0gd6cprpydf3x9pte3mx4h5ptuvtzyl82df8qvcfsdrvx8n8nafasf3h5rjjnjjp69eyw8qp30ydycj3d2lsgfky2vr873yvjmmuws95v9a43f4qd28w2p6pgaua3kf86alkmsyllljj7hnxezrz6fqapggrzg4vhazr82xvcp0k4erz6dzqrn95n6ueryap0vwxtq2e2qmmfev2w6x8630r3gqlj22ypgllm7fw5e9ql0l09l0g39v8un2gw5yvzvmqjtjcsxdp2le3ztkswgg0hvyeuqvf930xlxe9dwdtzcf0hygs9mcsdpwgu493vtljkzssqnkrh5evm2ycv8f0dz9z84cm0mnzjzgw9z74jznsdr7y77285d3svrgwg3d7essz4f5zhh2q928qmzfzj0m0w65kyda5hm6t5hrgywd3ajhfcm22qleneuxxt7u52u5asg8e9lx2lme8lm93f5cdw4gvcey4fql7hztg5cmq3l0
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-07T03:14:23Z"
  mac: ENC[AES256_GCM,data:vrxkBQzScJsH6abAktCkz3ASK8jbKoBGMY0gZ3w8yeAw/8GsU7vo46LUS3ijXJ+nuyhey8yQtydgBVX9ozu94SHP5Turungwuue+lTf5lrDiVMBOuKWrFarMCjgu7LZ24DZsJCDXMJKRE4p0wDdxsoH0IwTRTnlJ5WYumia9zoc=,iv:HcR05G8PnmLBJUjMZFo6wobhd/F/q+w3X8mstAqyWU0=,tag:PLJKFL5uQu+9L7wYPUzsEw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
