apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:0RwI7FS/asG/DGWxrumcSqDRyoUFNLpZy2D0wxKMZLLwjSgcbHNwf1fAuacrnctdboCO0ZvZW1Mw8IUIX8mtwlfo5dRhTQ2JSMEM8kYa00dH89mYYLYen4pcUgxtecXlokLoXqxSko4ujM3xan9bQTWzLwlEaZyraPouUMfrEfmg/BLyK1ggshMkay5T3NCiemSMAUQY9tgNN7OtioSymFUS+dcEwMpJD1hCg+dhYcVAuBMZ,iv:4MG0B1yqC0U0UMdCR8o3wdYz+FbY6M73XVIpcSNX5dE=,tag:EvzVvHiv9BLdx7gOeRgjkQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFdtNXoxZmxS
        R3lQM2JCbUZMd2ZaOHNMNWZTQUlHL0Fvd2tPRTQrKzVHNytUWWlWMS9rdHc4eHll
        bU16UDk1YW55dWRQT291VW1Ca2crN1hwL3o0OTZxeUR1aWFwQjR6NkpINE5Jb3F5
        c2ovMWlHNlgrMzlMWDh2ei90dnBpNVU3dGVQVE10Wlh0YlZyYUkvOVA4eFVMd3NS
        ajFyak14d3llRktUWVVDdkkzRFZ5bE8za1VycG1lWXc1UjlLaWRCYVcwODgyeTNz
        dk5raTNoQXBFVGRNWEhEd0RNV3F3T2VZdDlVSkI1bG5qR2ttOUV4bG1lNDVWMFo2
        Q1hGZWJOMkUzZ0toL2g0Y2c0cGVOL2kyL1lzL2NUZmhqeVlkeWVCdnVaSU5uVE9l
        WXZodmJiVTE0WUd4WU9INFRZeFM0Z3dwZ21td1FwdHdNeVRnQ3RsNyt2WnBIZ1Q1
        WVMxSVhtM2xsNzBBb2tQMFljSzlOZlBDM21ZQ3ZzeDQ1czdKRjBCclpFMHFlK0I0
        cS9ab3dvY3R5MWpyS05kZHp2T0c1Z21zcjd0YkFleGRSR2Zab2pNY0VTOUU0VnR2
        TnhSandrdVhNS24wTnVzTkFYZGZreC9JS01DTUJmSjFXTTFqT0JLY0k0WDNVS01D
        TEJVQTVWK3lhQnZmenhUQWhGbVNUSzloVlVhanVWOXhHMkNxeGFJdko3ZUIrQUxQ
        eWxGYUhEelNlSWNBcTJDWVdRVGpXdFFqOERVSm5GSHkyTWdTdHhmRW93KzlrQW5x
        L0pac0YyYy9QemZ0Z1dlVjEwYmpGL1UrR2c1aVJadkxqQTJFcVZpd3R1a24xSmZF
        aTRQZWVlSSttVFFpRVFuZEpGc0tna25qNFVYS3JHbWFxNWxWUHpzTml3ZUdGVitI
        MHl6NThWanRpR0NWZmhzMkJoRTNzMFJNYmh0WDRycWNXSTJhYVdOTlh0dFVTcGNv
        T3ZBdmxOdWlsdmJxZXdvQWZSSUpOeVJzYXZENzdIbFh0YW9kb3FoR2UzK3dHZ0Yv
        WEp4NnVFZzk0ZzE4VU1zME9RRlZ2UUhHWW5xQ3FFcDNTQjhQTzVWa1g4amFuQ25o
        QWgzdWFTN0dxQUt5ZmU3NzdCZVVLeXltc0dsdFpaWWd1b3c2aGZSZDdsM215SGVx
        eW8vdGJ6S1lxT0ltMkl2ZDR4V0hVR0Z0NG9HWE9ibENpY3NicVFTR0NubWRvem1X
        Z0pRRDdaUFBIZW50VzdWSUxSMHF6d0kzVUtxQlBsWm1CVkNMNlBMdXV3bjh5Q1Zu
        Vy9hSjVxSFBOay93K04xU2pyMXhzMTBmZUswaEY3eDdMZDQvSG9samtLbTJ3VjRw
        ajc4M3RzVEVxODl4aloxWFBMdGlhaDJMcEp5Z3lSaWl6SWN6S0FkR1FvR3dXc01S
        K2RvUmlETWFNS09YYzY2VURBSU9ITEo1ZDhXR0FFU08rWGVYSkliR3VoK0FUdnpY
        dW9kMjBRNGlWeThQUGExTHkrTzZFYkZwNGhxN01IQzNaOTNFZ0xHajZQQVM2cHlU
        NFhudm5ObUduQW52cll6YzhkL1FFYklGL0xGTjVqUXNZZnJ5WnN1NU9aUUZOQmVo
        djFETGt6djNYaWNqbk5GdVdwdEphVWxFekl2alFYaE0yeFlkSm9RVmRzZDVURU5U
        TG45d3ZWaU5WYzJlRDl0bUFwR1B5eW80djdna1gyNDgvdmxxVlJsN3Zuelc4cUwr
        U0xiSGMycDBuQ0wwRkIrU3pyV0Y4SjBabnhwdU1WK1g0Uyt3b0daQTlGczJPRk9R
        a01HVFF3Y0owVEtIMkhVV2E3RDdPWWI2YUxSSDJGVVZhV3Z2bC82ZXJUM3Yza1p2
        dDVhMnk2QkQzdkFSeFh3NDdncHJSUjlkU2ZKeG1mZlRIb204SXB2Wmh3bHpwSUla
        VjRwbnFjYkhLREdLWlU0cXk3YTU0S1F5MmQrbFVmK1lhUVpKYXMrV3FNWG5hUQpM
        OU9WU2pIWGFub3BzdVRDaHVRODdHTk9NVytKZU9acFlZNUl5NytCN3JFCi0tLSBH
        d3Z2alBOdWhDUzkwcXRERFhvWnIyVGU1WTVjaFVhQ0dJd3pSb2pxM1NZCmQsdZ2S
        Q8obLG5hjfqOzd745A2ZWSVn00iQYmEAr3aMJrh/+mRMT4SOqffE/AK6g6CDFJkS
        QDNOdv70bIU/46k=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq13kgy63cgnvwlckua679c7jrant6jc932vc78zaejqatgh9ee2ys6yal5hsm0jdk9cl9vvyak9up8hf92sjwuscaagp6tvj5f20tn09k20nspt2ray3m7pnxrwvfc5j2md7esds275dpv2zeryjjh6w5mfzdppf9vjzu5p9v8ty7r338r8cndw4h4rpehyysjk828fqk9ga2543rc69jwenxywmnp76tmwcasz0s45wck7y5nyc52smhe3r84rv7a4zl5zg40gv4k5er5vw26c8cd73prkcnskpgpgqltqe75jf3ecfdpwp9sul38g8dsf6geskzrs3awtf36agxxz6aed4r3znqc0sdnfyuhezaflkeqjc69f3nfqcnrqfj04t4x7esq3w6t54rwp297m4zrpadqn3e3ch4rdwacc6j6dxdewzy8dk9qhrxdxgz07spcx44nwq45y72vsrje3q2wsmxnwxmnu8upq3nh34st2a3vqdkzafuz6sq49urmpewxnfuznyjpekp0yduzar3ssucegcapdjjqnrz7ckdv73c5ktksxt60txznpvap8jf2qg76zjyvn9lyd2sh67zvfvmzljv9e9pf98mh8s4xkg28m6r59hv2k59gktmynf47y99eg34rgx8xpeul4jwpkz7mvqe92cz25llpzy7s2enatnyv0323q6xz9fs3c47d2a0gc44w6m90fjgtl4uu8ywcv0s4m9gmx23e2s3kl8mfz5zfx9na39l9l3zvxuvme5pyvl7svnq7z89mx2fa8qzjv8wenhdyzg98hpv6x3my74s5u8p4ng3wsf8f56kzkvd8nvayz4zsqucrc8x2mzs5fhpjyjd29vd5ftwejz44rt9vqe5ez2ext9tqwuu2399ck52mch9q9lq8fyp9ppu0y04y09fq8gmu283etvskhcc9kz0zfv95zupt2s7x7dgn53hr4vgq3f2ekadkw8mp8e3pnhtfcrpjd93euer7uxqh3mjur78pzdwrrvxy0xr2andmnj8nwsa0qjkxeq99dqpdaxqe2jc99h6s5n0h7dcnmfm9uuaxpm84fq0tzjqmk9newrpsvuwry0jjvplv02zva20vh2s9jjrxxq3mpu8ywj8ufzalmuv4q0uphym4fp8eg9ukgk56mep52tdt4u7yz0sqy3delgk0pvd4gvfea3h5e4msv7uvyx6v07qelm2kpj38dj9rca0lpqa0wfzp05fvruh9fmgphxewj8xgx3rgmsrf2a4yn4mcs6ddkp2yc7svu7w80cexezg82qx5tdcr9wmxdpcxnsn82y8fkk95fphp5zvcyffnhm6pr2d04ww4vq9zm9j32gy898ce0ga5psj0y63u2gs62ekt5tp8s4h2yz04nvaqluc2ppaf5yaygx9lxketh3v7rwp397g30nmywg5sd0gd6cprpydf3x9pte3mx4h5ptuvtzyl82df8qvcfsdrvx8n8nafasf3h5rjjnjjp69eyw8qp30ydycj3d2lsgfky2vr873yvjmmuws95v9a43f4qd28w2p6pgaua3kf86alkmsyllljj7hnxezrz6fqapggrzg4vhazr82xvcp0k4erz6dzqrn95n6ueryap0vwxtq2e2qmmfev2w6x8630r3gqlj22ypgllm7fw5e9ql0l09l0g39v8un2gw5yvzvmqjtjcsxdp2le3ztkswgg0hvyeuqvf930xlxe9dwdtzcf0hygs9mcsdpwgu493vtljkzssqnkrh5evm2ycv8f0dz9z84cm0mnzjzgw9z74jznsdr7y77285d3svrgwg3d7essz4f5zhh2q928qmzfzj0m0w65kyda5hm6t5hrgywd3ajhfcm22qleneuxxt7u52u5asg8e9lx2lme8lm93f5cdw4gvcey4fql7hztg5cmq3l0
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-06T06:53:07Z"
  mac: ENC[AES256_GCM,data:RHs0k6B5ofNHSQV8nPmVsgmFjbZx1Jx2FJcTtqG3Qb+9HT50HgVfUQSnhkQuck5s9VVwZbUQux4vs7mMdHoZWqK37MVGNmiSbBWE725M7Yc8JzmiQa85IoZbNEoPbr9ZINXBFCgS+gn+SxIH8cGhFNoHJGxr4nEksnm3wxkqsMg=,iv:bFLHhWgpCrGFTDxNA9KvXQoujqCfgT+TvoWBHRn5VMU=,tag:3aaNpcNWPy9kSw+DAuBPQg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
