---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: actions-runner-controller
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: gha-runner-scale-set-controller
  driftDetection:
    mode: enabled
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    #    affinity:
    #      nodeAffinity:
    #        requiredDuringSchedulingIgnoredDuringExecution:
    #          nodeSelectorTerms:
    #          - matchExpressions:
    #            - key: node-role.kubernetes.io/worker
    #              operator: In
    #              values:
    #              - worker
    fullnameOverride: actions-runner-controller
    replicaCount: 1
    metrics:
      controllerManagerAddr: ":8080"
      listenerAddr: ":8080"
      listenerEndpoint: "/metrics"
    podAnnotations:
      prometheus.io/scrape: "true"
      prometheus.io/path: "/metrics"
      prometheus.io/port: "8080"
