---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: actions-runner-controller-auth
  namespace: actions-runner-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: actions-runner-controller-auth-secret
  #    template:
  #      data:
  #        github_app_id: '{{ .GITHUB_APP_ID }}'
  #        github_app_installation_id: '{{ .GITHUB_APP_INSTALLATION }}'
  #        github_app_private_key: '{{ .GITHUB_APP_PRIVATE_KEY }}'
  dataFrom:
    - extract:
        # github_app_id, github_app_installation_id, github_app_private_key
        key: actions-runner
