---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qbittorrent-exporter
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: qbittorrent-exporter-secret
    template:
      engineVersion: v2
      data:
        # App
        QBITTORRENT_USER: "{{ .QBITTORRENT_USER }}"
        QBITTORRENT_PASS: "{{ .QBITTORRENT_PASSWORD }}"
  dataFrom:
    - extract:
        key: qbittorrent
