apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:JD3F0pieYjGVitF92z75ZqVlK7SQcqHmv17UpRWeuwwMqVssz/QnMw==,iv:WwBqzUDMKyPUlln1nl77LUIyrJX8MpuxSPkNDwOOV8g=,tag:MsGiZ+WXZcmTH+X4TFvUKw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IEpXbnFJaGFY
        YlgrZnYrdmFtZ1ZwUG5jYzFzSGVHNTNWSkwvRjdUTHNNdGZHcUlwTUl5d016VFpW
        WUZNbUQwcFJMMGdyR1AwOFUyMW1sdnpGcFhzblVSS05lbFROUmtXdDloalUwOEhX
        NnkySU1mNW52elpNVy9hSWdOV2JEZkxSNGdsVkdJTGM5WEJiREk0TFVHTVpJUkls
        dFVZNThwN2FDSHYvWXJhTmMwNFZKUExobHR0VUNZMnVuQnRobUc4a0dubmpUYUxa
        NUlaRWdmdTJwQ3Vwd2RESzNwSXE0MzN6TWdkT0Zna1FHQi9zUTBHSmhqMzlmdWp1
        R0NrQXUyZ05pQWZKZFMxdVFySkZSVFlyb25nY0JPMEJVY1Mva0xidENVWTdPQWg0
        TU1VRFNVbVBqU0E2N29oTEhDYWdUcFFjcXZyTkZtRWVSSVU2Y1FmbHNudnpsYzZj
        aFhNM1JSaVRBOThmRHN4Ty9ub2ZNY0hJamo3alY3QVhPMEk4WHlKbGZvN0lPK3hH
        TXdOOTNwMS9vYWZKT2QvSmFxN3U1U3NUUzNLdmZrZXd6czZIWXV1RTY4NFBEenBI
        alN4YnFCMnFFbzltcTYyTXo3WkwvUFpIamFEamlLNExJdis4ZldqMm5rc1BHOGFY
        bzRSVVBDQi9Lb2xMVEpnc2VUalV1YkRna3dhc3FISG5UNHNjZGI4ZUxyVUU5RnRO
        OXdsV2xyN2NLeE5iSlpJczE2cngxNHNTS0FaSEdMaCtRcUN2NUlaWGg5bXVjOVZD
        WWtOcWpjZDBXclYrR05KOTZGSXRiRXN1Z0d1a3VRcXNXdERjRlh2R0dTbmx0NFdX
        V3I4UkpxemxlTDQyOHBTN2wwWHowODJ3Vm1hYURzT3pOSGdueUw5TTJ0RUNmenlJ
        VVBRaU9SYThCUFFpZWxBRFJhdmVLcHBONWtuREV4UE5rdDQrbXN2SFVteVhRZUZo
        Zmx0eWlzRlNuaWZrSmFzNWtPR2VXNlVNYzdreEhYTUF0ZnpZQjdHMzlId0VHSFcz
        VlZqNEJDRmVtSUFLempac1FUa0JxVDNQZFEzNGFVc05oRXpuTTM2alFwNmdNZEdo
        dFFLckVxcnZoSlk2SkVjSFRWVTRMT3JVdTF6N3h3Ri9TNG5pVE95OXk5ZVZqbGJo
        cjFaeHk0dGRpSmRCMjdMSTl3QUhGRVVqSVFmZDh2UFNvMzJMZDU3Zi9ML0w0TnRn
        UERIYnpObmFqQTRSYlhNTmgyb2l0SXczUjIxVGlocEpvRitGTjRybmMxZ210WnVy
        UVgyOGZEZ01nSzZQRUgwSnd0T1phTW8yNmVxeXpVQ0ducmVpeWMzTlZOL09SV3V2
        OHBFSGRLUXVIaWdaQ3hyV3hiZ0RDNlJGMWVaMXFMVjRTdndMR25SVlJoaWJZMS9z
        dWNSdWUrNEIzR0Z3VEhIZUN2ZERwdWhwR0xqd3B6ektEd09QY2kyZktkdTh0UEp2
        Z0ZNaFpBZGlBNjlDMkJBcms0Q1U5WXExekluVUFySVBueEFqeUxXRHMzMFVvbHhN
        TzI2M2REN1VxUkFHTVo1SUhkMG5kV1piRjZmbW9MZmhUU2p5UnJMZkEvUmNuMmov
        RThjbmFBSXFxQ2paV1RNYWxvSVh5QW1lMUQzS3NvK1E2VXMvdHFuQlZ3bFRGa3Zv
        Q2NxOFlGdnB5R3IwUFVDV3UvVnpNNjBPVHBuN2ZzNDlVTWN1WUQ5SlZhczBlYVZj
        dGpvNlZJdzdkcW5zcXAyWHlnL3FJVnZpUklGNkIvMHEwdC9WQnl0bFpyeUtsV2Vi
        NmFSZCs2VHdPcm9iNkN5WURRc1V3QVJIZDRKdUJTTkppc3ZGc0R1dGZoWHNGSVdS
        aWxGbU16WWtXbzBqdUNBUlJyU25oU2RGRGRuYXNUN2xZZkEwenVyUDhseTVnb2JX
        REt0WHVxVzEwcnBVd0d5cVUrN1BEYmNmU1lMZVFGQmtmaEo1WnRZRW9RQ1dJUQpH
        dEhNa0x1TTVUMDFadWlPNUhtcUhIaXpCcXh4RkZhNU92RHNULzZLOERFCi0tLSBL
        emhhVG85RDhJNzZXRnhFQUtrWHBEanVOSHhnbGpzQjcrV1RtVEZ4ZjVVChy8KTrn
        33g1OY9x0QrAgex6mGnMx3wFDs4IG8mgzy+FDjvBNQs+ymsXkLhctjysBhQZfbH2
        Y9NOmlE9l85YaoQ=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq13kgy63cgnvwlckua679c7jrant6jc932vc78zaejqatgh9ee2ys6yal5hsm0jdk9cl9vvyak9up8hf92sjwuscaagp6tvj5f20tn09k20nspt2ray3m7pnxrwvfc5j2md7esds275dpv2zeryjjh6w5mfzdppf9vjzu5p9v8ty7r338r8cndw4h4rpehyysjk828fqk9ga2543rc69jwenxywmnp76tmwcasz0s45wck7y5nyc52smhe3r84rv7a4zl5zg40gv4k5er5vw26c8cd73prkcnskpgpgqltqe75jf3ecfdpwp9sul38g8dsf6geskzrs3awtf36agxxz6aed4r3znqc0sdnfyuhezaflkeqjc69f3nfqcnrqfj04t4x7esq3w6t54rwp297m4zrpadqn3e3ch4rdwacc6j6dxdewzy8dk9qhrxdxgz07spcx44nwq45y72vsrje3q2wsmxnwxmnu8upq3nh34st2a3vqdkzafuz6sq49urmpewxnfuznyjpekp0yduzar3ssucegcapdjjqnrz7ckdv73c5ktksxt60txznpvap8jf2qg76zjyvn9lyd2sh67zvfvmzljv9e9pf98mh8s4xkg28m6r59hv2k59gktmynf47y99eg34rgx8xpeul4jwpkz7mvqe92cz25llpzy7s2enatnyv0323q6xz9fs3c47d2a0gc44w6m90fjgtl4uu8ywcv0s4m9gmx23e2s3kl8mfz5zfx9na39l9l3zvxuvme5pyvl7svnq7z89mx2fa8qzjv8wenhdyzg98hpv6x3my74s5u8p4ng3wsf8f56kzkvd8nvayz4zsqucrc8x2mzs5fhpjyjd29vd5ftwejz44rt9vqe5ez2ext9tqwuu2399ck52mch9q9lq8fyp9ppu0y04y09fq8gmu283etvskhcc9kz0zfv95zupt2s7x7dgn53hr4vgq3f2ekadkw8mp8e3pnhtfcrpjd93euer7uxqh3mjur78pzdwrrvxy0xr2andmnj8nwsa0qjkxeq99dqpdaxqe2jc99h6s5n0h7dcnmfm9uuaxpm84fq0tzjqmk9newrpsvuwry0jjvplv02zva20vh2s9jjrxxq3mpu8ywj8ufzalmuv4q0uphym4fp8eg9ukgk56mep52tdt4u7yz0sqy3delgk0pvd4gvfea3h5e4msv7uvyx6v07qelm2kpj38dj9rca0lpqa0wfzp05fvruh9fmgphxewj8xgx3rgmsrf2a4yn4mcs6ddkp2yc7svu7w80cexezg82qx5tdcr9wmxdpcxnsn82y8fkk95fphp5zvcyffnhm6pr2d04ww4vq9zm9j32gy898ce0ga5psj0y63u2gs62ekt5tp8s4h2yz04nvaqluc2ppaf5yaygx9lxketh3v7rwp397g30nmywg5sd0gd6cprpydf3x9pte3mx4h5ptuvtzyl82df8qvcfsdrvx8n8nafasf3h5rjjnjjp69eyw8qp30ydycj3d2lsgfky2vr873yvjmmuws95v9a43f4qd28w2p6pgaua3kf86alkmsyllljj7hnxezrz6fqapggrzg4vhazr82xvcp0k4erz6dzqrn95n6ueryap0vwxtq2e2qmmfev2w6x8630r3gqlj22ypgllm7fw5e9ql0l09l0g39v8un2gw5yvzvmqjtjcsxdp2le3ztkswgg0hvyeuqvf930xlxe9dwdtzcf0hygs9mcsdpwgu493vtljkzssqnkrh5evm2ycv8f0dz9z84cm0mnzjzgw9z74jznsdr7y77285d3svrgwg3d7essz4f5zhh2q928qmzfzj0m0w65kyda5hm6t5hrgywd3ajhfcm22qleneuxxt7u52u5asg8e9lx2lme8lm93f5cdw4gvcey4fql7hztg5cmq3l0
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-07T05:23:29Z"
  mac: ENC[AES256_GCM,data:M5bWGmxy46ACNeqcHmLf250kjeNhu/zS1TqnazMm77sbCBxWdVrFuVGnm7HJs6NDHUgSmGvxTUsqwZmQ5ptbXYeqedVCYkgdYpS5GjiM3G9qYoyAJqulUv1nPjKc6o7/xAekfEo9mCYfRU/Nie/hwIVLdPn2dTV9a+3F1aIa3/I=,iv:4Q148JwsiwJnsCFhcW5tjBK7RbCFwGz2eHiOl1nzdEI=,tag:uBrOyPQVMi0uKHUj/sUH/w==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
