apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:JihFZWvThjHeOLqBplR+c4Uh3iR+H3YhmjaeU6C4qF+lcum6MdduYA==,iv:u2pAu2jVuAMjYk1TUlS4HLkjOb3QdFxj+FwhifIiEy4=,tag:6CcsQleGL0J0NSr3K9TQSQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFM3MUNYMWhD
        Ni9jb2Z3OTU4SFF5cXdMSU0vWVFMb1FvTitFamYzMDhpV09ZbTFJU3l1VThFbjNZ
        QjZFbnJid01HTEg4cUhpUTJBTkNDdGdVUzUxRVZEdGs1TnducUtGaGk5cTVQVUZJ
        aGZkYlpZUENRdEpWa3dzd3hDcHdQajU2SzlIV0kvd2RlOTR2eTZJVUtQYVhXOFdV
        cmcydER6cHZGSnJoNzVZbWxwUEZ3SEJyenJiemU0OTgyS2xpaVZmQ3YxRlRzd1Vh
        WGhCUnorTXVFemt1aFZLTjY1OXdIenBBblcxSEEyeURxZzNSQm1KTG51bVl4dWpN
        eHlqdWlTRm9WNVVxK0NybHExQy81bFRDcTNsWXlLT0J1b1dQalJvSUdLMlh3anlM
        aXA2OXhBMmtMZ0krbnBBa0JjdWxaQTVwSElGM3NTWmZrK2RzTnA5ajNKa1ZBZXBk
        Tkx6VTZUcHZocWk0WVk4aDI3Nnhid1g4YU5VcUNPNlRoRlk4Z21KVzVzeEw5NmtX
        QThKaE1uYXUwYUF5ZUpvSVN2cUcxU1NCaWdtbzVjUlBiZ2ZJMHIrMkptcEF4N1dG
        WExnbUZJZHJOUXVBWDJJcTlJbGpKNzJiWXpPakQ5TmZwdWc1ZXVrdW9yQ1JUMHpu
        VEpMNmdyY2FEZkFBYU1NMGVaU0xGOG0ra3Q0dTZhNllVcDZ4Q25DWlRVTmU0aVdw
        ZGl4NHlnUUVaZlJJMFpaUzVUU1hKN0RXSVFocHVZbi9KbDRIZG9zR1h6akFmWmYr
        OEZYR2ZoMDh4RG9uc1ROTkZldDlZVXllbXRDdHN0ZmF5ZW03Y1phQnAyMm5KS0xY
        L0djcG10Sm9oYTBLZjQ2V2dhRjROaC9wWFdvN1FEYzRvTmZoeHdxVDJsSGw3Vm1P
        SWpmYnBjRUcvb3AvdnBmbTFCNWoxKzdrMDJLVzNlcFlyeWUrQ1VSRU5qVEtrb0Ns
        T09FeDk5R1UzUG5Ub3JTS2dwMERZMmFpVDJwbmJIWFFGajNPLytFN0NPZWQrUjNu
        ZzBIeXFpMnFWYUxQTnpMckxMQXpDWEIwc2p1N3Z2dmUzMWhJR2tqS2JROFlOUGQ3
        Vng4aVNVL00xMHBLNkN1RmFYZFNPRUFlS25jUGZ2NFk1TU1pVGNHVjkrTDFqd05t
        TWVaWTNRWTZVZC9MZE14RWM5ZmF5R2lvbGRNL0JiT1hJdExhcXdlRk5FN0pULy92
        QTFNTFcrMmlvZlM4dTdFbTdyK3h5eExDWmFDdExsOU56dUQ1R2I5QkhRNVg5bkxN
        L3RsM0hRWmZib2d6WGJiQlVOL0VqQjdpNTg3VTAwYmFxYitVZU9CTHlPN3F1aFZw
        ckVwRnNadWlicEIvQWk5QzkyT3lQblh4b1VtVThER3VHUzljTm0xMitjKy9Oc1pr
        UUpWTCtqMnkwZ05wdDdDV0pGa2Y5ZzYvOGJpMnJDUFVkcVFXRkI0cGNTVlRDSXVM
        NXl2UjFqd1RGZWZTNHF1V251TTdFVVJTTVh2YmJvaWJZenpsMVE0YjVWNlN1S2xs
        eEwzdFFXcUJKTjBmWHMxMHF3QjZURCtXQzlubTlSb09HK0tyZnJrb2xVb2lQeGc4
        V2ZDMDJjWGlSMXc4UXQ1V2Qrc2hsc2lPTVVrcEt5WmNOUm53TnpNWlZPbXUvTU9k
        MGZBY0xDUzJuNFRwelpadjVscXVpdVJ0OEE0bmxHTmozQWFKZGpEaUxIU2tzZ2ZS
        WmZITmF6TDNIbW1peS8xYzJwcW5GcTIvNXppR0xnU0tjbFMzNnphb0NaQk9iWDZt
        SUtTdmZVbVlObXJUQXNOb3B3Znp4N1BQanpnQUtJekhtY285VmdlYmZGWENUSUZQ
        anZjclNUam9FWHJ0VCs2VTBHaDhFdEF3QVl1UUg0ZStqQmlMQThkaXZkVGhXcC9S
        Q3ZrUEJrc2RjOWl0VHo1YmFXUUdDNTBQdzEyNUNzemhBVkdrYTdqcUZ1eGZhUQpB
        TS9ZMGkvcUJkUlM2aHVRN3FGVkRVY3M5NWoxRkF3c2J3VmtqdXdzSUNNCi0tLSBR
        ZDVPNGJQS2FIZjVlT1dNVUdaZjNBelE2QUE2Q3ZaK08ycjlLOEZSU3U0CjdyXn9T
        Ib3BoeOj2Cker2nDqVFVguqTvRe+JqpQajfjDIVhZtTEG6ecEJ0aYMHvzwyyheVk
        1KbaLMYySb7ko98=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq13kgy63cgnvwlckua679c7jrant6jc932vc78zaejqatgh9ee2ys6yal5hsm0jdk9cl9vvyak9up8hf92sjwuscaagp6tvj5f20tn09k20nspt2ray3m7pnxrwvfc5j2md7esds275dpv2zeryjjh6w5mfzdppf9vjzu5p9v8ty7r338r8cndw4h4rpehyysjk828fqk9ga2543rc69jwenxywmnp76tmwcasz0s45wck7y5nyc52smhe3r84rv7a4zl5zg40gv4k5er5vw26c8cd73prkcnskpgpgqltqe75jf3ecfdpwp9sul38g8dsf6geskzrs3awtf36agxxz6aed4r3znqc0sdnfyuhezaflkeqjc69f3nfqcnrqfj04t4x7esq3w6t54rwp297m4zrpadqn3e3ch4rdwacc6j6dxdewzy8dk9qhrxdxgz07spcx44nwq45y72vsrje3q2wsmxnwxmnu8upq3nh34st2a3vqdkzafuz6sq49urmpewxnfuznyjpekp0yduzar3ssucegcapdjjqnrz7ckdv73c5ktksxt60txznpvap8jf2qg76zjyvn9lyd2sh67zvfvmzljv9e9pf98mh8s4xkg28m6r59hv2k59gktmynf47y99eg34rgx8xpeul4jwpkz7mvqe92cz25llpzy7s2enatnyv0323q6xz9fs3c47d2a0gc44w6m90fjgtl4uu8ywcv0s4m9gmx23e2s3kl8mfz5zfx9na39l9l3zvxuvme5pyvl7svnq7z89mx2fa8qzjv8wenhdyzg98hpv6x3my74s5u8p4ng3wsf8f56kzkvd8nvayz4zsqucrc8x2mzs5fhpjyjd29vd5ftwejz44rt9vqe5ez2ext9tqwuu2399ck52mch9q9lq8fyp9ppu0y04y09fq8gmu283etvskhcc9kz0zfv95zupt2s7x7dgn53hr4vgq3f2ekadkw8mp8e3pnhtfcrpjd93euer7uxqh3mjur78pzdwrrvxy0xr2andmnj8nwsa0qjkxeq99dqpdaxqe2jc99h6s5n0h7dcnmfm9uuaxpm84fq0tzjqmk9newrpsvuwry0jjvplv02zva20vh2s9jjrxxq3mpu8ywj8ufzalmuv4q0uphym4fp8eg9ukgk56mep52tdt4u7yz0sqy3delgk0pvd4gvfea3h5e4msv7uvyx6v07qelm2kpj38dj9rca0lpqa0wfzp05fvruh9fmgphxewj8xgx3rgmsrf2a4yn4mcs6ddkp2yc7svu7w80cexezg82qx5tdcr9wmxdpcxnsn82y8fkk95fphp5zvcyffnhm6pr2d04ww4vq9zm9j32gy898ce0ga5psj0y63u2gs62ekt5tp8s4h2yz04nvaqluc2ppaf5yaygx9lxketh3v7rwp397g30nmywg5sd0gd6cprpydf3x9pte3mx4h5ptuvtzyl82df8qvcfsdrvx8n8nafasf3h5rjjnjjp69eyw8qp30ydycj3d2lsgfky2vr873yvjmmuws95v9a43f4qd28w2p6pgaua3kf86alkmsyllljj7hnxezrz6fqapggrzg4vhazr82xvcp0k4erz6dzqrn95n6ueryap0vwxtq2e2qmmfev2w6x8630r3gqlj22ypgllm7fw5e9ql0l09l0g39v8un2gw5yvzvmqjtjcsxdp2le3ztkswgg0hvyeuqvf930xlxe9dwdtzcf0hygs9mcsdpwgu493vtljkzssqnkrh5evm2ycv8f0dz9z84cm0mnzjzgw9z74jznsdr7y77285d3svrgwg3d7essz4f5zhh2q928qmzfzj0m0w65kyda5hm6t5hrgywd3ajhfcm22qleneuxxt7u52u5asg8e9lx2lme8lm93f5cdw4gvcey4fql7hztg5cmq3l0
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-06T12:26:40Z"
  mac: ENC[AES256_GCM,data:YQ9YRhDhKs1oTfJUKf89y5/HDabEb9f8eTDpnlgC3XCYXmo0jNzH71MLWAfr4CO2T3I8shY1GsAuq9jyEWW9EVjcFnNIIET10E7WBkgGPE7G+F42fHtgbu9SZxNyLzUvOhkQ15rfkwpJi+1TbgqWHi4nieGbg4wLnxYGDvJpa5s=,iv:8mWoRhoSvFeD+GQhiFUgNKrXus8pTQASPZUNX/czd4U=,tag:Tucvz4swpzT5sG4/fddXMA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
