apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:4nQWWp5+a0ruT3jTGlMG0xVkKHAzaXEtzadmCvRe6FBDSd+xMWBcmQ==,iv:dOUt29ZTXK3nrfYDcuL7m7sjaEgyF1sBepjnOTAjpPY=,tag:xoYYgvVx6RNCmFvchw2CBA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGtNVzN5MUdp
        OSsrVU5YY1Z5cWZLeExsY0ZXaEJIY2g2SXQ2M1JUenFXbUFSMGxXcHNMYXludXFv
        S2dJYXYzMHZUZDBBK0dmN1hCZmVKa0E0NDR6WmRkWGwxZ2R4TzBLTlB0UkhGL1lV
        OUY1TzhMTC9vU2VMUGRhdEdoNjEyWnhiTDNyVVBNUzZETGg2dG15VTBOR3dHc3l5
        VTJrbFVoYTVRdEdWelpHanNMNXdGM2pmQ0N3YmNueGFqKzJJN1BOY0lhY3RsWkZ0
        Znh4cm5IdmpSOUVYdGx0R3FqOTNPUjBNOHg4K0haUzdyUVFRVzlWUExnSG53czR4
        VmljQVNSc3FEMG93dmpHMkJkSi9XdnR6SUFFcjd1Mk00K2tWbjhSVE5kUjdicW9M
        VVA3QkRZU3BHNDJ5ek9SckR2VURzL2kza1dOckx2d2JWL2pTWDBlb1JtOG5mRXBy
        ZnZtMTZzeW5FZUNvMWdQTjg0TnV2b3ZRWFhlcERlOGw4V0tlZmNESkVxQ21lcHZp
        TysyRGNOOFhiWW5IbUpLRkZmcGh6MkZJNk14cUFTbWNGYUMwTy9KTlNLdnlCSmhZ
        d3dodFJ1YVVJc1NtR0tUR1hsTVFDTWtxd2lUTDY2Q3pzb0RkUi85dmJDMlZqaHFl
        VjV6SVlwWWhnbTUvNk5Ld2llNTMrM251YnJDMWM0Y0VNWlNOd0EvVmVoL0lYa3NH
        M3FqeUhzWjRwZnZuTTRIRVBweVhlbDcrcUpHMUdvTmFDSmZPTmRoeHova3NCWHZz
        RDBWNzR0MkpLSXFmWHlLcnloS2QySHBNWFhNL1NpWFhLM0paTVhRenJXQnVQclNR
        R3ZkOUN1Uk1kdGEvOCsrRnNXanR1NWtkTFdTaXkwcWZ0b2xIVTVLLzduT292VHlk
        UW1aOWNTLytod2ZncWY3clE1QnQyTGFyZDZIODZXSlB1TFFnRTJPVWluTkgyeis5
        aU9UVUlMbDBWczdmajVyTTFtdnpySllOZFF5bHFsSkZqVlZSdnZxTWxPUmdPaU5K
        VStHeFo4TTJpUmJvcFlTVUdCSVlhbVZmcnE1TzhwTDNVRE1vVDIwWS81SHNiWHYv
        bXVSZUJGOE5MMkVqU3V3dkZpZW1uOFdWZForQXBFTWpXMUppK2dLUTA0M05na3NU
        OUJ0VnlFSklyZnhOYUh3ZXVNSi9xVkxza25nL0FSa0Z6Wkx2L0VIcG9Sbmp1aU8w
        MDk2VkgyZ1FpdGRtN254akZ6ZldvYjVLSjJSWjFNejBSbndmTkc0SVNBVVVuVlNW
        V2VFM0Fzb05kQWRDRGxqKzhEZDBOOG8xNGltZ2xYYlg0cE1WWmxDay8xZVp6WWpJ
        YWVCMVQwMkxnRmlobUR4cGVYUnhyTG53SFRndWxncFdKSjhXdmttUzJNL083VlNh
        aHd6bXNaRlBabDdBR0dWbDJEdlR0QmFLUW9Jd0ZQWWlybFBQcXZkamREbDl1Z3h2
        TEFGZGoyNXR2ZW0yZldqZ01ZNTcyT2E1QW9JNnd6VjRWZ25MRERtcDZDc0ZTMTg2
        ZUNzZjBPSlhmMXBTczliemRWVlNyZGdTaUtaQ3UzakF3Sm9yN3pQUzlPRkFzOFh6
        SGorcFhHRmo4UFRiTmNWbG0xcDN2WktIZ0JwejhrT3k0Y3lHZU1xQXRGMmxoQ1hs
        d1EzakJML3RZSWRXSm5zVzVwQkZQZ0VYQVlqQUhlREFxSXdPK3dkT0tQNGg2N2U5
        ZmZvb1RRamRuT3VSL1VTV0VpTWpRQUd4MDBQc2pVZlRvTnlXSjZlT1VYU2h1Wkcv
        UWtBWUlia0pKS3BNM3J2d1oyQUs5VjNyWGtSK1I3dmF5TGtTeFcvdkFJNmRnUmkx
        N01YZ1J1NXRCSGNtWXRFelNtTFlmOGgzL0NsZndGWVg4Wk11dm1Pa3JQUVJkUFM3
        ZTd4Y3FOOEkybDBRUjlOWUROWm1NRm81eVJmdG0zd2wwS0ZZaUNTMW9va3BVdwpl
        QjJoZmFtQkV2NWhybjYrWGhBYUxrV3h4aWltTm5YUWEwM2pmNHVVUFFBCi0tLSBE
        d21oNU5xUGNjWUJsNFdTZ3pqdll0UHo1V1ovSkhZRlIwajJiN2ppejZRCjfNtssB
        8lkn6X1Lr7/+2Wwo8grjRgXrUjxt3huqELgCrcPl2udcNFhZ4YY6k7Tt2H0MZKUO
        HElKEBMjz5H41Kw=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq13kgy63cgnvwlckua679c7jrant6jc932vc78zaejqatgh9ee2ys6yal5hsm0jdk9cl9vvyak9up8hf92sjwuscaagp6tvj5f20tn09k20nspt2ray3m7pnxrwvfc5j2md7esds275dpv2zeryjjh6w5mfzdppf9vjzu5p9v8ty7r338r8cndw4h4rpehyysjk828fqk9ga2543rc69jwenxywmnp76tmwcasz0s45wck7y5nyc52smhe3r84rv7a4zl5zg40gv4k5er5vw26c8cd73prkcnskpgpgqltqe75jf3ecfdpwp9sul38g8dsf6geskzrs3awtf36agxxz6aed4r3znqc0sdnfyuhezaflkeqjc69f3nfqcnrqfj04t4x7esq3w6t54rwp297m4zrpadqn3e3ch4rdwacc6j6dxdewzy8dk9qhrxdxgz07spcx44nwq45y72vsrje3q2wsmxnwxmnu8upq3nh34st2a3vqdkzafuz6sq49urmpewxnfuznyjpekp0yduzar3ssucegcapdjjqnrz7ckdv73c5ktksxt60txznpvap8jf2qg76zjyvn9lyd2sh67zvfvmzljv9e9pf98mh8s4xkg28m6r59hv2k59gktmynf47y99eg34rgx8xpeul4jwpkz7mvqe92cz25llpzy7s2enatnyv0323q6xz9fs3c47d2a0gc44w6m90fjgtl4uu8ywcv0s4m9gmx23e2s3kl8mfz5zfx9na39l9l3zvxuvme5pyvl7svnq7z89mx2fa8qzjv8wenhdyzg98hpv6x3my74s5u8p4ng3wsf8f56kzkvd8nvayz4zsqucrc8x2mzs5fhpjyjd29vd5ftwejz44rt9vqe5ez2ext9tqwuu2399ck52mch9q9lq8fyp9ppu0y04y09fq8gmu283etvskhcc9kz0zfv95zupt2s7x7dgn53hr4vgq3f2ekadkw8mp8e3pnhtfcrpjd93euer7uxqh3mjur78pzdwrrvxy0xr2andmnj8nwsa0qjkxeq99dqpdaxqe2jc99h6s5n0h7dcnmfm9uuaxpm84fq0tzjqmk9newrpsvuwry0jjvplv02zva20vh2s9jjrxxq3mpu8ywj8ufzalmuv4q0uphym4fp8eg9ukgk56mep52tdt4u7yz0sqy3delgk0pvd4gvfea3h5e4msv7uvyx6v07qelm2kpj38dj9rca0lpqa0wfzp05fvruh9fmgphxewj8xgx3rgmsrf2a4yn4mcs6ddkp2yc7svu7w80cexezg82qx5tdcr9wmxdpcxnsn82y8fkk95fphp5zvcyffnhm6pr2d04ww4vq9zm9j32gy898ce0ga5psj0y63u2gs62ekt5tp8s4h2yz04nvaqluc2ppaf5yaygx9lxketh3v7rwp397g30nmywg5sd0gd6cprpydf3x9pte3mx4h5ptuvtzyl82df8qvcfsdrvx8n8nafasf3h5rjjnjjp69eyw8qp30ydycj3d2lsgfky2vr873yvjmmuws95v9a43f4qd28w2p6pgaua3kf86alkmsyllljj7hnxezrz6fqapggrzg4vhazr82xvcp0k4erz6dzqrn95n6ueryap0vwxtq2e2qmmfev2w6x8630r3gqlj22ypgllm7fw5e9ql0l09l0g39v8un2gw5yvzvmqjtjcsxdp2le3ztkswgg0hvyeuqvf930xlxe9dwdtzcf0hygs9mcsdpwgu493vtljkzssqnkrh5evm2ycv8f0dz9z84cm0mnzjzgw9z74jznsdr7y77285d3svrgwg3d7essz4f5zhh2q928qmzfzj0m0w65kyda5hm6t5hrgywd3ajhfcm22qleneuxxt7u52u5asg8e9lx2lme8lm93f5cdw4gvcey4fql7hztg5cmq3l0
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-06T11:13:00Z"
  mac: ENC[AES256_GCM,data:UQ2Oq2CU+H6MAByEXbxEWDOmv0MIDDwnIWZbOp+kD38l334Z7g38IwX3c+uNIUot3aMTY6ILQRVhhDaad5KAtphhnN57akgRQNpukn7M6zqgEEBH9z1N+Bwn6IIAHD0uZTzGYOjm3Ft61E0JDc4j6hbpqSviAdaSYMvDiIdePpM=,iv:CT7UD0PSxV63jtibFHtaCH9QdoUUF5B/VOQWvNKwp9c=,tag:cd9eunmhG+KpuqbcbjcpRA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
