---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openclaw-test-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: openclaw-test-secret
    template:
      data:
        #        ANTHROPIC_API_KEY: "{{ .ANTHROPIC_API_KEY }}"
        #        OPENAI_API_KEY: "{{ .OPENAI_API_KEY }}"
        OPENCLAW_GATEWAY_TOKEN: "{{ .OPENCLAW_GATEWAY_TOKEN }}"
        #        OPENCLAW_GATEWAY_PASSWORD: "{{ .OPENCLAW_GATEWAY_PASSWORD }}"
        # SLACK API TOKENS
        SLACK_APP_TOKEN: "{{ .SLACK_OPENCLAW_APP_TOKEN }}"
        SLACK_BOT_TOKEN: "{{ .SLACK_OPENCLAW_BOT_USER_OAUTH_TOKEN }}"
        SLACK_BOT_USER_OAUTH_TOKEN: "{{ .SLACK_BOT_USER_OAUTH_TOKEN }}"
        SLACK_SIGNING_SECRET: "{{ .SLACK_OPENCLAW_APP_SIGNING_SECRET }}"
        SLACK_TALOS_HOMELAB_APP_TOKEN: "{{ .SLACK_TALOS_HOMELAB_APP_TOKEN }}"
        SLACK_USERID_ME: "{{ .SLACK_USERID_ME }}"
        SLACK_DEVOPS_CHANNEL_ID: "{{ .SLACK_DEVOPS_CHANNEL_ID }}"
        SLACK_CLAW_CHANNEL_ID: "{{ .SLACK_CLAW_CHANNEL_ID }}"
        # TELEGRAM API TOKENS
        TELEGRAM_BOT_TOKEN: "{{ .TELEGRAM_BOT_TOKEN }}"
        # Gemini API Key
        GOOGLE_API_KEY: "{{ .OPENCLAW_GEMINI_API_KEY }}"
        # Discord API Keys
        DISCORD_BOT_TOKEN: "{{ .OPENCLAW_DISCORD_BOT_TOKEN }}"
        DISCORD_SERVER_ID: "{{ .DISCORD_SERVER_ID }}"
        DISCORD_CHANNEL_ID: "{{ .DISCORD_CHANNEL_ID }}"
        PLANNER_BOT_TOKEN: "{{ .PLANNER_DISCORD_BOT_TOKEN }}"
        IDEATOR_BOT_TOKEN: "{{ .IDEATOR_DISCORD_BOT_TOKEN }}"
        CRITIC_BOT_TOKEN: "{{ .CRITIC_DISCORD_BOT_TOKEN }}"
        SURVEYOR_BOT_TOKEN: "{{ .SURVEYOR_DISCORD_BOT_TOKEN }}"
        CODER_BOT_TOKEN: "{{ .CODER_DISCORD_BOT_TOKEN }}"
        WRITER_BOT_TOKEN: "{{ .WRITER_DISCORD_BOT_TOKEN }}"
        REVIEWER_BOT_TOKEN: "{{ .REVIEWER_DISCORD_BOT_TOKEN }}"
        SCOUT_BOT_TOKEN: "{{ .SCOUT_DISCORD_BOT_TOKEN }}"
        DISCORD_PLANNER_CHANNEL_ID: "{{ .DISCORD_PLANNER_CHANNEL_ID }}"
        DISCORD_IDEATOR_CHANNEL_ID: "{{ .DISCORD_IDEATOR_CHANNEL_ID }}"
        DISCORD_CRITIC_CHANNEL_ID: "{{ .DISCORD_CRITIC_CHANNEL_ID }}"
        DISCORD_SURVEYOR_CHANNEL_ID: "{{ .DISCORD_SURVEYOR_CHANNEL_ID }}"
        DISCORD_CODER_CHANNEL_ID: "{{ .DISCORD_CODER_CHANNEL_ID }}"
        DISCORD_WRITER_CHANNEL_ID: "{{ .DISCORD_WRITER_CHANNEL_ID }}"
        DISCORD_REVIEWER_CHANNEL_ID: "{{ .DISCORD_REVIEWER_CHANNEL_ID }}"
        DISCORD_SCOUT_CHANNEL_ID: "{{ .DISCORD_SCOUT_CHANNEL_ID }}"
        DISCORD_GENERAL_VOICE_CHANNEL_ID: "{{ .DISCORD_GENERAL_VOICE_CHANNEL_ID }}"
        MY_DISCORD_USERID: "{{ .MY_DISCORD_USERID }}"
        # Github Fine Grained PAT Tokens
        BACKUP_TOKEN: "{{ .OPENCLAW_BACKUP_GH_PAT }}"
        BACKUP_REPO: "{{ .OPENCLAW_BACKUP_GH_REPO }}"
        OLLAMA_API_KEY: "not-needed"
        # Groq access https://console.groq.com/
        GROQ_API_KEY: "{{ .GROQ_API_KEY }}"
        # Github PAT for access to Obsidian vault repo https://github.com/dstewen/Obsidian_Vault_Openclaw
        OPENCLAW_OBSIDIANVAULT_GH_PAT: "{{ .OPENCLAW_OBSIDIANVAULT_GH_PAT }}"
        # Github PAT for access to Talos Homelab repo https://github.com/dstewen/talos-homelab
        GITHUB_TOKEN: "{{ .OPENCLAW_TEST_GITHUB_TOKEN }}"
        # Mistral API Key - free tier
        MISTRAL_API_KEY: "{{ .MISTRAL_API_KEY }}"
        # Elevenlabs API key
        ELEVENLABS_API_KEY: "{{ .ELEVENLABS_API_KEY }}"
        ELEVENLABS_VOICE_ID: "{{ .ELEVENLABS_VOICE_ID }}"
        # Home-Assistant
        HA_URL: "{{ .HA_URL }}"
        # Home-Assistant Talos token
        HA_TOKEN: "{{ .HA_OPENCLAW_TOKEN }}"
        # LiteLLM Virtual API Key
        LITELLM_API_KEY: "{{ .LITELLM_VIRTUAL_KEY_OPENCLAW_TEST }}"
        # WikiJS token
        WIKI_URL: "{{ .WIKI_URL }}"
        WIKI_KEY: "{{ .WIKI_KEY }}"
  dataFrom:
    - extract:
        key: home-assistant
    - extract:
        key: openclaw-test
    - extract:
        key: slackapi
    - extract:
        key: telegram-bot
