---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/monitoring.coreos.com/scrapeconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: proxmox-hosts
spec:
  staticConfigs:
    - targets:
        - "pve1.davidstewen.com:9100"
        - "pve2.davidstewen.com:9100"
        - "pve3.davidstewen.com:9100"
#      labels:
#        application: MyMinecraftModPack
#        instance: node1.unrealhosting.fr
