---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/volsync.backube/replicationdestination_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: esphome-dest
  namespace: home
spec:
  trigger:
    manual: restore-once
  restic:
    repository: esphome-restic-secret
    copyMethod: Direct
    destinationPVC: esphome-config
    storageClassName: local-hostpath
