---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnative-pg
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: cloudnative-pg
  maxHistory: 3
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    #  affinity:
    #    nodeAffinity:
    #      requiredDuringSchedulingIgnoredDuringExecution:
    #        nodeSelectorTerms:
    #        - matchExpressions:
    #          - key: kubernetes.io/arch
    #            operator: In
    #            values:
    #            - arm64
    #      preferredDuringSchedulingIgnoredDuringExecution:
    #      - weight: 50
    #        preference:
    #          matchExpressions:
    #          - key: node-role.kubernetes.io/worker
    #            operator: In
    #            values:
    #            - worker
    crds:
      create: true
    config:
      data:
        INHERITED_ANNOTATIONS: kyverno.io/ignore
    monitoring:
      podMonitorEnabled: false
      grafanaDashboard:
        create: true
#    nodeSelector:
#      kubernetes.io/arch: arm64
