---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name lubelog-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *name
    template:
      data:
        # app
        POSTGRES_CONNECTION: "Host=postgres18-rw.database.svc.cluster.local:5432;Username={{ .LUBELOGGER_POSTGRES_USER }};Password={{ .LUBELOGGER_POSTGRES_PASS }};Database=lubelog"
        # # OIDC
        # OpenIDConfig__Name: authentik
        # OpenIDConfig__ClientId: "{{ .LUBELOG_CLIENT_ID }}"
        # OpenIDConfig__ClientSecret: "{{ .LUBELOG_CLIENT_SECRET }}"
        # OpenIDConfig__AuthURL: https://sso.${SECRET_DOMAIN}/application/o/authorize/
        # OpenIDConfig__TokenURL: https://sso.${SECRET_DOMAIN}/application/o/token/
        # OpenIDConfig__RedirectURL: https://lubelog.${SECRET_DOMAIN}/Login/RemoteAuth
        # OpenIDConfig__Scope: email
        # Database init
        INIT_POSTGRES_DBNAME: lubelog
        INIT_POSTGRES_HOST: postgres18-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .LUBELOGGER_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .LUBELOGGER_POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"

  dataFrom:
    - extract:
        key: lubelogger
    - extract:
        key: cloudnative-pg
