---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app lubelogger
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: lubelogger
  values:
    controllers:
      lubelogger:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: 18.6
              pullPolicy: IfNotPresent
            envFrom: &envFrom
              - secretRef:
                  name: lubelog-secret
        containers:
          app:
            image:
              repository: ghcr.io/hargata/lubelogger
              tag: v1.7.3@sha256:c9d2bbb48c7f84d90e54496e2cd60422e56a5f2345c8a539ebe09f77e629d321
            env:
              TZ: ${TIMEZONE}
              LC_ALL: en_US.UTF-8
              POSTGRES_CONNECTION:
                valueFrom:
                  secretKeyRef:
                    name: lubelog-secret
                    key: POSTGRES_CONNECTION
            probes:
              liveness: &probes
                enabled: false
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: &port 8080
                  initialDelaySeconds: 15
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 20m
                memory: 128Mi
              limits:
                memory: 256Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        ports:
          http:
            port: *port
    route:
      app:
        hostnames:
          - "lubelogger.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: *port
    persistence:
      config:
        existingClaim: "lubelogger"
        globalMounts:
          - path: /App/config
            subPath: config
          - path: /App/data
            subPath: data
          - path: /App/wwwroot/translations
            subPath: translations
          - path: /App/wwwroot/documents
            subPath: documents
          - path: /App/wwwroot/images
            subPath: images
          - path: /App/log
            subPath: log
          - path: /root/.aspnet/DataProtection-Keys
            subPath: keys
      tmp:
        type: emptyDir
        globalMounts:
          - path: /App/wwwroot/temp
