---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/inference.llmkube.dev/model_v1alpha1.json
apiVersion: inference.llmkube.dev/v1alpha1
kind: Model
metadata:
  name: phi4-mini-instruct
  namespace: ai
spec:
  source: pvc://llmkube-model-cache/unsloth/Phi-4-mini-instruct-GGUF/Phi-4-mini-instruct-Q4_K_M.gguf
  format: gguf
  hardware:
    accelerator: intel
    gpu:
      enabled: true
      count: 1
      vendor: intel
      layers: -1
      resourceClaims:
        - name: gpu
          resourceClaimTemplateName: llmkube-models-gpu
  resources:
    cpu: "2"
    memory: "4Gi"
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/inference.llmkube.dev/inferenceservice_v1alpha1.json
apiVersion: inference.llmkube.dev/v1alpha1
kind: InferenceService
metadata:
  name: phi4-mini-instruct
  namespace: ai
spec:
  modelRef: phi4-mini-instruct
  replicas: 1
  image: ghcr.io/ggml-org/llama.cpp:server-intel@sha256:0bccb61b36d5a56fd06e35dfd34bef80a1ac5cd3a24d5cc8f20b5245cb40ab3a
  resources:
    cpu: "2"
    memory: "4Gi"
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    privileged: true
#  podSecurityContext:
#    runAsUser: 1000
#    runAsGroup: 1000
#    fsGroup: 102
#    supplementalGroups:
#      - 44
#      - 102
#    seccompProfile:
#      type: RuntimeDefault
